// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountSourcePostings = `-- name: AdminCountSourcePostings :one

SELECT count(*)::bigint AS total,
       count(*) FILTER (WHERE o.merged_into IS NOT NULL)::bigint AS merged,
       count(*) FILTER (WHERE EXISTS (
           SELECT 1 FROM opportunity_source os2
            WHERE os2.opportunity_id = o.id AND os2.source_id <> $1
       ))::bigint AS also_seen_elsewhere
  FROM opportunity o
 WHERE EXISTS (SELECT 1 FROM opportunity_source os
                WHERE os.opportunity_id = o.id AND os.source_id = $1)
`

type AdminCountSourcePostingsRow struct {
	Total             int64
	Merged            int64
	AlsoSeenElsewhere int64
}

// ---------------------------------------------------------------- purge
// What a source purge would remove, counted before it runs.
func (q *Queries) AdminCountSourcePostings(ctx context.Context, sourceID pgtype.UUID) (AdminCountSourcePostingsRow, error) {
	row := q.db.QueryRow(ctx, adminCountSourcePostings, sourceID)
	var i AdminCountSourcePostingsRow
	err := row.Scan(&i.Total, &i.Merged, &i.AlsoSeenElsewhere)
	return i, err
}

const adminDeleteMergeRecordsFor = `-- name: AdminDeleteMergeRecordsFor :execrows
DELETE FROM opportunity_merge
 WHERE from_opportunity_id = ANY ($1::uuid[])
    OR into_opportunity_id = ANY ($1::uuid[])
`

// Merge records referencing postings the purge is about to remove.
//
// Deleted explicitly rather than by cascade, and counted, so the purge report
// says how much merge history went with the source. A foreign key with no ON
// DELETE clause would otherwise block the purge entirely, which is how "retire
// this source" turns into an afternoon of manual SQL.
func (q *Queries) AdminDeleteMergeRecordsFor(ctx context.Context, opportunityIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteMergeRecordsFor, opportunityIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteOrphanedAmong = `-- name: AdminDeleteOrphanedAmong :execrows
DELETE FROM opportunity o
 WHERE o.id = ANY ($1::uuid[])
   AND NOT EXISTS (SELECT 1 FROM opportunity_source os WHERE os.opportunity_id = o.id)
`

// Removes postings left with no provenance at all, from the bounded candidate set.
//
// Scoped to the ids this source contributed to, NOT table-wide. A table-wide
// orphan sweep would delete unrelated postings as a side effect of purging one
// source: cleanup with unbounded blast radius, which is the kind of helpfulness
// that causes the second incident.
//
// Two steps rather than one cascading delete, because a posting seen on a second
// source must SURVIVE the purge of the first. Deleting by source would take those
// with it, which is data loss disguised as cleanup.
func (q *Queries) AdminDeleteOrphanedAmong(ctx context.Context, opportunityIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteOrphanedAmong, opportunityIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteSourceRows = `-- name: AdminDeleteSourceRows :execrows
DELETE FROM opportunity_source WHERE source_id = $1
`

// Drops this source's provenance rows only.
func (q *Queries) AdminDeleteSourceRows(ctx context.Context, sourceID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteSourceRows, sourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminListFlags = `-- name: AdminListFlags :many
SELECT f.id, f.opportunity_id, f.reason, f.detail, f.status, f.created_at,
       o.title_raw, o.closed_at,
       c.display_name AS company_name,
       (SELECT count(*) FROM opportunity_flag x
         WHERE x.opportunity_id = f.opportunity_id)::bigint AS flags_on_posting
  FROM opportunity_flag f
  JOIN opportunity o ON o.id = f.opportunity_id
  LEFT JOIN company c ON c.id = o.company_id
 WHERE ($1::text IS NULL OR f.status = $1::text)
 ORDER BY (f.status = 'open') DESC, f.created_at
 LIMIT $2
`

type AdminListFlagsParams struct {
	Status   *string
	PageSize int32
}

type AdminListFlagsRow struct {
	ID             pgtype.UUID
	OpportunityID  pgtype.UUID
	Reason         string
	Detail         *string
	Status         string
	CreatedAt      pgtype.Timestamptz
	TitleRaw       string
	ClosedAt       pgtype.Timestamptz
	CompanyName    *string
	FlagsOnPosting int64
}

// The review queue, oldest first: a scam report that has sat for a day is more
// urgent than one raised a minute ago.
func (q *Queries) AdminListFlags(ctx context.Context, arg AdminListFlagsParams) ([]AdminListFlagsRow, error) {
	rows, err := q.db.Query(ctx, adminListFlags, arg.Status, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListFlagsRow
	for rows.Next() {
		var i AdminListFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.OpportunityID,
			&i.Reason,
			&i.Detail,
			&i.Status,
			&i.CreatedAt,
			&i.TitleRaw,
			&i.ClosedAt,
			&i.CompanyName,
			&i.FlagsOnPosting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMergeCandidates = `-- name: AdminListMergeCandidates :many
SELECT mc.id, mc.left_opportunity_id, mc.right_opportunity_id,
       mc.reason, mc.confidence, mc.withheld_because, mc.created_at,
       l.title_raw AS left_title, r.title_raw AS right_title
  FROM merge_candidate mc
  JOIN opportunity l ON l.id = mc.left_opportunity_id
  JOIN opportunity r ON r.id = mc.right_opportunity_id
 WHERE mc.resolution IS NULL
 ORDER BY mc.confidence DESC, mc.created_at
 LIMIT $1
`

type AdminListMergeCandidatesRow struct {
	ID                 pgtype.UUID
	LeftOpportunityID  pgtype.UUID
	RightOpportunityID pgtype.UUID
	Reason             string
	Confidence         float32
	WithheldBecause    string
	CreatedAt          pgtype.Timestamptz
	LeftTitle          string
	RightTitle         string
}

// The review queue for merges dedup declined to make automatically.
func (q *Queries) AdminListMergeCandidates(ctx context.Context, pageSize int32) ([]AdminListMergeCandidatesRow, error) {
	rows, err := q.db.Query(ctx, adminListMergeCandidates, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMergeCandidatesRow
	for rows.Next() {
		var i AdminListMergeCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.LeftOpportunityID,
			&i.RightOpportunityID,
			&i.Reason,
			&i.Confidence,
			&i.WithheldBecause,
			&i.CreatedAt,
			&i.LeftTitle,
			&i.RightTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMergedInto = `-- name: AdminListMergedInto :many
SELECT o.id, o.title_raw, o.merged_into, o.version,
       (SELECT count(*) FROM opportunity_source os WHERE os.opportunity_id = o.id)::bigint
         AS source_rows
  FROM opportunity o
 WHERE o.merged_into = $1
 ORDER BY o.first_seen_at
`

type AdminListMergedIntoRow struct {
	ID         pgtype.UUID
	TitleRaw   string
	MergedInto pgtype.UUID
	Version    int32
	SourceRows int64
}

// Postings merged INTO this one. The un-merge candidates.
func (q *Queries) AdminListMergedInto(ctx context.Context, canonicalID pgtype.UUID) ([]AdminListMergedIntoRow, error) {
	rows, err := q.db.Query(ctx, adminListMergedInto, canonicalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMergedIntoRow
	for rows.Next() {
		var i AdminListMergedIntoRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRaw,
			&i.MergedInto,
			&i.Version,
			&i.SourceRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSources = `-- name: AdminListSources :many

SELECT s.id, s.name, s.tier, s.type, s.status,
       s.last_success_at, s.last_failure_at,
       s.items_discovered, s.items_processed,
       s.legal_basis, s.robots_checked_at, s.terms_reviewed_at, s.reviewed_by,
       s.poll_interval, s.etag_supported,
       (SELECT count(*) FROM opportunity_source os WHERE os.source_id = s.id)::bigint
         AS postings_attributed
  FROM source s
 ORDER BY (s.status <> 'active') DESC, s.name
`

type AdminListSourcesRow struct {
	ID                 pgtype.UUID
	Name               string
	Tier               string
	Type               string
	Status             string
	LastSuccessAt      pgtype.Timestamptz
	LastFailureAt      pgtype.Timestamptz
	ItemsDiscovered    int64
	ItemsProcessed     int64
	LegalBasis         string
	RobotsCheckedAt    pgtype.Timestamptz
	TermsReviewedAt    pgtype.Timestamptz
	ReviewedBy         *string
	PollInterval       pgtype.Interval
	EtagSupported      bool
	PostingsAttributed int64
}

// ------------------------------------------------------------------- sources
// The source list with the health columns the blueprint's §29 table names, so one
// screen answers "which source is broken".
func (q *Queries) AdminListSources(ctx context.Context) ([]AdminListSourcesRow, error) {
	rows, err := q.db.Query(ctx, adminListSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListSourcesRow
	for rows.Next() {
		var i AdminListSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tier,
			&i.Type,
			&i.Status,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.ItemsDiscovered,
			&i.ItemsProcessed,
			&i.LegalBasis,
			&i.RobotsCheckedAt,
			&i.TermsReviewedAt,
			&i.ReviewedBy,
			&i.PollInterval,
			&i.EtagSupported,
			&i.PostingsAttributed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminOpportunitySources = `-- name: AdminOpportunitySources :many

SELECT os.id, os.source_id, s.name AS source_name,
       os.ats_type, os.ats_job_id, os.source_job_id, os.apply_url,
       os.merge_reason, os.merge_confidence, os.merged_by,
       os.first_seen_at, os.last_seen_at
  FROM opportunity_source os
  JOIN source s ON s.id = os.source_id
 WHERE os.opportunity_id = $1
 ORDER BY os.first_seen_at
`

type AdminOpportunitySourcesRow struct {
	ID              pgtype.UUID
	SourceID        pgtype.UUID
	SourceName      string
	AtsType         *string
	AtsJobID        *string
	SourceJobID     string
	ApplyUrl        *string
	MergeReason     *string
	MergeConfidence *float32
	MergedBy        *string
	FirstSeenAt     pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
}

// ------------------------------------------------------------- provenance
// Every opportunity_source row for one posting, including merged ones.
//
// Hard rule 11: dedup never deletes a source row, so this is the full provenance
// of a canonical posting and the input to an un-merge decision.
func (q *Queries) AdminOpportunitySources(ctx context.Context, opportunityID pgtype.UUID) ([]AdminOpportunitySourcesRow, error) {
	rows, err := q.db.Query(ctx, adminOpportunitySources, opportunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminOpportunitySourcesRow
	for rows.Next() {
		var i AdminOpportunitySourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.SourceName,
			&i.AtsType,
			&i.AtsJobID,
			&i.SourceJobID,
			&i.ApplyUrl,
			&i.MergeReason,
			&i.MergeConfidence,
			&i.MergedBy,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRequeueOpportunity = `-- name: AdminRequeueOpportunity :execrows
UPDATE opportunity
   SET pipeline_state = $1,
       attempts = 0, last_error = NULL, next_attempt_at = now(), lease_until = NULL
 WHERE id = $2 AND merged_into IS NULL
`

type AdminRequeueOpportunityParams struct {
	TargetState   string
	OpportunityID pgtype.UUID
}

func (q *Queries) AdminRequeueOpportunity(ctx context.Context, arg AdminRequeueOpportunityParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminRequeueOpportunity, arg.TargetState, arg.OpportunityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminRequeueSource = `-- name: AdminRequeueSource :execrows

UPDATE opportunity o
   SET pipeline_state = $1,
       attempts = 0, last_error = NULL, next_attempt_at = now(), lease_until = NULL
 WHERE o.merged_into IS NULL
   AND EXISTS (SELECT 1 FROM opportunity_source os
                WHERE os.opportunity_id = o.id AND os.source_id = $2)
`

type AdminRequeueSourceParams struct {
	TargetState string
	SourceID    pgtype.UUID
}

// --------------------------------------------------------------- re-runs
// Re-run controls. Sends every posting from one source back to a chosen pipeline
// state so it is re-parsed, re-extracted or re-embedded.
//
// Resets attempts and clears the lease, because a record that already exhausted
// its retries would otherwise sit in the new state and never be claimed. Merged
// rows are excluded: they are not independently processed.
func (q *Queries) AdminRequeueSource(ctx context.Context, arg AdminRequeueSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminRequeueSource, arg.TargetState, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminResolveFlag = `-- name: AdminResolveFlag :one
UPDATE opportunity_flag
   SET status = $1, resolution_note = $2,
       resolved_by = $3, resolved_at = now()
 WHERE id = $4 AND status = 'open'
RETURNING id, opportunity_id, status
`

type AdminResolveFlagParams struct {
	Status         string
	ResolutionNote *string
	ResolvedBy     pgtype.UUID
	FlagID         pgtype.UUID
}

type AdminResolveFlagRow struct {
	ID            pgtype.UUID
	OpportunityID pgtype.UUID
	Status        string
}

func (q *Queries) AdminResolveFlag(ctx context.Context, arg AdminResolveFlagParams) (AdminResolveFlagRow, error) {
	row := q.db.QueryRow(ctx, adminResolveFlag,
		arg.Status,
		arg.ResolutionNote,
		arg.ResolvedBy,
		arg.FlagID,
	)
	var i AdminResolveFlagRow
	err := row.Scan(&i.ID, &i.OpportunityID, &i.Status)
	return i, err
}

const adminResolveMergeCandidate = `-- name: AdminResolveMergeCandidate :one
UPDATE merge_candidate
   SET resolution = $1,
       resolved_by = $2,
       resolved_at = now()
 WHERE id = $3 AND resolution IS NULL
RETURNING id, left_opportunity_id, right_opportunity_id, resolution
`

type AdminResolveMergeCandidateParams struct {
	Resolution  *string
	ResolvedBy  *string
	CandidateID pgtype.UUID
}

type AdminResolveMergeCandidateRow struct {
	ID                 pgtype.UUID
	LeftOpportunityID  pgtype.UUID
	RightOpportunityID pgtype.UUID
	Resolution         *string
}

func (q *Queries) AdminResolveMergeCandidate(ctx context.Context, arg AdminResolveMergeCandidateParams) (AdminResolveMergeCandidateRow, error) {
	row := q.db.QueryRow(ctx, adminResolveMergeCandidate, arg.Resolution, arg.ResolvedBy, arg.CandidateID)
	var i AdminResolveMergeCandidateRow
	err := row.Scan(
		&i.ID,
		&i.LeftOpportunityID,
		&i.RightOpportunityID,
		&i.Resolution,
	)
	return i, err
}

const adminSetSourceStatus = `-- name: AdminSetSourceStatus :one
UPDATE source SET status = $1, updated_at = now()
 WHERE id = $2
RETURNING id, name, status
`

type AdminSetSourceStatusParams struct {
	Status   string
	SourceID pgtype.UUID
}

type AdminSetSourceStatusRow struct {
	ID     pgtype.UUID
	Name   string
	Status string
}

// Quarantine is reversible and never destructive: a quarantined source stops
// being polled, and hard rule 9 means its postings are NOT closed as a result.
// Inferring closure from a quarantined source is how one outage deletes the
// corpus.
func (q *Queries) AdminSetSourceStatus(ctx context.Context, arg AdminSetSourceStatusParams) (AdminSetSourceStatusRow, error) {
	row := q.db.QueryRow(ctx, adminSetSourceStatus, arg.Status, arg.SourceID)
	var i AdminSetSourceStatusRow
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const adminSourceHealthHistory = `-- name: AdminSourceHealthHistory :many
SELECT day, polls, poll_failures, not_modified,
       postings_seen, postings_usable,
       with_company, with_location, with_apply_url, with_language, with_salary
  FROM source_health_daily
 WHERE source_id = $1
 ORDER BY day DESC
 LIMIT $2
`

type AdminSourceHealthHistoryParams struct {
	SourceID pgtype.UUID
	Days     int32
}

type AdminSourceHealthHistoryRow struct {
	Day            pgtype.Date
	Polls          int32
	PollFailures   int32
	NotModified    int32
	PostingsSeen   int32
	PostingsUsable int32
	WithCompany    int32
	WithLocation   int32
	WithApplyUrl   int32
	WithLanguage   int32
	WithSalary     int32
}

// Per-day history for one source, so parser rot is visible as a trend rather than
// a single bad number.
func (q *Queries) AdminSourceHealthHistory(ctx context.Context, arg AdminSourceHealthHistoryParams) ([]AdminSourceHealthHistoryRow, error) {
	rows, err := q.db.Query(ctx, adminSourceHealthHistory, arg.SourceID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSourceHealthHistoryRow
	for rows.Next() {
		var i AdminSourceHealthHistoryRow
		if err := rows.Scan(
			&i.Day,
			&i.Polls,
			&i.PollFailures,
			&i.NotModified,
			&i.PostingsSeen,
			&i.PostingsUsable,
			&i.WithCompany,
			&i.WithLocation,
			&i.WithApplyUrl,
			&i.WithLanguage,
			&i.WithSalary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSourceOpportunityIDs = `-- name: AdminSourceOpportunityIDs :many
SELECT DISTINCT os.opportunity_id
  FROM opportunity_source os
 WHERE os.source_id = $1
`

// The postings this source contributed to, captured BEFORE its provenance rows
// are deleted. Everything the purge may touch is bounded by this list.
func (q *Queries) AdminSourceOpportunityIDs(ctx context.Context, sourceID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, adminSourceOpportunityIDs, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var opportunity_id pgtype.UUID
		if err := rows.Scan(&opportunity_id); err != nil {
			return nil, err
		}
		items = append(items, opportunity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenFlags = `-- name: CountOpenFlags :one
SELECT count(*)::bigint FROM opportunity_flag WHERE status = 'open'
`

func (q *Queries) CountOpenFlags(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenFlags)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFlag = `-- name: CreateFlag :one

INSERT INTO opportunity_flag (opportunity_id, reported_by, reason, detail)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateFlagParams struct {
	OpportunityID pgtype.UUID
	ReportedBy    pgtype.UUID
	Reason        string
	Detail        *string
}

type CreateFlagRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// ------------------------------------------------------------------ flags
// Raised by a user against a posting. One open flag per user per posting is
// enforced by a partial unique index, so a duplicate is a conflict rather than
// more signal.
func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (CreateFlagRow, error) {
	row := q.db.QueryRow(ctx, createFlag,
		arg.OpportunityID,
		arg.ReportedBy,
		arg.Reason,
		arg.Detail,
	)
	var i CreateFlagRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const grantAdmin = `-- name: GrantAdmin :execrows
UPDATE app_user SET role = 'admin', updated_at = now()
 WHERE email = $1 AND status = 'active'
`

// Deliberately not exposed over HTTP. Granting admin is a bootstrap and recovery
// operation, done from the binary with database access, so a compromised admin
// session cannot mint more admins.
func (q *Queries) GrantAdmin(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, grantAdmin, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isAdmin = `-- name: IsAdmin :one
SELECT (role = 'admin')::boolean AS is_admin
  FROM app_user WHERE id = $1 AND status = 'active'
`

// Authorization is one query in one place. A per-handler check is how one handler
// ends up missing it.
func (q *Queries) IsAdmin(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, userID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, created_at FROM app_user WHERE role = 'admin' ORDER BY email
`

type ListAdminsRow struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsRow
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdmin = `-- name: RevokeAdmin :execrows
UPDATE app_user SET role = 'user', updated_at = now()
 WHERE email = $1
`

func (q *Queries) RevokeAdmin(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAdmin, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
