// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT count(*) FROM audit_log
`

func (q *Queries) CountAuditEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_token (family_id, user_id, session_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, family_id, user_id, session_id, token_hash, used_at, replaced_by, revoked_at, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	FamilyID  pgtype.UUID
	UserID    pgtype.UUID
	SessionID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.FamilyID,
		arg.UserID,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.UsedAt,
		&i.ReplacedBy,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_session (user_id, token_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, token_hash, user_agent, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	UserAgent *string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenant (kind, display_name) VALUES ($1, $2) RETURNING id, kind, display_name, created_at
`

type CreateTenantParams struct {
	Kind        string
	DisplayName *string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Kind, arg.DisplayName)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (tenant_id, email, password_hash)
VALUES ($1, $2, $3) RETURNING id, tenant_id, email, password_hash, email_verified_at, status, failed_logins, locked_until, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     pgtype.UUID
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.TenantID, arg.Email, arg.PasswordHash)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastAuditHash = `-- name: GetLastAuditHash :one
SELECT entry_hash FROM audit_log ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLastAuditHash(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLastAuditHash)
	var entry_hash []byte
	err := row.Scan(&entry_hash)
	return entry_hash, err
}

const getLiveSessionByHash = `-- name: GetLiveSessionByHash :one
SELECT id, user_id, token_hash, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM user_session
 WHERE token_hash = $1
   AND revoked_at IS NULL
   AND expires_at > now()
`

func (q *Queries) GetLiveSessionByHash(ctx context.Context, tokenHash []byte) (UserSession, error) {
	row := q.db.QueryRow(ctx, getLiveSessionByHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshByHash = `-- name: GetRefreshByHash :one
SELECT id, family_id, user_id, session_id, token_hash, used_at, replaced_by, revoked_at, expires_at, created_at FROM refresh_token WHERE token_hash = $1
`

func (q *Queries) GetRefreshByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.UsedAt,
		&i.ReplacedBy,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, email_verified_at, status, failed_logins, locked_until, last_login_at, created_at, updated_at FROM app_user WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, email_verified_at, status, failed_logins, locked_until, last_login_at, created_at, updated_at FROM app_user WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :one
INSERT INTO audit_log (actor_id, tenant_id, action, subject, metadata, prev_hash, entry_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, occurred_at, actor_id, tenant_id, action, subject, metadata, prev_hash, entry_hash
`

type InsertAuditParams struct {
	ActorID   pgtype.UUID
	TenantID  pgtype.UUID
	Action    string
	Subject   *string
	Metadata  []byte
	PrevHash  []byte
	EntryHash []byte
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAudit,
		arg.ActorID,
		arg.TenantID,
		arg.Action,
		arg.Subject,
		arg.Metadata,
		arg.PrevHash,
		arg.EntryHash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.ActorID,
		&i.TenantID,
		&i.Action,
		&i.Subject,
		&i.Metadata,
		&i.PrevHash,
		&i.EntryHash,
	)
	return i, err
}

const listAuditForChainCheck = `-- name: ListAuditForChainCheck :many
SELECT id, prev_hash, entry_hash, action, occurred_at FROM audit_log ORDER BY id
`

type ListAuditForChainCheckRow struct {
	ID         int64
	PrevHash   []byte
	EntryHash  []byte
	Action     string
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) ListAuditForChainCheck(ctx context.Context) ([]ListAuditForChainCheckRow, error) {
	rows, err := q.db.Query(ctx, listAuditForChainCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditForChainCheckRow
	for rows.Next() {
		var i ListAuditForChainCheckRow
		if err := rows.Scan(
			&i.ID,
			&i.PrevHash,
			&i.EntryHash,
			&i.Action,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuditChain = `-- name: LockAuditChain :exec
SELECT pg_advisory_xact_lock(hashtext('devsignal.audit_log'))
`

// Serializes audit inserts for the duration of the transaction so two writers
// cannot both chain off the same previous hash. Audit volume is low; the
// contention is irrelevant and the chain integrity is not.
func (q *Queries) LockAuditChain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAuditChain)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE app_user SET email_verified_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const markRefreshUsed = `-- name: MarkRefreshUsed :exec
UPDATE refresh_token SET used_at = now(), replaced_by = $2 WHERE id = $1
`

type MarkRefreshUsedParams struct {
	ID         pgtype.UUID
	ReplacedBy pgtype.UUID
}

func (q *Queries) MarkRefreshUsed(ctx context.Context, arg MarkRefreshUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshUsed, arg.ID, arg.ReplacedBy)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE app_user
   SET failed_logins = failed_logins + 1,
       locked_until = CASE WHEN failed_logins + 1 >= $1::int
                           THEN now() + $2::interval
                           ELSE locked_until END
 WHERE id = $3
 RETURNING failed_logins, locked_until
`

type RecordLoginFailureParams struct {
	Threshold int32
	Lockout   pgtype.Interval
	ID        pgtype.UUID
}

type RecordLoginFailureRow struct {
	FailedLogins int32
	LockedUntil  pgtype.Timestamptz
}

// Lockout is computed in SQL so concurrent attempts cannot race past the
// threshold by each reading a stale counter.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.Threshold, arg.Lockout, arg.ID)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedLogins, &i.LockedUntil)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE app_user
   SET failed_logins = 0, locked_until = NULL, last_login_at = now()
 WHERE id = $1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, id)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE user_session SET revoked_at = now()
 WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :execrows
UPDATE refresh_token SET revoked_at = now()
 WHERE family_id = $1 AND revoked_at IS NULL
`

// Reuse detection: a replayed token revokes the entire family, because we
// cannot tell whether the attacker or the legitimate client holds the newer one.
func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_session SET revoked_at = now()
 WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionsForFamily = `-- name: RevokeSessionsForFamily :execrows
UPDATE user_session SET revoked_at = now()
 WHERE id IN (SELECT session_id FROM refresh_token WHERE family_id = $1)
   AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForFamily(ctx context.Context, familyID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE user_session SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE app_user SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
