// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const putEligibilityResultBatch = `-- name: PutEligibilityResultBatch :batchexec
INSERT INTO eligibility_result (
    user_id, opportunity_id, profile_version, opportunity_version,
    eligible, failed_checks
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (user_id, opportunity_id, profile_version, opportunity_version)
DO UPDATE SET eligible = excluded.eligible,
              failed_checks = excluded.failed_checks,
              evaluated_at = now()
`

type PutEligibilityResultBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type PutEligibilityResultBatchParams struct {
	UserID             pgtype.UUID
	OpportunityID      pgtype.UUID
	ProfileVersion     int32
	OpportunityVersion int32
	Eligible           bool
	FailedChecks       []string
}

// The same batching for the eligibility audit trail.
func (q *Queries) PutEligibilityResultBatch(ctx context.Context, arg []PutEligibilityResultBatchParams) *PutEligibilityResultBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.OpportunityID,
			a.ProfileVersion,
			a.OpportunityVersion,
			a.Eligible,
			a.FailedChecks,
		}
		batch.Queue(putEligibilityResultBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &PutEligibilityResultBatchBatchResults{br, len(arg), false}
}

func (b *PutEligibilityResultBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *PutEligibilityResultBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const putFitScoreBatch = `-- name: PutFitScoreBatch :batchexec
INSERT INTO fit_score (
    user_id, opportunity_id, weights_version, profile_version,
    opportunity_version, embedding_version, score, max_possible, factors
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9
)
ON CONFLICT (user_id, opportunity_id, weights_version, profile_version,
             opportunity_version, embedding_version)
DO UPDATE SET score = excluded.score,
              max_possible = excluded.max_possible,
              factors = excluded.factors,
              computed_at = now()
`

type PutFitScoreBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type PutFitScoreBatchParams struct {
	UserID             pgtype.UUID
	OpportunityID      pgtype.UUID
	WeightsVersion     string
	ProfileVersion     int32
	OpportunityVersion int32
	EmbeddingVersion   string
	Score              int16
	MaxPossible        int16
	Factors            []byte
}

// The batched form of PutFitScore.
//
// :batchexec makes sqlc emit a pgx.Batch, which pipelines every statement into
// ONE network round trip. The per-candidate version was an N+1 write: a feed
// request over 188 candidates issued 188 INSERTs, one round trip each, and the
// load test measured 842ms for a single request. Nothing about the SQL changes —
// only how many times we wait for the network.
func (q *Queries) PutFitScoreBatch(ctx context.Context, arg []PutFitScoreBatchParams) *PutFitScoreBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.OpportunityID,
			a.WeightsVersion,
			a.ProfileVersion,
			a.OpportunityVersion,
			a.EmbeddingVersion,
			a.Score,
			a.MaxPossible,
			a.Factors,
		}
		batch.Queue(putFitScoreBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &PutFitScoreBatchBatchResults{br, len(arg), false}
}

func (b *PutFitScoreBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *PutFitScoreBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
