// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDigestDay = `-- name: ClaimDigestDay :one
INSERT INTO digest_send (
    user_id, tenant_id, local_date,
    generation_started_at, generated_at,
    outcome, reason, item_count, opportunity_ids,
    weights_version, profile_version, min_band, sender
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (user_id, local_date) DO NOTHING
RETURNING id, user_id, tenant_id, local_date, generation_started_at, generated_at, sent_at, outcome, reason, item_count, opportunity_ids, weights_version, profile_version, min_band, sender, attempts
`

type ClaimDigestDayParams struct {
	UserID              pgtype.UUID
	TenantID            pgtype.UUID
	LocalDate           pgtype.Date
	GenerationStartedAt pgtype.Timestamptz
	GeneratedAt         pgtype.Timestamptz
	Outcome             string
	Reason              *string
	ItemCount           int32
	OpportunityIds      []pgtype.UUID
	WeightsVersion      *string
	ProfileVersion      *int32
	MinBand             *string
	Sender              string
}

// Claims the user's local day, or returns nothing if it is already claimed.
//
// The insert IS the lock. Two workers running the same day race here and
// exactly one wins, because the unique constraint decides rather than a
// read-then-write in application code.
func (q *Queries) ClaimDigestDay(ctx context.Context, arg ClaimDigestDayParams) (DigestSend, error) {
	row := q.db.QueryRow(ctx, claimDigestDay,
		arg.UserID,
		arg.TenantID,
		arg.LocalDate,
		arg.GenerationStartedAt,
		arg.GeneratedAt,
		arg.Outcome,
		arg.Reason,
		arg.ItemCount,
		arg.OpportunityIds,
		arg.WeightsVersion,
		arg.ProfileVersion,
		arg.MinBand,
		arg.Sender,
	)
	var i DigestSend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.LocalDate,
		&i.GenerationStartedAt,
		&i.GeneratedAt,
		&i.SentAt,
		&i.Outcome,
		&i.Reason,
		&i.ItemCount,
		&i.OpportunityIds,
		&i.WeightsVersion,
		&i.ProfileVersion,
		&i.MinBand,
		&i.Sender,
		&i.Attempts,
	)
	return i, err
}

const countDigestSendsInWindow = `-- name: CountDigestSendsInWindow :one
SELECT count(*) AS sends
  FROM digest_send
 WHERE user_id = $1
   AND outcome = 'sent'
   AND local_date > $2::date
`

type CountDigestSendsInWindowParams struct {
	UserID    pgtype.UUID
	SinceDate pgtype.Date
}

// The weekly cap. Counts DELIVERED digests only: a day we correctly stayed
// quiet did not spend the user's attention, so it must not spend their budget.
func (q *Queries) CountDigestSendsInWindow(ctx context.Context, arg CountDigestSendsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDigestSendsInWindow, arg.UserID, arg.SinceDate)
	var sends int64
	err := row.Scan(&sends)
	return sends, err
}

const deleteDigestSends = `-- name: DeleteDigestSends :execrows
DELETE FROM digest_send WHERE user_id = $1
`

func (q *Queries) DeleteDigestSends(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDigestSends, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationSetting = `-- name: DeleteNotificationSetting :execrows
DELETE FROM notification_setting WHERE user_id = $1
`

func (q *Queries) DeleteNotificationSetting(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationSetting, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const digestCandidateUsers = `-- name: DigestCandidateUsers :many
SELECT n.user_id, n.tenant_id, n.timezone, n.quiet_start, n.quiet_end,
       n.max_per_week, n.min_band, n.send_when_empty,
       p.profile_version
  FROM notification_setting n
  JOIN profile p   ON p.user_id = n.user_id
  JOIN app_user u  ON u.id      = n.user_id
 WHERE n.digest_enabled
   AND n.digest_consent_at IS NOT NULL
   AND n.digest_consent_withdrawn_at IS NULL
   -- A suspended or deleted account is not a recipient.
   AND u.status = 'active'
   -- Unverified addresses are never mailed: sending to one is how a domain's
   -- reputation is lost, and it may not even be the user's address.
   AND u.email_verified_at IS NOT NULL
 ORDER BY n.user_id
`

type DigestCandidateUsersRow struct {
	UserID         pgtype.UUID
	TenantID       pgtype.UUID
	Timezone       string
	QuietStart     int16
	QuietEnd       int16
	MaxPerWeek     int16
	MinBand        string
	SendWhenEmpty  bool
	ProfileVersion int32
}

// Everyone a digest run should consider.
//
// The consent and enabled predicates are HERE rather than in the loop, so a
// caller cannot forget them. A profile is required by join: the digest is a
// ranking, and there is nothing to rank for a user who has not told us anything.
func (q *Queries) DigestCandidateUsers(ctx context.Context) ([]DigestCandidateUsersRow, error) {
	rows, err := q.db.Query(ctx, digestCandidateUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DigestCandidateUsersRow
	for rows.Next() {
		var i DigestCandidateUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.TenantID,
			&i.Timezone,
			&i.QuietStart,
			&i.QuietEnd,
			&i.MaxPerWeek,
			&i.MinBand,
			&i.SendWhenEmpty,
			&i.ProfileVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDigestDay = `-- name: GetDigestDay :one
SELECT id, user_id, tenant_id, local_date, generation_started_at, generated_at, sent_at, outcome, reason, item_count, opportunity_ids, weights_version, profile_version, min_band, sender, attempts FROM digest_send WHERE user_id = $1 AND local_date = $2
`

type GetDigestDayParams struct {
	UserID    pgtype.UUID
	LocalDate pgtype.Date
}

// Today's row for this user, if a run already reached a decision.
//
// Read before composing, so a day that is already SENT costs one indexed lookup
// instead of a full retrieval and scoring pass. The unique constraint is still
// what guarantees correctness under a race; this is the cheap path, not the
// guarantee.
func (q *Queries) GetDigestDay(ctx context.Context, arg GetDigestDayParams) (DigestSend, error) {
	row := q.db.QueryRow(ctx, getDigestDay, arg.UserID, arg.LocalDate)
	var i DigestSend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.LocalDate,
		&i.GenerationStartedAt,
		&i.GeneratedAt,
		&i.SentAt,
		&i.Outcome,
		&i.Reason,
		&i.ItemCount,
		&i.OpportunityIds,
		&i.WeightsVersion,
		&i.ProfileVersion,
		&i.MinBand,
		&i.Sender,
		&i.Attempts,
	)
	return i, err
}

const getNotificationSetting = `-- name: GetNotificationSetting :one
SELECT user_id, tenant_id, timezone, quiet_start, quiet_end, digest_enabled, max_per_week, min_band, send_when_empty, digest_consent_at, digest_consent_wording_version, digest_consent_ip, digest_consent_withdrawn_at, version, created_at, updated_at FROM notification_setting WHERE user_id = $1
`

func (q *Queries) GetNotificationSetting(ctx context.Context, userID pgtype.UUID) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSetting, userID)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Timezone,
		&i.QuietStart,
		&i.QuietEnd,
		&i.DigestEnabled,
		&i.MaxPerWeek,
		&i.MinBand,
		&i.SendWhenEmpty,
		&i.DigestConsentAt,
		&i.DigestConsentWordingVersion,
		&i.DigestConsentIp,
		&i.DigestConsentWithdrawnAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDigestFailed = `-- name: MarkDigestFailed :execrows
UPDATE digest_send
   SET outcome = 'failed', reason = $1
 WHERE id = $2
`

type MarkDigestFailedParams struct {
	Reason *string
	ID     pgtype.UUID
}

func (q *Queries) MarkDigestFailed(ctx context.Context, arg MarkDigestFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDigestFailed, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDigestSent = `-- name: MarkDigestSent :execrows
UPDATE digest_send
   SET sent_at = $1, outcome = 'sent'
 WHERE id = $2
`

type MarkDigestSentParams struct {
	SentAt pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) MarkDigestSent(ctx context.Context, arg MarkDigestSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDigestSent, arg.SentAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recentDigestOpportunityIDs = `-- name: RecentDigestOpportunityIDs :many
SELECT DISTINCT unnest(opportunity_ids)::uuid AS opportunity_id
  FROM digest_send
 WHERE user_id = $1
   AND local_date > $2::date
`

type RecentDigestOpportunityIDsParams struct {
	UserID    pgtype.UUID
	SinceDate pgtype.Date
}

// What we have already shown this user by email, so today's digest does not
// repeat it. A retention channel that resends yesterday's list is worse than
// silence.
func (q *Queries) RecentDigestOpportunityIDs(ctx context.Context, arg RecentDigestOpportunityIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, recentDigestOpportunityIDs, arg.UserID, arg.SinceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var opportunity_id pgtype.UUID
		if err := rows.Scan(&opportunity_id); err != nil {
			return nil, err
		}
		items = append(items, opportunity_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDigestConsent = `-- name: RecordDigestConsent :execrows
UPDATE notification_setting
   SET digest_consent_at              = $1,
       digest_consent_wording_version = $2,
       digest_consent_ip              = $3,
       digest_consent_withdrawn_at    = NULL,
       digest_enabled                 = true,
       version                        = version + 1,
       updated_at                     = now()
 WHERE user_id = $4
`

type RecordDigestConsentParams struct {
	ConsentedAt    pgtype.Timestamptz
	WordingVersion *string
	Ip             *netip.Addr
	UserID         pgtype.UUID
}

// Evidenced consent: when, what wording, from where. Clearing withdrawn_at is
// how a re-subscribe works, and it is explicit rather than implied.
func (q *Queries) RecordDigestConsent(ctx context.Context, arg RecordDigestConsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordDigestConsent,
		arg.ConsentedAt,
		arg.WordingVersion,
		arg.Ip,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sLIDigestGeneration = `-- name: SLIDigestGeneration :one
WITH latest AS (
    SELECT max(local_date) AS d FROM digest_send
     WHERE outcome IN ('sent', 'empty')
)
SELECT
    count(*)::bigint AS users,
    coalesce(max(generated_at) - min(generation_started_at),
             interval '0')::interval AS spread
  FROM digest_send, latest
 WHERE local_date = latest.d
   AND outcome IN ('sent', 'empty')
`

type SLIDigestGenerationRow struct {
	Users  int64
	Spread pgtype.Interval
}

// Blueprint §28: the full user base inside a 30-minute window.
//
// Measures the SPREAD of the most recent run, not any single user's duration:
// the objective is that everybody's digest is ready in time, so the number that
// matters is first-start to last-finish. Scoped to the latest local_date that
// produced anything, because averaging across days hides a bad one.
func (q *Queries) SLIDigestGeneration(ctx context.Context) (SLIDigestGenerationRow, error) {
	row := q.db.QueryRow(ctx, sLIDigestGeneration)
	var i SLIDigestGenerationRow
	err := row.Scan(&i.Users, &i.Spread)
	return i, err
}

const upgradeDigestDay = `-- name: UpgradeDigestDay :one
UPDATE digest_send
   SET outcome         = $1,
       reason          = $2,
       item_count      = $3,
       opportunity_ids = $4,
       weights_version = $5,
       generated_at    = $6,
       attempts        = attempts + 1
 WHERE user_id = $7
   AND local_date = $8
   AND outcome <> 'sent'
RETURNING id, user_id, tenant_id, local_date, generation_started_at, generated_at, sent_at, outcome, reason, item_count, opportunity_ids, weights_version, profile_version, min_band, sender, attempts
`

type UpgradeDigestDayParams struct {
	Outcome        string
	Reason         *string
	ItemCount      int32
	OpportunityIds []pgtype.UUID
	WeightsVersion *string
	GeneratedAt    pgtype.Timestamptz
	UserID         pgtype.UUID
	LocalDate      pgtype.Date
}

// Turns a provisional day into a real one.
//
// An 'empty' or 'suppressed_cap' row records what was true when it was written,
// not a promise about the rest of the day. Guarded on outcome <> 'sent' so a
// delivered digest can never be overwritten or double-counted — that guard is
// the daily cap, and it lives in the WHERE clause rather than in a caller's
// memory.
func (q *Queries) UpgradeDigestDay(ctx context.Context, arg UpgradeDigestDayParams) (DigestSend, error) {
	row := q.db.QueryRow(ctx, upgradeDigestDay,
		arg.Outcome,
		arg.Reason,
		arg.ItemCount,
		arg.OpportunityIds,
		arg.WeightsVersion,
		arg.GeneratedAt,
		arg.UserID,
		arg.LocalDate,
	)
	var i DigestSend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.LocalDate,
		&i.GenerationStartedAt,
		&i.GeneratedAt,
		&i.SentAt,
		&i.Outcome,
		&i.Reason,
		&i.ItemCount,
		&i.OpportunityIds,
		&i.WeightsVersion,
		&i.ProfileVersion,
		&i.MinBand,
		&i.Sender,
		&i.Attempts,
	)
	return i, err
}

const upsertNotificationSetting = `-- name: UpsertNotificationSetting :one
INSERT INTO notification_setting (
    user_id, tenant_id, timezone, quiet_start, quiet_end,
    digest_enabled, max_per_week, min_band, send_when_empty
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE SET
    timezone        = excluded.timezone,
    quiet_start     = excluded.quiet_start,
    quiet_end       = excluded.quiet_end,
    digest_enabled  = excluded.digest_enabled,
    max_per_week    = excluded.max_per_week,
    min_band        = excluded.min_band,
    send_when_empty = excluded.send_when_empty,
    version         = notification_setting.version + 1,
    updated_at      = now()
RETURNING user_id, tenant_id, timezone, quiet_start, quiet_end, digest_enabled, max_per_week, min_band, send_when_empty, digest_consent_at, digest_consent_wording_version, digest_consent_ip, digest_consent_withdrawn_at, version, created_at, updated_at
`

type UpsertNotificationSettingParams struct {
	UserID        pgtype.UUID
	TenantID      pgtype.UUID
	Timezone      string
	QuietStart    int16
	QuietEnd      int16
	DigestEnabled bool
	MaxPerWeek    int16
	MinBand       string
	SendWhenEmpty bool
}

// version bumps on every write so a concurrent editor is detectable. Consent
// columns are deliberately NOT touched here: consent is recorded by its own
// statement with its own evidence, and folding it into a settings save is how
// an unrelated preference change ends up looking like a consent event.
func (q *Queries) UpsertNotificationSetting(ctx context.Context, arg UpsertNotificationSettingParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertNotificationSetting,
		arg.UserID,
		arg.TenantID,
		arg.Timezone,
		arg.QuietStart,
		arg.QuietEnd,
		arg.DigestEnabled,
		arg.MaxPerWeek,
		arg.MinBand,
		arg.SendWhenEmpty,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Timezone,
		&i.QuietStart,
		&i.QuietEnd,
		&i.DigestEnabled,
		&i.MaxPerWeek,
		&i.MinBand,
		&i.SendWhenEmpty,
		&i.DigestConsentAt,
		&i.DigestConsentWordingVersion,
		&i.DigestConsentIp,
		&i.DigestConsentWithdrawnAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawDigestConsent = `-- name: WithdrawDigestConsent :execrows
UPDATE notification_setting
   SET digest_consent_withdrawn_at = $1,
       digest_enabled              = false,
       version                     = version + 1,
       updated_at                  = now()
 WHERE user_id = $2 AND digest_consent_withdrawn_at IS NULL
`

type WithdrawDigestConsentParams struct {
	WithdrawnAt pgtype.Timestamptz
	UserID      pgtype.UUID
}

// The consent record is kept, not erased: proving we HAD consent and that it was
// withdrawn on a date is the point of recording it. digest_enabled goes false in
// the same statement so a withdrawal cannot half-apply.
func (q *Queries) WithdrawDigestConsent(ctx context.Context, arg WithdrawDigestConsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, withdrawDigestConsent, arg.WithdrawnAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
