// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embedding.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const advanceAfterEmbedding = `-- name: AdvanceAfterEmbedding :execrows
UPDATE opportunity
   SET pipeline_state = $1,
       version = version + 1,
       next_attempt_at = now(), attempts = 0, last_error = NULL, lease_until = NULL
 WHERE id = $2
   AND version = $3
   AND pipeline_state = $4
`

type AdvanceAfterEmbeddingParams struct {
	NextState    string
	ID           pgtype.UUID
	Version      int32
	CurrentState string
}

func (q *Queries) AdvanceAfterEmbedding(ctx context.Context, arg AdvanceAfterEmbeddingParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceAfterEmbedding,
		arg.NextState,
		arg.ID,
		arg.Version,
		arg.CurrentState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEmbeddingsByVersion = `-- name: CountEmbeddingsByVersion :many
SELECT embedding_version, embedding_model, count(*)::bigint AS total
  FROM opportunity_embedding
 GROUP BY 1,2 ORDER BY 1
`

type CountEmbeddingsByVersionRow struct {
	EmbeddingVersion string
	EmbeddingModel   string
	Total            int64
}

// Migration visibility: during a dual-write both versions must be watchable, or
// there is no way to know when the backfill is done.
func (q *Queries) CountEmbeddingsByVersion(ctx context.Context) ([]CountEmbeddingsByVersionRow, error) {
	rows, err := q.db.Query(ctx, countEmbeddingsByVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEmbeddingsByVersionRow
	for rows.Next() {
		var i CountEmbeddingsByVersionRow
		if err := rows.Scan(&i.EmbeddingVersion, &i.EmbeddingModel, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEmbeddingVersion = `-- name: DeleteEmbeddingVersion :execrows
DELETE FROM opportunity_embedding WHERE embedding_version = $1
`

// The last step of a migration, run only once the new version is verified
// against the eval set. Dropping the old vectors before that is unrecoverable
// without re-embedding the whole corpus.
func (q *Queries) DeleteEmbeddingVersion(ctx context.Context, embeddingVersion string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmbeddingVersion, embeddingVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOpportunityEmbedding = `-- name: GetOpportunityEmbedding :one
SELECT opportunity_id, embedding_model, embedding_version, embedding_dim, embedding, created_at FROM opportunity_embedding
 WHERE opportunity_id = $1 AND embedding_version = $2
`

type GetOpportunityEmbeddingParams struct {
	OpportunityID    pgtype.UUID
	EmbeddingVersion string
}

func (q *Queries) GetOpportunityEmbedding(ctx context.Context, arg GetOpportunityEmbeddingParams) (OpportunityEmbedding, error) {
	row := q.db.QueryRow(ctx, getOpportunityEmbedding, arg.OpportunityID, arg.EmbeddingVersion)
	var i OpportunityEmbedding
	err := row.Scan(
		&i.OpportunityID,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
		&i.EmbeddingDim,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const getOpportunityTextForEmbedding = `-- name: GetOpportunityTextForEmbedding :one
SELECT id, version, title_raw, description_text FROM opportunity WHERE id = $1
`

type GetOpportunityTextForEmbeddingRow struct {
	ID              pgtype.UUID
	Version         int32
	TitleRaw        string
	DescriptionText *string
}

func (q *Queries) GetOpportunityTextForEmbedding(ctx context.Context, id pgtype.UUID) (GetOpportunityTextForEmbeddingRow, error) {
	row := q.db.QueryRow(ctx, getOpportunityTextForEmbedding, id)
	var i GetOpportunityTextForEmbeddingRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.TitleRaw,
		&i.DescriptionText,
	)
	return i, err
}

const nearestOpportunities = `-- name: NearestOpportunities :many
SELECT o.id, o.title_raw, o.role_family, o.seniority_ordinal,
       o.location_country, o.work_mode,
       (e.embedding <=> $1::vector) AS distance
  FROM opportunity_embedding e
  JOIN opportunity o ON o.id = e.opportunity_id
 WHERE e.embedding_version = $2
   AND o.pipeline_state = 'ready'
   AND o.closed_at IS NULL
   AND o.merged_into IS NULL
 ORDER BY e.embedding <=> $1::vector
 LIMIT $3::int
`

type NearestOpportunitiesParams struct {
	QueryVector      pgvector.Vector
	EmbeddingVersion string
	MaxCandidates    int32
}

type NearestOpportunitiesRow struct {
	ID               pgtype.UUID
	TitleRaw         string
	RoleFamily       *string
	SeniorityOrdinal *int16
	LocationCountry  *string
	WorkMode         *string
	Distance         interface{}
}

// Cosine distance against a query vector, restricted to one embedding version.
//
// The version filter is not optional: vectors from two models are not comparable,
// so an unfiltered search during a migration would silently mix them and every
// distance would be meaningless.
//
// CAVEAT: this is a filtered HNSW search. Postgres may scan the index and then
// apply the predicates, which can return FEWER than the limit even when more
// matches exist. Retrieval must therefore treat a short result as "the index ran
// out", not "there are no more candidates" — and coverage is measured against the
// eval set rather than assumed (blueprint §21).
func (q *Queries) NearestOpportunities(ctx context.Context, arg NearestOpportunitiesParams) ([]NearestOpportunitiesRow, error) {
	rows, err := q.db.Query(ctx, nearestOpportunities, arg.QueryVector, arg.EmbeddingVersion, arg.MaxCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NearestOpportunitiesRow
	for rows.Next() {
		var i NearestOpportunitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRaw,
			&i.RoleFamily,
			&i.SeniorityOrdinal,
			&i.LocationCountry,
			&i.WorkMode,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const opportunitiesMissingEmbedding = `-- name: OpportunitiesMissingEmbedding :many
SELECT o.id
  FROM opportunity o
 WHERE o.merged_into IS NULL
   AND o.closed_at IS NULL
   AND NOT EXISTS (
     SELECT 1 FROM opportunity_embedding e
      WHERE e.opportunity_id = o.id AND e.embedding_version = $1)
 LIMIT $2::int
`

type OpportunitiesMissingEmbeddingParams struct {
	EmbeddingVersion string
	Batch            int32
}

// Backfill driver: rows that have no vector for the current version. Used both
// for a model migration and to recover from an embedding outage.
func (q *Queries) OpportunitiesMissingEmbedding(ctx context.Context, arg OpportunitiesMissingEmbeddingParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, opportunitiesMissingEmbedding, arg.EmbeddingVersion, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putOpportunityEmbedding = `-- name: PutOpportunityEmbedding :exec
INSERT INTO opportunity_embedding (
    opportunity_id, embedding_model, embedding_version, embedding_dim, embedding
) VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (opportunity_id, embedding_version) DO UPDATE SET
    embedding       = EXCLUDED.embedding,
    embedding_model = EXCLUDED.embedding_model,
    embedding_dim   = EXCLUDED.embedding_dim,
    created_at      = now()
`

type PutOpportunityEmbeddingParams struct {
	OpportunityID    pgtype.UUID
	EmbeddingModel   string
	EmbeddingVersion string
	EmbeddingDim     int32
	Embedding        pgvector.Vector
}

// Keyed by (opportunity_id, embedding_version), which is what makes a model
// migration possible: both versions coexist while the new one backfills, then
// reads switch by version and the old rows are dropped (blueprint M-04).
func (q *Queries) PutOpportunityEmbedding(ctx context.Context, arg PutOpportunityEmbeddingParams) error {
	_, err := q.db.Exec(ctx, putOpportunityEmbedding,
		arg.OpportunityID,
		arg.EmbeddingModel,
		arg.EmbeddingVersion,
		arg.EmbeddingDim,
		arg.Embedding,
	)
	return err
}
