// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engagement.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDismissReasons = `-- name: CountDismissReasons :many
SELECT dismiss_reason, count(*)::int AS n
  FROM engagement_event
 WHERE event_type = 'dismissed' AND dismiss_reason IS NOT NULL
   AND ($1::uuid IS NULL
        OR engagement_event.user_id = $1::uuid)
 GROUP BY 1 ORDER BY 2 DESC
`

type CountDismissReasonsRow struct {
	DismissReason *string
	N             int32
}

// The most valuable feedback in the system: a dismissal reason is a correction to
// a specific factor, not a generic negative.
func (q *Queries) CountDismissReasons(ctx context.Context, userID pgtype.UUID) ([]CountDismissReasonsRow, error) {
	rows, err := q.db.Query(ctx, countDismissReasons, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDismissReasonsRow
	for rows.Next() {
		var i CountDismissReasonsRow
		if err := rows.Scan(&i.DismissReason, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countShownDays = `-- name: CountShownDays :many
SELECT opportunity_id, count(DISTINCT date_trunc('day', occurred_at))::int AS days_shown
  FROM engagement_event
 WHERE user_id = $1 AND event_type = 'shown'
 GROUP BY opportunity_id
`

type CountShownDaysRow struct {
	OpportunityID pgtype.UUID
	DaysShown     int32
}

// Distinct days each posting was shown to this user, for the saturation term in
// priority.
//
// Distinct DAYS, not raw impressions: a user who refreshes the feed twenty times
// has not ignored a role twenty times, and counting events would bury everything
// they looked at.
func (q *Queries) CountShownDays(ctx context.Context, userID pgtype.UUID) ([]CountShownDaysRow, error) {
	rows, err := q.db.Query(ctx, countShownDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountShownDaysRow
	for rows.Next() {
		var i CountShownDaysRow
		if err := rows.Scan(&i.OpportunityID, &i.DaysShown); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEngagementEvents = `-- name: DeleteEngagementEvents :execrows
DELETE FROM engagement_event WHERE user_id = $1
`

// Erasure. Enumerated so the report states a count for this store.
func (q *Queries) DeleteEngagementEvents(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEngagementEvents, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEngagementState = `-- name: GetEngagementState :many
SELECT e.opportunity_id,
       -- Casts are load-bearing: without them sqlc cannot infer these
       -- expressions' types and emits interface{}.
       coalesce(
         (array_agg(e.event_type ORDER BY e.occurred_at DESC)
            FILTER (WHERE e.event_type IN ('saved', 'unsaved')))[1] = 'saved',
         false)::boolean AS saved,
       bool_or(e.event_type = 'applied')   AS applied,
       bool_or(e.event_type = 'dismissed') AS dismissed,
       (max(e.occurred_at) FILTER (WHERE e.event_type = 'applied'))::timestamptz AS applied_at
  FROM engagement_event e
 WHERE e.user_id = $1
 GROUP BY e.opportunity_id
`

type GetEngagementStateRow struct {
	OpportunityID pgtype.UUID
	Saved         bool
	Applied       bool
	Dismissed     bool
	AppliedAt     pgtype.Timestamptz
}

// Current state per opportunity for one user, derived from the log.
//
// Derived rather than stored separately: a second table holding "is_saved" would
// be a cache of this, and a cache that can disagree with its source is how a user
// ends up seeing a role they dismissed.
//
// Saving is reversible, so its state is the LATEST of saved/unsaved. Applying and
// dismissing are not reversible in v1, so any such event stands.
func (q *Queries) GetEngagementState(ctx context.Context, userID pgtype.UUID) ([]GetEngagementStateRow, error) {
	rows, err := q.db.Query(ctx, getEngagementState, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEngagementStateRow
	for rows.Next() {
		var i GetEngagementStateRow
		if err := rows.Scan(
			&i.OpportunityID,
			&i.Saved,
			&i.Applied,
			&i.Dismissed,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagementLabels = `-- name: ListEngagementLabels :many
SELECT e.user_id, os.ats_type, os.ats_job_id, e.event_type, e.dismiss_reason,
       e.fit_score_at_event, e.weights_version, e.occurred_at
  FROM engagement_event e
  JOIN opportunity_source os ON os.opportunity_id = e.opportunity_id
 WHERE e.event_type IN ('saved','applied','dismissed')
   AND e.occurred_at >= $1
 ORDER BY e.occurred_at DESC
 LIMIT $2
`

type ListEngagementLabelsParams struct {
	Since    pgtype.Timestamptz
	PageSize int32
}

type ListEngagementLabelsRow struct {
	UserID          pgtype.UUID
	AtsType         *string
	AtsJobID        *string
	EventType       string
	DismissReason   *string
	FitScoreAtEvent *int16
	WeightsVersion  *string
	OccurredAt      pgtype.Timestamptz
}

// The behavioural evaluation set. Replaces the rubric labels in internal/eval
// once there is enough of it.
//
// Returns the ATS identity rather than the opportunity id, because a label keyed
// on a local UUID cannot travel between environments — the same reason the frozen
// eval fixtures use (ats_type, ats_job_id).
func (q *Queries) ListEngagementLabels(ctx context.Context, arg ListEngagementLabelsParams) ([]ListEngagementLabelsRow, error) {
	rows, err := q.db.Query(ctx, listEngagementLabels, arg.Since, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEngagementLabelsRow
	for rows.Next() {
		var i ListEngagementLabelsRow
		if err := rows.Scan(
			&i.UserID,
			&i.AtsType,
			&i.AtsJobID,
			&i.EventType,
			&i.DismissReason,
			&i.FitScoreAtEvent,
			&i.WeightsVersion,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedOpportunities = `-- name: ListSavedOpportunities :many
WITH latest AS (
    SELECT opportunity_id,
           (max(occurred_at) FILTER (WHERE event_type = 'saved'))::timestamptz   AS saved_at,
           (max(occurred_at) FILTER (WHERE event_type = 'unsaved'))::timestamptz AS unsaved_at
      FROM engagement_event
     WHERE user_id = $3 AND event_type IN ('saved','unsaved')
     GROUP BY opportunity_id
)
SELECT l.opportunity_id, l.saved_at
  FROM latest l
 WHERE l.saved_at IS NOT NULL
   AND (l.unsaved_at IS NULL OR l.unsaved_at < l.saved_at)
   AND ($1::timestamptz IS NULL OR l.saved_at < $1::timestamptz)
 ORDER BY l.saved_at DESC
 LIMIT $2
`

type ListSavedOpportunitiesParams struct {
	Before   pgtype.Timestamptz
	PageSize int32
	UserID   pgtype.UUID
}

type ListSavedOpportunitiesRow struct {
	OpportunityID pgtype.UUID
	SavedAt       pgtype.Timestamptz
}

// Saved postings, most recently saved first. Keyset-paginated on (occurred_at, id).
func (q *Queries) ListSavedOpportunities(ctx context.Context, arg ListSavedOpportunitiesParams) ([]ListSavedOpportunitiesRow, error) {
	rows, err := q.db.Query(ctx, listSavedOpportunities, arg.Before, arg.PageSize, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedOpportunitiesRow
	for rows.Next() {
		var i ListSavedOpportunitiesRow
		if err := rows.Scan(&i.OpportunityID, &i.SavedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEngagement = `-- name: RecordEngagement :one
INSERT INTO engagement_event (
    user_id, opportunity_id, event_type, dismiss_reason,
    fit_score_at_event, max_possible_at_event, factor_breakdown,
    weights_version, embedding_version, profile_version, opportunity_version
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11
)
RETURNING id, occurred_at
`

type RecordEngagementParams struct {
	UserID             pgtype.UUID
	OpportunityID      pgtype.UUID
	EventType          string
	DismissReason      *string
	FitScoreAtEvent    *int16
	MaxPossibleAtEvent *int16
	FactorBreakdown    []byte
	WeightsVersion     *string
	EmbeddingVersion   *string
	ProfileVersion     *int32
	OpportunityVersion *int32
}

type RecordEngagementRow struct {
	ID         int64
	OccurredAt pgtype.Timestamptz
}

// Append one event. Never an upsert: the log is the decision record and the
// reversal of an action is itself a label worth keeping.
func (q *Queries) RecordEngagement(ctx context.Context, arg RecordEngagementParams) (RecordEngagementRow, error) {
	row := q.db.QueryRow(ctx, recordEngagement,
		arg.UserID,
		arg.OpportunityID,
		arg.EventType,
		arg.DismissReason,
		arg.FitScoreAtEvent,
		arg.MaxPossibleAtEvent,
		arg.FactorBreakdown,
		arg.WeightsVersion,
		arg.EmbeddingVersion,
		arg.ProfileVersion,
		arg.OpportunityVersion,
	)
	var i RecordEngagementRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}
