// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extraction.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachExtractionToOpportunity = `-- name: AttachExtractionToOpportunity :execrows
UPDATE opportunity
   SET extraction_content_hash = $1,
       enriched_at = now(),
       extraction_error = NULL,
       version = version + 1,
       pipeline_state = $2,
       next_attempt_at = now(),
       attempts = 0,
       last_error = NULL,
       lease_until = NULL
 WHERE id = $3
   AND version = $4
   AND pipeline_state = $5
`

type AttachExtractionToOpportunityParams struct {
	ContentHash  []byte
	NextState    string
	ID           pgtype.UUID
	Version      int32
	CurrentState string
}

func (q *Queries) AttachExtractionToOpportunity(ctx context.Context, arg AttachExtractionToOpportunityParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachExtractionToOpportunity,
		arg.ContentHash,
		arg.NextState,
		arg.ID,
		arg.Version,
		arg.CurrentState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extractionSpendReport = `-- name: ExtractionSpendReport :many
SELECT created_at::date AS day, model_id, lane,
       count(*)::int AS calls,
       sum(input_tokens)::bigint AS input_tokens,
       sum(output_tokens)::bigint AS output_tokens,
       sum(cache_read_tokens)::bigint AS cache_read_tokens
  FROM extraction
 GROUP BY 1,2,3
 ORDER BY 1 DESC, 2
`

type ExtractionSpendReportRow struct {
	Day             pgtype.Date
	ModelID         string
	Lane            string
	Calls           int32
	InputTokens     int64
	OutputTokens    int64
	CacheReadTokens int64
}

// What enrichment actually costs, by day and model. Spend on the only
// per-token component has to be observable rather than inferred.
func (q *Queries) ExtractionSpendReport(ctx context.Context) ([]ExtractionSpendReportRow, error) {
	rows, err := q.db.Query(ctx, extractionSpendReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtractionSpendReportRow
	for rows.Next() {
		var i ExtractionSpendReportRow
		if err := rows.Scan(
			&i.Day,
			&i.ModelID,
			&i.Lane,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExtraction = `-- name: GetExtraction :one
SELECT content_hash, prompt_version, model_id, schema_version, raw_output, normalized, input_tokens, output_tokens, cache_read_tokens, lane, created_at FROM extraction
 WHERE content_hash = $1 AND prompt_version = $2
   AND model_id = $3 AND schema_version = $4
`

type GetExtractionParams struct {
	ContentHash   []byte
	PromptVersion string
	ModelID       string
	SchemaVersion string
}

func (q *Queries) GetExtraction(ctx context.Context, arg GetExtractionParams) (Extraction, error) {
	row := q.db.QueryRow(ctx, getExtraction,
		arg.ContentHash,
		arg.PromptVersion,
		arg.ModelID,
		arg.SchemaVersion,
	)
	var i Extraction
	err := row.Scan(
		&i.ContentHash,
		&i.PromptVersion,
		&i.ModelID,
		&i.SchemaVersion,
		&i.RawOutput,
		&i.Normalized,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.Lane,
		&i.CreatedAt,
	)
	return i, err
}

const getOpportunityForEnrichment = `-- name: GetOpportunityForEnrichment :one
SELECT id, version, content_hash, description_text, title_raw
  FROM opportunity WHERE id = $1
`

type GetOpportunityForEnrichmentRow struct {
	ID              pgtype.UUID
	Version         int32
	ContentHash     []byte
	DescriptionText *string
	TitleRaw        string
}

func (q *Queries) GetOpportunityForEnrichment(ctx context.Context, id pgtype.UUID) (GetOpportunityForEnrichmentRow, error) {
	row := q.db.QueryRow(ctx, getOpportunityForEnrichment, id)
	var i GetOpportunityForEnrichmentRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ContentHash,
		&i.DescriptionText,
		&i.TitleRaw,
	)
	return i, err
}

const insertOpportunitySkill = `-- name: InsertOpportunitySkill :exec
INSERT INTO opportunity_skill (
    opportunity_id, skill_id, requirement_level, extraction_confidence,
    ontology_version, model_id, prompt_version
) VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (opportunity_id, skill_id, requirement_level) DO NOTHING
`

type InsertOpportunitySkillParams struct {
	OpportunityID        pgtype.UUID
	SkillID              pgtype.UUID
	RequirementLevel     string
	ExtractionConfidence *float32
	OntologyVersion      string
	ModelID              *string
	PromptVersion        *string
}

func (q *Queries) InsertOpportunitySkill(ctx context.Context, arg InsertOpportunitySkillParams) error {
	_, err := q.db.Exec(ctx, insertOpportunitySkill,
		arg.OpportunityID,
		arg.SkillID,
		arg.RequirementLevel,
		arg.ExtractionConfidence,
		arg.OntologyVersion,
		arg.ModelID,
		arg.PromptVersion,
	)
	return err
}

const linkSkillAlias = `-- name: LinkSkillAlias :exec
INSERT INTO skill_alias (skill_id, alias) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkSkillAliasParams struct {
	SkillID pgtype.UUID
	Alias   string
}

func (q *Queries) LinkSkillAlias(ctx context.Context, arg LinkSkillAliasParams) error {
	_, err := q.db.Exec(ctx, linkSkillAlias, arg.SkillID, arg.Alias)
	return err
}

const putExtraction = `-- name: PutExtraction :exec
INSERT INTO extraction (
    content_hash, prompt_version, model_id, schema_version,
    raw_output, normalized, input_tokens, output_tokens, cache_read_tokens, lane
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (content_hash, prompt_version, model_id, schema_version) DO NOTHING
`

type PutExtractionParams struct {
	ContentHash     []byte
	PromptVersion   string
	ModelID         string
	SchemaVersion   string
	RawOutput       []byte
	Normalized      []byte
	InputTokens     int32
	OutputTokens    int32
	CacheReadTokens int32
	Lane            string
}

// Idempotent on the cache key. Two workers racing on the same posting must not
// both pay, and the second write must not fail the record.
func (q *Queries) PutExtraction(ctx context.Context, arg PutExtractionParams) error {
	_, err := q.db.Exec(ctx, putExtraction,
		arg.ContentHash,
		arg.PromptVersion,
		arg.ModelID,
		arg.SchemaVersion,
		arg.RawOutput,
		arg.Normalized,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.Lane,
	)
	return err
}

const recordExtractionFailure = `-- name: RecordExtractionFailure :exec
UPDATE opportunity SET extraction_error = $2 WHERE id = $1
`

type RecordExtractionFailureParams struct {
	ID              pgtype.UUID
	ExtractionError *string
}

// Per-opportunity, so one unparseable posting does not look like a broken model.
func (q *Queries) RecordExtractionFailure(ctx context.Context, arg RecordExtractionFailureParams) error {
	_, err := q.db.Exec(ctx, recordExtractionFailure, arg.ID, arg.ExtractionError)
	return err
}

const replaceOpportunitySkills = `-- name: ReplaceOpportunitySkills :exec
DELETE FROM opportunity_skill WHERE opportunity_id = $1
`

func (q *Queries) ReplaceOpportunitySkills(ctx context.Context, opportunityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceOpportunitySkills, opportunityID)
	return err
}

const upsertSkillByAlias = `-- name: UpsertSkillByAlias :one
WITH existing AS (
    SELECT s.id FROM skill_alias a JOIN skill s ON s.id = a.skill_id
     WHERE a.alias = $1::citext
     LIMIT 1
), created AS (
    INSERT INTO skill (canonical_slug, display_name, ontology_version)
    SELECT $2::citext, $3, $4
     WHERE NOT EXISTS (SELECT 1 FROM existing)
    ON CONFLICT (canonical_slug) DO NOTHING
    RETURNING id
)
SELECT id FROM existing
UNION ALL SELECT id FROM created
UNION ALL SELECT s.id FROM skill s WHERE s.canonical_slug = $2::citext
LIMIT 1
`

type UpsertSkillByAliasParams struct {
	Alias           string
	Slug            string
	DisplayName     string
	OntologyVersion string
}

// Resolves an extracted name against our own ontology. The model is never asked
// to guess our slugs; it names the technology as the posting wrote it and the
// mapping happens here, where it is versioned and reviewable.
func (q *Queries) UpsertSkillByAlias(ctx context.Context, arg UpsertSkillByAliasParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSkillByAlias,
		arg.Alias,
		arg.Slug,
		arg.DisplayName,
		arg.OntologyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
