// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const companyMedianDaysToClose = `-- name: CompanyMedianDaysToClose :one
SELECT coalesce(
    percentile_cont(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (closed_at - first_seen_at)) / 86400.0
    ), 0)::int AS median_days
  FROM opportunity
 WHERE company_id = $1 AND closed_at IS NOT NULL AND merged_into IS NULL
`

// The company's own hiring pace, used as the baseline for ghost risk. Relative
// beats absolute: a 90-day posting is unremarkable at a company that always
// takes 90 days. Returns 0 when there is not enough history, and an unknown
// baseline must never manufacture suspicion.
func (q *Queries) CompanyMedianDaysToClose(ctx context.Context, companyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, companyMedianDaysToClose, companyID)
	var median_days int32
	err := row.Scan(&median_days)
	return median_days, err
}

const countOpenSimilarRoles = `-- name: CountOpenSimilarRoles :one
SELECT count(*) FROM opportunity
 WHERE company_id = $1 AND role_family = $2
   AND closed_at IS NULL AND merged_into IS NULL AND pipeline_state = 'ready'
`

type CountOpenSimilarRolesParams struct {
	CompanyID  pgtype.UUID
	RoleFamily *string
}

// Observable competition proxy. NOT an applicant count — we have none, and
// inventing one would discredit every honest field beside it (blueprint §3).
func (q *Queries) CountOpenSimilarRoles(ctx context.Context, arg CountOpenSimilarRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenSimilarRoles, arg.CompanyID, arg.RoleFamily)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOpportunityDetail = `-- name: GetOpportunityDetail :one
SELECT o.id, o.company_id, o.title_raw, o.description_text, o.role_family, o.seniority_ordinal,
       o.is_management, o.work_mode, o.location_country, o.location_city,
       o.remote_geo_scope, o.language, o.apply_method,
       o.salary_min_minor, o.salary_max_minor, o.salary_currency,
       o.salary_period, o.salary_is_estimated, o.visa_sponsorship,
       o.first_seen_at, o.last_seen_at, o.liveness_checked_at,
       o.source_reported_posted_at, o.repost_count, o.closed_at, o.close_reason,
       c.display_name AS company_name, c.canonical_domain, c.domain_confirmed,
       (SELECT s.apply_url FROM opportunity_source s
         WHERE s.opportunity_id = o.id AND s.apply_url IS NOT NULL LIMIT 1) AS apply_url,
       (SELECT count(*) FROM opportunity_source s WHERE s.opportunity_id = o.id) AS source_count
  FROM opportunity o
  JOIN company c ON c.id = o.company_id
 WHERE o.id = $1 AND o.merged_into IS NULL
`

type GetOpportunityDetailRow struct {
	ID                     pgtype.UUID
	CompanyID              pgtype.UUID
	TitleRaw               string
	DescriptionText        *string
	RoleFamily             *string
	SeniorityOrdinal       *int16
	IsManagement           bool
	WorkMode               *string
	LocationCountry        *string
	LocationCity           *string
	RemoteGeoScope         *string
	Language               *string
	ApplyMethod            *string
	SalaryMinMinor         *int64
	SalaryMaxMinor         *int64
	SalaryCurrency         *string
	SalaryPeriod           *string
	SalaryIsEstimated      bool
	VisaSponsorship        string
	FirstSeenAt            pgtype.Timestamptz
	LastSeenAt             pgtype.Timestamptz
	LivenessCheckedAt      pgtype.Timestamptz
	SourceReportedPostedAt pgtype.Timestamptz
	RepostCount            int32
	ClosedAt               pgtype.Timestamptz
	CloseReason            *string
	CompanyName            string
	CanonicalDomain        string
	DomainConfirmed        bool
	ApplyUrl               *string
	SourceCount            int64
}

func (q *Queries) GetOpportunityDetail(ctx context.Context, id pgtype.UUID) (GetOpportunityDetailRow, error) {
	row := q.db.QueryRow(ctx, getOpportunityDetail, id)
	var i GetOpportunityDetailRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TitleRaw,
		&i.DescriptionText,
		&i.RoleFamily,
		&i.SeniorityOrdinal,
		&i.IsManagement,
		&i.WorkMode,
		&i.LocationCountry,
		&i.LocationCity,
		&i.RemoteGeoScope,
		&i.Language,
		&i.ApplyMethod,
		&i.SalaryMinMinor,
		&i.SalaryMaxMinor,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryIsEstimated,
		&i.VisaSponsorship,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LivenessCheckedAt,
		&i.SourceReportedPostedAt,
		&i.RepostCount,
		&i.ClosedAt,
		&i.CloseReason,
		&i.CompanyName,
		&i.CanonicalDomain,
		&i.DomainConfirmed,
		&i.ApplyUrl,
		&i.SourceCount,
	)
	return i, err
}

const listOpportunities = `-- name: ListOpportunities :many
SELECT o.id, o.title_raw, o.role_family, o.seniority_ordinal, o.is_management,
       o.work_mode, o.location_country, o.location_city, o.remote_geo_scope,
       o.language, o.apply_method,
       o.salary_min_minor, o.salary_max_minor, o.salary_currency,
       o.salary_period, o.salary_is_estimated,
       o.visa_sponsorship,
       o.first_seen_at, o.last_seen_at, o.liveness_checked_at,
       o.source_reported_posted_at, o.repost_count,
       c.display_name AS company_name, c.canonical_domain, c.domain_confirmed,
       (SELECT s.apply_url FROM opportunity_source s
         WHERE s.opportunity_id = o.id AND s.apply_url IS NOT NULL LIMIT 1) AS apply_url,
       (SELECT count(*) FROM opportunity_source s WHERE s.opportunity_id = o.id) AS source_count
  FROM opportunity o
  JOIN company c ON c.id = o.company_id
 WHERE o.pipeline_state = 'ready'
   -- Serving excludes anything closed or merged away. A closed posting must
   -- never appear, and a merged one is represented by its canonical row.
   AND o.closed_at IS NULL
   AND o.merged_into IS NULL
   AND ($1::text IS NULL OR o.role_family = $1::text)
   AND ($2::text IS NULL OR o.work_mode = $2::text)
   AND ($3::text IS NULL
        OR o.location_country = $3::text
        OR o.remote_geo_scope LIKE '%' || $3::text || '%')
   AND ($4::timestamptz IS NULL
        OR (o.first_seen_at, o.id) < ($4::timestamptz, $5::uuid))
 ORDER BY o.first_seen_at DESC, o.id DESC
 LIMIT $6::int
`

type ListOpportunitiesParams struct {
	RoleFamily *string
	WorkMode   *string
	Country    *string
	AfterSeen  pgtype.Timestamptz
	AfterID    pgtype.UUID
	PageSize   int32
}

type ListOpportunitiesRow struct {
	ID                     pgtype.UUID
	TitleRaw               string
	RoleFamily             *string
	SeniorityOrdinal       *int16
	IsManagement           bool
	WorkMode               *string
	LocationCountry        *string
	LocationCity           *string
	RemoteGeoScope         *string
	Language               *string
	ApplyMethod            *string
	SalaryMinMinor         *int64
	SalaryMaxMinor         *int64
	SalaryCurrency         *string
	SalaryPeriod           *string
	SalaryIsEstimated      bool
	VisaSponsorship        string
	FirstSeenAt            pgtype.Timestamptz
	LastSeenAt             pgtype.Timestamptz
	LivenessCheckedAt      pgtype.Timestamptz
	SourceReportedPostedAt pgtype.Timestamptz
	RepostCount            int32
	CompanyName            string
	CanonicalDomain        string
	DomainConfirmed        bool
	ApplyUrl               *string
	SourceCount            int64
}

// Keyset pagination, never OFFSET: ingestion never stops, so an offset skips or
// duplicates rows between pages as data shifts underneath. (first_seen_at, id)
// is the sort key, with id as the tiebreaker so the order is total.
func (q *Queries) ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]ListOpportunitiesRow, error) {
	rows, err := q.db.Query(ctx, listOpportunities,
		arg.RoleFamily,
		arg.WorkMode,
		arg.Country,
		arg.AfterSeen,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpportunitiesRow
	for rows.Next() {
		var i ListOpportunitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRaw,
			&i.RoleFamily,
			&i.SeniorityOrdinal,
			&i.IsManagement,
			&i.WorkMode,
			&i.LocationCountry,
			&i.LocationCity,
			&i.RemoteGeoScope,
			&i.Language,
			&i.ApplyMethod,
			&i.SalaryMinMinor,
			&i.SalaryMaxMinor,
			&i.SalaryCurrency,
			&i.SalaryPeriod,
			&i.SalaryIsEstimated,
			&i.VisaSponsorship,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LivenessCheckedAt,
			&i.SourceReportedPostedAt,
			&i.RepostCount,
			&i.CompanyName,
			&i.CanonicalDomain,
			&i.DomainConfirmed,
			&i.ApplyUrl,
			&i.SourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
