// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const baselineSourceHealth = `-- name: BaselineSourceHealth :one
SELECT coalesce(sum(postings_seen), 0)::int   AS postings_seen,
       coalesce(sum(postings_usable), 0)::int AS postings_usable,
       coalesce(sum(with_company), 0)::int    AS with_company,
       coalesce(sum(with_location), 0)::int   AS with_location,
       coalesce(sum(with_apply_url), 0)::int  AS with_apply_url,
       coalesce(sum(with_language), 0)::int   AS with_language,
       coalesce(sum(with_salary), 0)::int     AS with_salary
  FROM source_health_daily
 WHERE source_id = $1
   AND day <  CURRENT_DATE
   AND day >= CURRENT_DATE - $2::int
`

type BaselineSourceHealthParams struct {
	SourceID   pgtype.UUID
	WindowDays int32
}

type BaselineSourceHealthRow struct {
	PostingsSeen   int32
	PostingsUsable int32
	WithCompany    int32
	WithLocation   int32
	WithApplyUrl   int32
	WithLanguage   int32
	WithSalary     int32
}

// The source's OWN recent past, excluding today. Summed across the window rather
// than averaged per day: a quiet day would otherwise carry the same weight as a
// busy one and make the baseline swing.
func (q *Queries) BaselineSourceHealth(ctx context.Context, arg BaselineSourceHealthParams) (BaselineSourceHealthRow, error) {
	row := q.db.QueryRow(ctx, baselineSourceHealth, arg.SourceID, arg.WindowDays)
	var i BaselineSourceHealthRow
	err := row.Scan(
		&i.PostingsSeen,
		&i.PostingsUsable,
		&i.WithCompany,
		&i.WithLocation,
		&i.WithApplyUrl,
		&i.WithLanguage,
		&i.WithSalary,
	)
	return i, err
}

const clearSourceDegraded = `-- name: ClearSourceDegraded :exec
UPDATE source
   SET consecutive_degraded = 0, last_health_note = NULL
 WHERE id = $1 AND consecutive_degraded <> 0
`

func (q *Queries) ClearSourceDegraded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSourceDegraded, id)
	return err
}

const listActiveSourceIDs = `-- name: ListActiveSourceIDs :many
SELECT id, name FROM source WHERE status = 'active' ORDER BY name
`

type ListActiveSourceIDsRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListActiveSourceIDs(ctx context.Context) ([]ListActiveSourceIDsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSourceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSourceIDsRow
	for rows.Next() {
		var i ListActiveSourceIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarantineDegradedSource = `-- name: QuarantineDegradedSource :exec
UPDATE source
   SET status = 'quarantined', last_health_note = $1
 WHERE id = $2 AND status = 'active'
`

type QuarantineDegradedSourceParams struct {
	Note *string
	ID   pgtype.UUID
}

func (q *Queries) QuarantineDegradedSource(ctx context.Context, arg QuarantineDegradedSourceParams) error {
	_, err := q.db.Exec(ctx, quarantineDegradedSource, arg.Note, arg.ID)
	return err
}

const recordSourceHealth = `-- name: RecordSourceHealth :exec
INSERT INTO source_health_daily (
    source_id, day, polls, poll_failures, not_modified,
    postings_seen, postings_usable,
    with_company, with_location, with_apply_url, with_language, with_salary
) VALUES (
    $1, CURRENT_DATE, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
ON CONFLICT (source_id, day) DO UPDATE SET
    polls           = source_health_daily.polls + EXCLUDED.polls,
    poll_failures   = source_health_daily.poll_failures + EXCLUDED.poll_failures,
    not_modified    = source_health_daily.not_modified + EXCLUDED.not_modified,
    postings_seen   = source_health_daily.postings_seen + EXCLUDED.postings_seen,
    postings_usable = source_health_daily.postings_usable + EXCLUDED.postings_usable,
    with_company    = source_health_daily.with_company + EXCLUDED.with_company,
    with_location   = source_health_daily.with_location + EXCLUDED.with_location,
    with_apply_url  = source_health_daily.with_apply_url + EXCLUDED.with_apply_url,
    with_language   = source_health_daily.with_language + EXCLUDED.with_language,
    with_salary     = source_health_daily.with_salary + EXCLUDED.with_salary,
    updated_at      = now()
`

type RecordSourceHealthParams struct {
	SourceID       pgtype.UUID
	Polls          int32
	PollFailures   int32
	NotModified    int32
	PostingsSeen   int32
	PostingsUsable int32
	WithCompany    int32
	WithLocation   int32
	WithApplyUrl   int32
	WithLanguage   int32
	WithSalary     int32
}

// Accumulates within the day. Counters rather than snapshots, so a source polled
// every five minutes builds one comparable row per day.
func (q *Queries) RecordSourceHealth(ctx context.Context, arg RecordSourceHealthParams) error {
	_, err := q.db.Exec(ctx, recordSourceHealth,
		arg.SourceID,
		arg.Polls,
		arg.PollFailures,
		arg.NotModified,
		arg.PostingsSeen,
		arg.PostingsUsable,
		arg.WithCompany,
		arg.WithLocation,
		arg.WithApplyUrl,
		arg.WithLanguage,
		arg.WithSalary,
	)
	return err
}

const setSourceDegraded = `-- name: SetSourceDegraded :exec
UPDATE source
   SET consecutive_degraded = consecutive_degraded + 1,
       last_health_note = $1
 WHERE id = $2
`

type SetSourceDegradedParams struct {
	Note *string
	ID   pgtype.UUID
}

func (q *Queries) SetSourceDegraded(ctx context.Context, arg SetSourceDegradedParams) error {
	_, err := q.db.Exec(ctx, setSourceDegraded, arg.Note, arg.ID)
	return err
}

const setSourceReview = `-- name: SetSourceReview :exec
UPDATE source
   SET reviewed_by = $1,
       terms_reviewed_at = now(),
       platform_review_ref = $2
 WHERE id = $3
`

type SetSourceReviewParams struct {
	ReviewedBy        *string
	PlatformReviewRef *string
	ID                pgtype.UUID
}

// Records who reviewed the platform this source inherits its legal basis from.
func (q *Queries) SetSourceReview(ctx context.Context, arg SetSourceReviewParams) error {
	_, err := q.db.Exec(ctx, setSourceReview, arg.ReviewedBy, arg.PlatformReviewRef, arg.ID)
	return err
}

const sourceHealthReport = `-- name: SourceHealthReport :many
SELECT s.name, s.tier, s.status, s.consecutive_degraded, s.last_health_note,
       s.last_success_at, s.last_failure_at,
       coalesce(t.postings_seen, 0)::int   AS today_seen,
       coalesce(t.postings_usable, 0)::int AS today_usable,
       coalesce(t.with_location, 0)::int   AS today_with_location,
       coalesce(b.seen, 0)::int            AS baseline_seen,
       coalesce(b.usable, 0)::int          AS baseline_usable,
       coalesce(b.loc, 0)::int             AS baseline_with_location
  FROM source s
  LEFT JOIN source_health_daily t ON t.source_id = s.id AND t.day = CURRENT_DATE
  LEFT JOIN (
      SELECT source_id,
             sum(postings_seen) AS seen,
             sum(postings_usable) AS usable,
             sum(with_location) AS loc
        FROM source_health_daily
       WHERE day < CURRENT_DATE AND day >= CURRENT_DATE - 7
       GROUP BY source_id
  ) b ON b.source_id = s.id
 ORDER BY s.status, s.name
`

type SourceHealthReportRow struct {
	Name                 string
	Tier                 string
	Status               string
	ConsecutiveDegraded  int32
	LastHealthNote       *string
	LastSuccessAt        pgtype.Timestamptz
	LastFailureAt        pgtype.Timestamptz
	TodaySeen            int32
	TodayUsable          int32
	TodayWithLocation    int32
	BaselineSeen         int32
	BaselineUsable       int32
	BaselineWithLocation int32
}

// Operator view: one row per source with today against its baseline window.
func (q *Queries) SourceHealthReport(ctx context.Context) ([]SourceHealthReportRow, error) {
	rows, err := q.db.Query(ctx, sourceHealthReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceHealthReportRow
	for rows.Next() {
		var i SourceHealthReportRow
		if err := rows.Scan(
			&i.Name,
			&i.Tier,
			&i.Status,
			&i.ConsecutiveDegraded,
			&i.LastHealthNote,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.TodaySeen,
			&i.TodayUsable,
			&i.TodayWithLocation,
			&i.BaselineSeen,
			&i.BaselineUsable,
			&i.BaselineWithLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todaySourceHealth = `-- name: TodaySourceHealth :one
SELECT postings_seen, postings_usable, with_company, with_location,
       with_apply_url, with_language, with_salary
  FROM source_health_daily
 WHERE source_id = $1 AND day = CURRENT_DATE
`

type TodaySourceHealthRow struct {
	PostingsSeen   int32
	PostingsUsable int32
	WithCompany    int32
	WithLocation   int32
	WithApplyUrl   int32
	WithLanguage   int32
	WithSalary     int32
}

func (q *Queries) TodaySourceHealth(ctx context.Context, sourceID pgtype.UUID) (TodaySourceHealthRow, error) {
	row := q.db.QueryRow(ctx, todaySourceHealth, sourceID)
	var i TodaySourceHealthRow
	err := row.Scan(
		&i.PostingsSeen,
		&i.PostingsUsable,
		&i.WithCompany,
		&i.WithLocation,
		&i.WithApplyUrl,
		&i.WithLanguage,
		&i.WithSalary,
	)
	return i, err
}
