// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpMissesForAbsent = `-- name: BumpMissesForAbsent :execrows
UPDATE opportunity o
   SET consecutive_misses = o.consecutive_misses + 1,
       liveness_checked_at = now()
 WHERE o.closed_at IS NULL
   AND EXISTS (SELECT 1 FROM opportunity_source s
                WHERE s.opportunity_id = o.id AND s.source_id = $1)
   AND NOT EXISTS (SELECT 1 FROM opportunity_source s
                    WHERE s.opportunity_id = o.id
                      AND s.source_id = $1
                      AND s.source_job_id = ANY($2::text[]))
`

type BumpMissesForAbsentParams struct {
	SourceID pgtype.UUID
	SeenIds  []string
}

// Absence-based liveness. Called ONLY after a successful poll: inferring closure
// from a failed fetch would let one source outage delete the corpus.
func (q *Queries) BumpMissesForAbsent(ctx context.Context, arg BumpMissesForAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpMissesForAbsent, arg.SourceID, arg.SeenIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueSources = `-- name: ClaimDueSources :many
UPDATE source_schedule
   SET lease_until = now() + $1::interval
 WHERE source_id IN (
   SELECT ss.source_id FROM source_schedule ss
     JOIN source s ON s.id = ss.source_id
    WHERE ss.next_run_at <= now()
      AND (ss.lease_until IS NULL OR ss.lease_until < now())
      AND s.status = 'active'
    ORDER BY ss.next_run_at
    FOR UPDATE SKIP LOCKED
    LIMIT $2::int
 )
 RETURNING source_id, cursor
`

type ClaimDueSourcesParams struct {
	Lease pgtype.Interval
	Batch int32
}

type ClaimDueSourcesRow struct {
	SourceID pgtype.UUID
	Cursor   []byte
}

// Same SKIP LOCKED pattern as the pipeline: no scheduler process, so no single
// point of failure and no double-firing.
func (q *Queries) ClaimDueSources(ctx context.Context, arg ClaimDueSourcesParams) ([]ClaimDueSourcesRow, error) {
	rows, err := q.db.Query(ctx, claimDueSources, arg.Lease, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueSourcesRow
	for rows.Next() {
		var i ClaimDueSourcesRow
		if err := rows.Scan(&i.SourceID, &i.Cursor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeMissedOpportunities = `-- name: CloseMissedOpportunities :execrows
UPDATE opportunity
   SET closed_at = now(), close_reason = 'absent'
 WHERE closed_at IS NULL
   AND consecutive_misses >= $1::int
`

func (q *Queries) CloseMissedOpportunities(ctx context.Context, maxMisses int32) (int64, error) {
	result, err := q.db.Exec(ctx, closeMissedOpportunities, maxMisses)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveOpportunitiesForSource = `-- name: CountLiveOpportunitiesForSource :one
SELECT count(*) FROM opportunity o
 WHERE o.closed_at IS NULL
   AND EXISTS (SELECT 1 FROM opportunity_source s
                WHERE s.opportunity_id = o.id AND s.source_id = $1)
`

func (q *Queries) CountLiveOpportunitiesForSource(ctx context.Context, sourceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveOpportunitiesForSource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findCanonicalByATS = `-- name: FindCanonicalByATS :one
SELECT opportunity_id FROM opportunity_source
 WHERE ats_type = $1 AND ats_job_id = $2
 LIMIT 1
`

type FindCanonicalByATSParams struct {
	AtsType  *string
	AtsJobID *string
}

// For Tier-A sources this pair is a stable global identifier, which is what
// makes dedup nearly free: the same posting seen through another source links to
// the existing canonical row instead of creating a duplicate.
func (q *Queries) FindCanonicalByATS(ctx context.Context, arg FindCanonicalByATSParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findCanonicalByATS, arg.AtsType, arg.AtsJobID)
	var opportunity_id pgtype.UUID
	err := row.Scan(&opportunity_id)
	return opportunity_id, err
}

const findSourceRow = `-- name: FindSourceRow :one
SELECT id, opportunity_id, source_id, source_job_id, ats_type, ats_job_id, apply_url, raw_object_key, content_hash, simhash, first_seen_at, last_seen_at, etag, merge_reason, merge_confidence, merged_by, created_at FROM opportunity_source
 WHERE source_id = $1 AND source_job_id = $2
`

type FindSourceRowParams struct {
	SourceID    pgtype.UUID
	SourceJobID string
}

func (q *Queries) FindSourceRow(ctx context.Context, arg FindSourceRowParams) (OpportunitySource, error) {
	row := q.db.QueryRow(ctx, findSourceRow, arg.SourceID, arg.SourceJobID)
	var i OpportunitySource
	err := row.Scan(
		&i.ID,
		&i.OpportunityID,
		&i.SourceID,
		&i.SourceJobID,
		&i.AtsType,
		&i.AtsJobID,
		&i.ApplyUrl,
		&i.RawObjectKey,
		&i.ContentHash,
		&i.Simhash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Etag,
		&i.MergeReason,
		&i.MergeConfidence,
		&i.MergedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, name, tier, type, legal_basis, robots_checked_at, terms_reviewed_at, reviewed_by, rate_limit_rps, poll_interval, etag_supported, status, last_success_at, last_failure_at, last_error, items_discovered, items_processed, parse_yield_7d, created_at, updated_at FROM source WHERE id = $1
`

func (q *Queries) GetSourceByID(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.LegalBasis,
		&i.RobotsCheckedAt,
		&i.TermsReviewedAt,
		&i.ReviewedBy,
		&i.RateLimitRps,
		&i.PollInterval,
		&i.EtagSupported,
		&i.Status,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.ItemsDiscovered,
		&i.ItemsProcessed,
		&i.ParseYield7d,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, name, tier, type, legal_basis, robots_checked_at, terms_reviewed_at, reviewed_by, rate_limit_rps, poll_interval, etag_supported, status, last_success_at, last_failure_at, last_error, items_discovered, items_processed, parse_yield_7d, created_at, updated_at FROM source WHERE name = $1
`

func (q *Queries) GetSourceByName(ctx context.Context, name string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByName, name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.LegalBasis,
		&i.RobotsCheckedAt,
		&i.TermsReviewedAt,
		&i.ReviewedBy,
		&i.RateLimitRps,
		&i.PollInterval,
		&i.EtagSupported,
		&i.Status,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.ItemsDiscovered,
		&i.ItemsProcessed,
		&i.ParseYield7d,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceCursor = `-- name: GetSourceCursor :one
SELECT cursor FROM source_schedule WHERE source_id = $1
`

// Read the cursor directly, independent of whether the source is due. A manual
// re-run must still send If-None-Match, or it re-downloads the whole board.
func (q *Queries) GetSourceCursor(ctx context.Context, sourceID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSourceCursor, sourceID)
	var cursor []byte
	err := row.Scan(&cursor)
	return cursor, err
}

const insertOpportunityFromPosting = `-- name: InsertOpportunityFromPosting :one
INSERT INTO opportunity (
    company_id, title_raw, title_normalized, description_text,
    work_mode, location_region, language, apply_method, ats_type,
    source_reported_posted_at, content_hash, source_posted_at_at_last_change,
    liveness_checked_at, pipeline_state
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$10,
    -- Seeing a posting for the first time IS a verification. Leaving this NULL
    -- made "verified open, checked N ago" unanswerable for every new posting.
    now(),'parsed')
RETURNING id, tenant_id, company_id, title_raw, title_normalized, role_family, seniority_ordinal, description_text, description_html_key, employment_type, work_mode, remote_geo_scope, remote_timezone_min, remote_timezone_max, location_country, location_region, location_city, location_lat, location_lon, location_timezone, language, salary_min_minor, salary_max_minor, salary_currency, salary_period, salary_is_estimated, fx_rate_date, visa_sponsorship, apply_method, ats_type, first_seen_at, last_seen_at, source_reported_posted_at, closed_at, close_reason, consecutive_misses, liveness_checked_at, pipeline_state, attempts, last_error, next_attempt_at, lease_until, version, quality_score, ghost_risk_score, content_hash, simhash, created_at, updated_at, state_entered_at, is_management, normalization_version, block_key, merged_into, swept_at, repost_count, source_posted_at_at_last_change
`

type InsertOpportunityFromPostingParams struct {
	CompanyID              pgtype.UUID
	TitleRaw               string
	TitleNormalized        string
	DescriptionText        *string
	WorkMode               *string
	LocationRegion         *string
	Language               *string
	ApplyMethod            *string
	AtsType                *string
	SourceReportedPostedAt pgtype.Timestamptz
	ContentHash            []byte
}

func (q *Queries) InsertOpportunityFromPosting(ctx context.Context, arg InsertOpportunityFromPostingParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, insertOpportunityFromPosting,
		arg.CompanyID,
		arg.TitleRaw,
		arg.TitleNormalized,
		arg.DescriptionText,
		arg.WorkMode,
		arg.LocationRegion,
		arg.Language,
		arg.ApplyMethod,
		arg.AtsType,
		arg.SourceReportedPostedAt,
		arg.ContentHash,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.TitleRaw,
		&i.TitleNormalized,
		&i.RoleFamily,
		&i.SeniorityOrdinal,
		&i.DescriptionText,
		&i.DescriptionHtmlKey,
		&i.EmploymentType,
		&i.WorkMode,
		&i.RemoteGeoScope,
		&i.RemoteTimezoneMin,
		&i.RemoteTimezoneMax,
		&i.LocationCountry,
		&i.LocationRegion,
		&i.LocationCity,
		&i.LocationLat,
		&i.LocationLon,
		&i.LocationTimezone,
		&i.Language,
		&i.SalaryMinMinor,
		&i.SalaryMaxMinor,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryIsEstimated,
		&i.FxRateDate,
		&i.VisaSponsorship,
		&i.ApplyMethod,
		&i.AtsType,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.SourceReportedPostedAt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.ConsecutiveMisses,
		&i.LivenessCheckedAt,
		&i.PipelineState,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.Version,
		&i.QualityScore,
		&i.GhostRiskScore,
		&i.ContentHash,
		&i.Simhash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateEnteredAt,
		&i.IsManagement,
		&i.NormalizationVersion,
		&i.BlockKey,
		&i.MergedInto,
		&i.SweptAt,
		&i.RepostCount,
		&i.SourcePostedAtAtLastChange,
	)
	return i, err
}

const insertSourceRow = `-- name: InsertSourceRow :one
INSERT INTO opportunity_source (
    opportunity_id, source_id, source_job_id, ats_type, ats_job_id,
    apply_url, raw_object_key, content_hash, etag, merge_reason, merge_confidence, merged_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, opportunity_id, source_id, source_job_id, ats_type, ats_job_id, apply_url, raw_object_key, content_hash, simhash, first_seen_at, last_seen_at, etag, merge_reason, merge_confidence, merged_by, created_at
`

type InsertSourceRowParams struct {
	OpportunityID   pgtype.UUID
	SourceID        pgtype.UUID
	SourceJobID     string
	AtsType         *string
	AtsJobID        *string
	ApplyUrl        *string
	RawObjectKey    *string
	ContentHash     []byte
	Etag            *string
	MergeReason     *string
	MergeConfidence *float32
	MergedBy        *string
}

func (q *Queries) InsertSourceRow(ctx context.Context, arg InsertSourceRowParams) (OpportunitySource, error) {
	row := q.db.QueryRow(ctx, insertSourceRow,
		arg.OpportunityID,
		arg.SourceID,
		arg.SourceJobID,
		arg.AtsType,
		arg.AtsJobID,
		arg.ApplyUrl,
		arg.RawObjectKey,
		arg.ContentHash,
		arg.Etag,
		arg.MergeReason,
		arg.MergeConfidence,
		arg.MergedBy,
	)
	var i OpportunitySource
	err := row.Scan(
		&i.ID,
		&i.OpportunityID,
		&i.SourceID,
		&i.SourceJobID,
		&i.AtsType,
		&i.AtsJobID,
		&i.ApplyUrl,
		&i.RawObjectKey,
		&i.ContentHash,
		&i.Simhash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Etag,
		&i.MergeReason,
		&i.MergeConfidence,
		&i.MergedBy,
		&i.CreatedAt,
	)
	return i, err
}

const markOpportunitySeen = `-- name: MarkOpportunitySeen :execrows
UPDATE opportunity
   SET last_seen_at = now(), liveness_checked_at = now(),
       consecutive_misses = 0, closed_at = NULL, close_reason = NULL,
       repost_count = repost_count + CASE
           WHEN $1::timestamptz IS NOT NULL
            AND source_posted_at_at_last_change IS NOT NULL
            AND $1::timestamptz > source_posted_at_at_last_change
           THEN 1 ELSE 0 END,
       source_reported_posted_at = COALESCE($1::timestamptz,
                                            source_reported_posted_at)
 WHERE id = $2
`

type MarkOpportunitySeenParams struct {
	SourcePostedAt pgtype.Timestamptz
	ID             pgtype.UUID
}

// Unchanged content, but observed. Reopens a record that a flaky poll had
// closed: seeing it again is stronger evidence than having missed it.
//
// Also detects a refresh: identical content but the source moved its own
// posted-at forward. That is the strongest observable ghost signal, and it is
// only visible here — at the one moment we know the content did NOT change.
func (q *Queries) MarkOpportunitySeen(ctx context.Context, arg MarkOpportunitySeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOpportunitySeen, arg.SourcePostedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const quarantineSource = `-- name: QuarantineSource :exec
UPDATE source SET status = 'quarantined', last_error = $2 WHERE id = $1
`

type QuarantineSourceParams struct {
	ID        pgtype.UUID
	LastError *string
}

func (q *Queries) QuarantineSource(ctx context.Context, arg QuarantineSourceParams) error {
	_, err := q.db.Exec(ctx, quarantineSource, arg.ID, arg.LastError)
	return err
}

const recordSourceFailure = `-- name: RecordSourceFailure :exec
UPDATE source SET last_failure_at = now(), last_error = $2 WHERE id = $1
`

type RecordSourceFailureParams struct {
	ID        pgtype.UUID
	LastError *string
}

func (q *Queries) RecordSourceFailure(ctx context.Context, arg RecordSourceFailureParams) error {
	_, err := q.db.Exec(ctx, recordSourceFailure, arg.ID, arg.LastError)
	return err
}

const recordSourceSuccess = `-- name: RecordSourceSuccess :exec
UPDATE source
   SET last_success_at = now(), last_error = NULL,
       items_discovered = items_discovered + $1::bigint,
       items_processed  = items_processed  + $2::bigint,
       parse_yield_7d   = $3
 WHERE id = $4
`

type RecordSourceSuccessParams struct {
	Discovered int64
	Processed  int64
	Yield      pgtype.Numeric
	ID         pgtype.UUID
}

func (q *Queries) RecordSourceSuccess(ctx context.Context, arg RecordSourceSuccessParams) error {
	_, err := q.db.Exec(ctx, recordSourceSuccess,
		arg.Discovered,
		arg.Processed,
		arg.Yield,
		arg.ID,
	)
	return err
}

const saveSourceCursor = `-- name: SaveSourceCursor :exec
UPDATE source_schedule
   SET cursor = $2, last_run_at = now(), lease_until = NULL,
       next_run_at = now() + (SELECT poll_interval FROM source WHERE id = $1)
 WHERE source_id = $1
`

type SaveSourceCursorParams struct {
	ID     pgtype.UUID
	Cursor []byte
}

func (q *Queries) SaveSourceCursor(ctx context.Context, arg SaveSourceCursorParams) error {
	_, err := q.db.Exec(ctx, saveSourceCursor, arg.ID, arg.Cursor)
	return err
}

const touchSourceRow = `-- name: TouchSourceRow :exec
UPDATE opportunity_source
   SET last_seen_at = now(), content_hash = $2, etag = $3, raw_object_key = $4
 WHERE id = $1
`

type TouchSourceRowParams struct {
	ID           pgtype.UUID
	ContentHash  []byte
	Etag         *string
	RawObjectKey *string
}

func (q *Queries) TouchSourceRow(ctx context.Context, arg TouchSourceRowParams) error {
	_, err := q.db.Exec(ctx, touchSourceRow,
		arg.ID,
		arg.ContentHash,
		arg.Etag,
		arg.RawObjectKey,
	)
	return err
}

const updateOpportunityFromPosting = `-- name: UpdateOpportunityFromPosting :execrows
UPDATE opportunity
   SET title_raw = $2, title_normalized = $3, description_text = $4,
       work_mode = $5, location_region = $6, language = $7,
       source_reported_posted_at = $8, content_hash = $9,
       -- Baseline for refresh detection: the date they claimed at the moment the
       -- content last actually changed.
       source_posted_at_at_last_change = $8,
       pipeline_state = 'parsed', next_attempt_at = now(),
       attempts = 0, last_error = NULL,
       version = version + 1,
       last_seen_at = now(), liveness_checked_at = now(),
       consecutive_misses = 0, closed_at = NULL, close_reason = NULL
 WHERE id = $1
`

type UpdateOpportunityFromPostingParams struct {
	ID                     pgtype.UUID
	TitleRaw               string
	TitleNormalized        string
	DescriptionText        *string
	WorkMode               *string
	LocationRegion         *string
	Language               *string
	SourceReportedPostedAt pgtype.Timestamptz
	ContentHash            []byte
}

// Content changed, so the record re-enters the pipeline at 'parsed'. Version is
// bumped, which is what invalidates any cached fit score for it.
func (q *Queries) UpdateOpportunityFromPosting(ctx context.Context, arg UpdateOpportunityFromPostingParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOpportunityFromPosting,
		arg.ID,
		arg.TitleRaw,
		arg.TitleNormalized,
		arg.DescriptionText,
		arg.WorkMode,
		arg.LocationRegion,
		arg.Language,
		arg.SourceReportedPostedAt,
		arg.ContentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCompanyByDomain = `-- name: UpsertCompanyByDomain :one
INSERT INTO company (canonical_domain, display_name)
VALUES ($1, $2)
ON CONFLICT (canonical_domain) DO UPDATE
   SET display_name = COALESCE(NULLIF(EXCLUDED.display_name, ''), company.display_name)
RETURNING id, canonical_domain, display_name, is_agency, industry, size_band, stage, hq_country, created_at, updated_at, domain_confirmed
`

type UpsertCompanyByDomainParams struct {
	CanonicalDomain string
	DisplayName     string
}

// Resolution is on the registrable domain, never the name: "Google" /
// "Google LLC" / "Alphabet" / "google.com" are one employer with four spellings.
func (q *Queries) UpsertCompanyByDomain(ctx context.Context, arg UpsertCompanyByDomainParams) (Company, error) {
	row := q.db.QueryRow(ctx, upsertCompanyByDomain, arg.CanonicalDomain, arg.DisplayName)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CanonicalDomain,
		&i.DisplayName,
		&i.IsAgency,
		&i.Industry,
		&i.SizeBand,
		&i.Stage,
		&i.HqCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainConfirmed,
	)
	return i, err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO source (name, tier, type, legal_basis, poll_interval, etag_supported,
                    robots_checked_at, terms_reviewed_at, reviewed_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type
RETURNING id, name, tier, type, legal_basis, robots_checked_at, terms_reviewed_at, reviewed_by, rate_limit_rps, poll_interval, etag_supported, status, last_success_at, last_failure_at, last_error, items_discovered, items_processed, parse_yield_7d, created_at, updated_at
`

type UpsertSourceParams struct {
	Name            string
	Tier            string
	Type            string
	LegalBasis      string
	PollInterval    pgtype.Interval
	EtagSupported   bool
	RobotsCheckedAt pgtype.Timestamptz
	TermsReviewedAt pgtype.Timestamptz
	ReviewedBy      *string
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, upsertSource,
		arg.Name,
		arg.Tier,
		arg.Type,
		arg.LegalBasis,
		arg.PollInterval,
		arg.EtagSupported,
		arg.RobotsCheckedAt,
		arg.TermsReviewedAt,
		arg.ReviewedBy,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.Type,
		&i.LegalBasis,
		&i.RobotsCheckedAt,
		&i.TermsReviewedAt,
		&i.ReviewedBy,
		&i.RateLimitRps,
		&i.PollInterval,
		&i.EtagSupported,
		&i.Status,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.ItemsDiscovered,
		&i.ItemsProcessed,
		&i.ParseYield7d,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSourceSchedule = `-- name: UpsertSourceSchedule :exec
INSERT INTO source_schedule (source_id, next_run_at, cursor)
VALUES ($1, now(), $2)
ON CONFLICT (source_id) DO UPDATE
   SET next_run_at = EXCLUDED.next_run_at, cursor = EXCLUDED.cursor
`

type UpsertSourceScheduleParams struct {
	SourceID pgtype.UUID
	Cursor   []byte
}

func (q *Queries) UpsertSourceSchedule(ctx context.Context, arg UpsertSourceScheduleParams) error {
	_, err := q.db.Exec(ctx, upsertSourceSchedule, arg.SourceID, arg.Cursor)
	return err
}
