// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const countEligibilityFailuresByCheck = `-- name: CountEligibilityFailuresByCheck :many
SELECT unnest(failed_checks) AS check_name, count(*) AS failures
  FROM eligibility_result
 WHERE user_id = $1 AND NOT eligible
 GROUP BY 1
 ORDER BY 2 DESC
`

type CountEligibilityFailuresByCheckRow struct {
	CheckName interface{}
	Failures  int64
}

// Operational view: which gate is excluding the most for one user.
//
// A gate that quietly empties a feed is indistinguishable from an empty market,
// so this is the query that tells them apart.
func (q *Queries) CountEligibilityFailuresByCheck(ctx context.Context, userID pgtype.UUID) ([]CountEligibilityFailuresByCheckRow, error) {
	rows, err := q.db.Query(ctx, countEligibilityFailuresByCheck, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEligibilityFailuresByCheckRow
	for rows.Next() {
		var i CountEligibilityFailuresByCheckRow
		if err := rows.Scan(&i.CheckName, &i.Failures); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEligibilityResults = `-- name: DeleteEligibilityResults :execrows
DELETE FROM eligibility_result WHERE user_id = $1
`

func (q *Queries) DeleteEligibilityResults(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEligibilityResults, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFitScores = `-- name: DeleteFitScores :execrows
DELETE FROM fit_score WHERE user_id = $1
`

// Erasure. Enumerated rather than left to the app_user cascade so the report can
// state a count for this store.
func (q *Queries) DeleteFitScores(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFitScores, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFitScores = `-- name: GetFitScores :many
SELECT f.opportunity_id, f.score, f.max_possible, f.factors
  FROM fit_score f
  JOIN opportunity o ON o.id = f.opportunity_id
 WHERE f.user_id = $1
   AND f.weights_version = $2
   AND f.profile_version = $3
   AND f.embedding_version = $4
   AND f.opportunity_version = o.version
`

type GetFitScoresParams struct {
	UserID           pgtype.UUID
	WeightsVersion   string
	ProfileVersion   int32
	EmbeddingVersion string
}

type GetFitScoresRow struct {
	OpportunityID pgtype.UUID
	Score         int16
	MaxPossible   int16
	Factors       []byte
}

// Cached scores for one user under one set of versions. The profile and
// opportunity versions are checked per row, so a stale score is a cache MISS
// rather than a wrong answer served fast.
func (q *Queries) GetFitScores(ctx context.Context, arg GetFitScoresParams) ([]GetFitScoresRow, error) {
	rows, err := q.db.Query(ctx, getFitScores,
		arg.UserID,
		arg.WeightsVersion,
		arg.ProfileVersion,
		arg.EmbeddingVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFitScoresRow
	for rows.Next() {
		var i GetFitScoresRow
		if err := rows.Scan(
			&i.OpportunityID,
			&i.Score,
			&i.MaxPossible,
			&i.Factors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpportunitiesForScoring = `-- name: GetOpportunitiesForScoring :many
SELECT o.id, o.tenant_id, o.company_id, o.title_raw, o.title_normalized, o.role_family, o.seniority_ordinal, o.description_text, o.description_html_key, o.employment_type, o.work_mode, o.remote_geo_scope, o.remote_timezone_min, o.remote_timezone_max, o.location_country, o.location_region, o.location_city, o.location_lat, o.location_lon, o.location_timezone, o.language, o.salary_min_minor, o.salary_max_minor, o.salary_currency, o.salary_period, o.salary_is_estimated, o.fx_rate_date, o.visa_sponsorship, o.apply_method, o.ats_type, o.first_seen_at, o.last_seen_at, o.source_reported_posted_at, o.closed_at, o.close_reason, o.consecutive_misses, o.liveness_checked_at, o.pipeline_state, o.attempts, o.last_error, o.next_attempt_at, o.lease_until, o.version, o.quality_score, o.ghost_risk_score, o.content_hash, o.simhash, o.created_at, o.updated_at, o.state_entered_at, o.is_management, o.normalization_version, o.block_key, o.merged_into, o.swept_at, o.repost_count, o.source_posted_at_at_last_change, o.extraction_content_hash, o.enriched_at, o.extraction_error,
       (e.embedding <=> $1::vector)::double precision AS distance
  FROM opportunity o
  LEFT JOIN opportunity_embedding e
    ON e.opportunity_id = o.id
   AND e.embedding_version = $2
 WHERE o.id = ANY ($3::uuid[])
`

type GetOpportunitiesForScoringParams struct {
	QueryVector      pgvector.Vector
	EmbeddingVersion string
	OpportunityIds   []pgtype.UUID
}

type GetOpportunitiesForScoringRow struct {
	Opportunity Opportunity
	Distance    float64
}

// The candidate rows plus their vector distance from the profile, in one query.
//
// The distance comes from the same embedding version retrieval used, because a
// cosine value from another model is not a smaller or larger number, it is a
// meaningless one.
func (q *Queries) GetOpportunitiesForScoring(ctx context.Context, arg GetOpportunitiesForScoringParams) ([]GetOpportunitiesForScoringRow, error) {
	rows, err := q.db.Query(ctx, getOpportunitiesForScoring, arg.QueryVector, arg.EmbeddingVersion, arg.OpportunityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpportunitiesForScoringRow
	for rows.Next() {
		var i GetOpportunitiesForScoringRow
		if err := rows.Scan(
			&i.Opportunity.ID,
			&i.Opportunity.TenantID,
			&i.Opportunity.CompanyID,
			&i.Opportunity.TitleRaw,
			&i.Opportunity.TitleNormalized,
			&i.Opportunity.RoleFamily,
			&i.Opportunity.SeniorityOrdinal,
			&i.Opportunity.DescriptionText,
			&i.Opportunity.DescriptionHtmlKey,
			&i.Opportunity.EmploymentType,
			&i.Opportunity.WorkMode,
			&i.Opportunity.RemoteGeoScope,
			&i.Opportunity.RemoteTimezoneMin,
			&i.Opportunity.RemoteTimezoneMax,
			&i.Opportunity.LocationCountry,
			&i.Opportunity.LocationRegion,
			&i.Opportunity.LocationCity,
			&i.Opportunity.LocationLat,
			&i.Opportunity.LocationLon,
			&i.Opportunity.LocationTimezone,
			&i.Opportunity.Language,
			&i.Opportunity.SalaryMinMinor,
			&i.Opportunity.SalaryMaxMinor,
			&i.Opportunity.SalaryCurrency,
			&i.Opportunity.SalaryPeriod,
			&i.Opportunity.SalaryIsEstimated,
			&i.Opportunity.FxRateDate,
			&i.Opportunity.VisaSponsorship,
			&i.Opportunity.ApplyMethod,
			&i.Opportunity.AtsType,
			&i.Opportunity.FirstSeenAt,
			&i.Opportunity.LastSeenAt,
			&i.Opportunity.SourceReportedPostedAt,
			&i.Opportunity.ClosedAt,
			&i.Opportunity.CloseReason,
			&i.Opportunity.ConsecutiveMisses,
			&i.Opportunity.LivenessCheckedAt,
			&i.Opportunity.PipelineState,
			&i.Opportunity.Attempts,
			&i.Opportunity.LastError,
			&i.Opportunity.NextAttemptAt,
			&i.Opportunity.LeaseUntil,
			&i.Opportunity.Version,
			&i.Opportunity.QualityScore,
			&i.Opportunity.GhostRiskScore,
			&i.Opportunity.ContentHash,
			&i.Opportunity.Simhash,
			&i.Opportunity.CreatedAt,
			&i.Opportunity.UpdatedAt,
			&i.Opportunity.StateEnteredAt,
			&i.Opportunity.IsManagement,
			&i.Opportunity.NormalizationVersion,
			&i.Opportunity.BlockKey,
			&i.Opportunity.MergedInto,
			&i.Opportunity.SweptAt,
			&i.Opportunity.RepostCount,
			&i.Opportunity.SourcePostedAtAtLastChange,
			&i.Opportunity.ExtractionContentHash,
			&i.Opportunity.EnrichedAt,
			&i.Opportunity.ExtractionError,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpportunitySkills = `-- name: GetOpportunitySkills :many
SELECT os.opportunity_id, os.skill_id, os.requirement_level
  FROM opportunity_skill os
 WHERE os.opportunity_id = ANY ($1::uuid[])
   AND os.requirement_level IN ('required', 'preferred')
`

type GetOpportunitySkillsRow struct {
	OpportunityID    pgtype.UUID
	SkillID          pgtype.UUID
	RequirementLevel string
}

// Extracted skills for a set of postings, split by requirement level. Batched
// over the candidate set rather than queried per posting: 500 candidates would
// otherwise be 500 round trips inside one feed request.
func (q *Queries) GetOpportunitySkills(ctx context.Context, opportunityIds []pgtype.UUID) ([]GetOpportunitySkillsRow, error) {
	rows, err := q.db.Query(ctx, getOpportunitySkills, opportunityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpportunitySkillsRow
	for rows.Next() {
		var i GetOpportunitySkillsRow
		if err := rows.Scan(&i.OpportunityID, &i.SkillID, &i.RequirementLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileSkillIDs = `-- name: GetProfileSkillIDs :many
SELECT ps.skill_id FROM profile_skill ps WHERE ps.user_id = $1
`

func (q *Queries) GetProfileSkillIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getProfileSkillIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var skill_id pgtype.UUID
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putEligibilityResult = `-- name: PutEligibilityResult :exec
INSERT INTO eligibility_result (
    user_id, opportunity_id, profile_version, opportunity_version,
    eligible, failed_checks
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (user_id, opportunity_id, profile_version, opportunity_version)
DO UPDATE SET eligible = excluded.eligible,
              failed_checks = excluded.failed_checks,
              evaluated_at = now()
`

type PutEligibilityResultParams struct {
	UserID             pgtype.UUID
	OpportunityID      pgtype.UUID
	ProfileVersion     int32
	OpportunityVersion int32
	Eligible           bool
	FailedChecks       []string
}

func (q *Queries) PutEligibilityResult(ctx context.Context, arg PutEligibilityResultParams) error {
	_, err := q.db.Exec(ctx, putEligibilityResult,
		arg.UserID,
		arg.OpportunityID,
		arg.ProfileVersion,
		arg.OpportunityVersion,
		arg.Eligible,
		arg.FailedChecks,
	)
	return err
}

const putFitScore = `-- name: PutFitScore :exec
INSERT INTO fit_score (
    user_id, opportunity_id, weights_version, profile_version,
    opportunity_version, embedding_version, score, max_possible, factors
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9
)
ON CONFLICT (user_id, opportunity_id, weights_version, profile_version,
             opportunity_version, embedding_version)
DO UPDATE SET score = excluded.score,
              max_possible = excluded.max_possible,
              factors = excluded.factors,
              computed_at = now()
`

type PutFitScoreParams struct {
	UserID             pgtype.UUID
	OpportunityID      pgtype.UUID
	WeightsVersion     string
	ProfileVersion     int32
	OpportunityVersion int32
	EmbeddingVersion   string
	Score              int16
	MaxPossible        int16
	Factors            []byte
}

// Cache one score. Keyed on every version it depends on, so a version change
// writes a new row rather than overwriting a score computed under other rules.
func (q *Queries) PutFitScore(ctx context.Context, arg PutFitScoreParams) error {
	_, err := q.db.Exec(ctx, putFitScore,
		arg.UserID,
		arg.OpportunityID,
		arg.WeightsVersion,
		arg.ProfileVersion,
		arg.OpportunityVersion,
		arg.EmbeddingVersion,
		arg.Score,
		arg.MaxPossible,
		arg.Factors,
	)
	return err
}
