// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const countEligibilityFailuresByCheck = `-- name: CountEligibilityFailuresByCheck :many
SELECT unnest(failed_checks) AS check_name, count(*) AS failures
  FROM eligibility_result
 WHERE user_id = $1 AND NOT eligible
 GROUP BY 1
 ORDER BY 2 DESC
`

type CountEligibilityFailuresByCheckRow struct {
	CheckName interface{}
	Failures  int64
}

// Operational view: which gate is excluding the most for one user.
//
// A gate that quietly empties a feed is indistinguishable from an empty market,
// so this is the query that tells them apart.
func (q *Queries) CountEligibilityFailuresByCheck(ctx context.Context, userID pgtype.UUID) ([]CountEligibilityFailuresByCheckRow, error) {
	rows, err := q.db.Query(ctx, countEligibilityFailuresByCheck, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEligibilityFailuresByCheckRow
	for rows.Next() {
		var i CountEligibilityFailuresByCheckRow
		if err := rows.Scan(&i.CheckName, &i.Failures); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEligibilityResults = `-- name: DeleteEligibilityResults :execrows
DELETE FROM eligibility_result WHERE user_id = $1
`

func (q *Queries) DeleteEligibilityResults(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEligibilityResults, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFitScores = `-- name: DeleteFitScores :execrows
DELETE FROM fit_score WHERE user_id = $1
`

// Erasure. Enumerated rather than left to the app_user cascade so the report can
// state a count for this store.
func (q *Queries) DeleteFitScores(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFitScores, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCachedFitScore = `-- name: GetCachedFitScore :one
SELECT f.score, f.max_possible, f.factors, f.weights_version,
       f.embedding_version, f.profile_version, f.opportunity_version
  FROM fit_score f
  JOIN opportunity o ON o.id = f.opportunity_id
 WHERE f.user_id = $1
   AND f.opportunity_id = $2
   AND f.weights_version = $3
   AND f.opportunity_version = o.version
 ORDER BY f.computed_at DESC
 LIMIT 1
`

type GetCachedFitScoreParams struct {
	UserID         pgtype.UUID
	OpportunityID  pgtype.UUID
	WeightsVersion string
}

type GetCachedFitScoreRow struct {
	Score              int16
	MaxPossible        int16
	Factors            []byte
	WeightsVersion     string
	EmbeddingVersion   string
	ProfileVersion     int32
	OpportunityVersion int32
}

// One cached score, for the engagement decision record.
//
// Read from the cache rather than recomputed: the record must say what was SHOWN,
// and re-running the matcher on every save would also mean a full retrieval and
// scoring pass on a request that should be a single insert.
func (q *Queries) GetCachedFitScore(ctx context.Context, arg GetCachedFitScoreParams) (GetCachedFitScoreRow, error) {
	row := q.db.QueryRow(ctx, getCachedFitScore, arg.UserID, arg.OpportunityID, arg.WeightsVersion)
	var i GetCachedFitScoreRow
	err := row.Scan(
		&i.Score,
		&i.MaxPossible,
		&i.Factors,
		&i.WeightsVersion,
		&i.EmbeddingVersion,
		&i.ProfileVersion,
		&i.OpportunityVersion,
	)
	return i, err
}

const getFitScores = `-- name: GetFitScores :many
SELECT f.opportunity_id, f.score, f.max_possible, f.factors
  FROM fit_score f
  JOIN opportunity o ON o.id = f.opportunity_id
 WHERE f.user_id = $1
   AND f.weights_version = $2
   AND f.profile_version = $3
   AND f.embedding_version = $4
   AND f.opportunity_version = o.version
`

type GetFitScoresParams struct {
	UserID           pgtype.UUID
	WeightsVersion   string
	ProfileVersion   int32
	EmbeddingVersion string
}

type GetFitScoresRow struct {
	OpportunityID pgtype.UUID
	Score         int16
	MaxPossible   int16
	Factors       []byte
}

// Cached scores for one user under one set of versions. The profile and
// opportunity versions are checked per row, so a stale score is a cache MISS
// rather than a wrong answer served fast.
func (q *Queries) GetFitScores(ctx context.Context, arg GetFitScoresParams) ([]GetFitScoresRow, error) {
	rows, err := q.db.Query(ctx, getFitScores,
		arg.UserID,
		arg.WeightsVersion,
		arg.ProfileVersion,
		arg.EmbeddingVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFitScoresRow
	for rows.Next() {
		var i GetFitScoresRow
		if err := rows.Scan(
			&i.OpportunityID,
			&i.Score,
			&i.MaxPossible,
			&i.Factors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpportunitiesForScoring = `-- name: GetOpportunitiesForScoring :many
SELECT o.id, o.tenant_id, o.company_id, o.title_raw, o.title_normalized, o.role_family, o.seniority_ordinal, o.description_text, o.description_html_key, o.employment_type, o.work_mode, o.remote_geo_scope, o.remote_timezone_min, o.remote_timezone_max, o.location_country, o.location_region, o.location_city, o.location_lat, o.location_lon, o.location_timezone, o.language, o.salary_min_minor, o.salary_max_minor, o.salary_currency, o.salary_period, o.salary_is_estimated, o.fx_rate_date, o.visa_sponsorship, o.apply_method, o.ats_type, o.first_seen_at, o.last_seen_at, o.source_reported_posted_at, o.closed_at, o.close_reason, o.consecutive_misses, o.liveness_checked_at, o.pipeline_state, o.attempts, o.last_error, o.next_attempt_at, o.lease_until, o.version, o.quality_score, o.ghost_risk_score, o.content_hash, o.simhash, o.created_at, o.updated_at, o.state_entered_at, o.is_management, o.normalization_version, o.block_key, o.merged_into, o.swept_at, o.repost_count, o.source_posted_at_at_last_change, o.extraction_content_hash, o.enriched_at, o.extraction_error, o.unmerged_at,
       (e.embedding <=> $1::vector)::double precision AS distance
  FROM opportunity o
  LEFT JOIN opportunity_embedding e
    ON e.opportunity_id = o.id
   AND e.embedding_version = $2
 WHERE o.id = ANY ($3::uuid[])
`

type GetOpportunitiesForScoringParams struct {
	QueryVector      pgvector.Vector
	EmbeddingVersion string
	OpportunityIds   []pgtype.UUID
}

type GetOpportunitiesForScoringRow struct {
	Opportunity Opportunity
	Distance    float64
}

// The candidate rows plus their vector distance from the profile, in one query.
//
// The distance comes from the same embedding version retrieval used, because a
// cosine value from another model is not a smaller or larger number, it is a
// meaningless one.
func (q *Queries) GetOpportunitiesForScoring(ctx context.Context, arg GetOpportunitiesForScoringParams) ([]GetOpportunitiesForScoringRow, error) {
	rows, err := q.db.Query(ctx, getOpportunitiesForScoring, arg.QueryVector, arg.EmbeddingVersion, arg.OpportunityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpportunitiesForScoringRow
	for rows.Next() {
		var i GetOpportunitiesForScoringRow
		if err := rows.Scan(
			&i.Opportunity.ID,
			&i.Opportunity.TenantID,
			&i.Opportunity.CompanyID,
			&i.Opportunity.TitleRaw,
			&i.Opportunity.TitleNormalized,
			&i.Opportunity.RoleFamily,
			&i.Opportunity.SeniorityOrdinal,
			&i.Opportunity.DescriptionText,
			&i.Opportunity.DescriptionHtmlKey,
			&i.Opportunity.EmploymentType,
			&i.Opportunity.WorkMode,
			&i.Opportunity.RemoteGeoScope,
			&i.Opportunity.RemoteTimezoneMin,
			&i.Opportunity.RemoteTimezoneMax,
			&i.Opportunity.LocationCountry,
			&i.Opportunity.LocationRegion,
			&i.Opportunity.LocationCity,
			&i.Opportunity.LocationLat,
			&i.Opportunity.LocationLon,
			&i.Opportunity.LocationTimezone,
			&i.Opportunity.Language,
			&i.Opportunity.SalaryMinMinor,
			&i.Opportunity.SalaryMaxMinor,
			&i.Opportunity.SalaryCurrency,
			&i.Opportunity.SalaryPeriod,
			&i.Opportunity.SalaryIsEstimated,
			&i.Opportunity.FxRateDate,
			&i.Opportunity.VisaSponsorship,
			&i.Opportunity.ApplyMethod,
			&i.Opportunity.AtsType,
			&i.Opportunity.FirstSeenAt,
			&i.Opportunity.LastSeenAt,
			&i.Opportunity.SourceReportedPostedAt,
			&i.Opportunity.ClosedAt,
			&i.Opportunity.CloseReason,
			&i.Opportunity.ConsecutiveMisses,
			&i.Opportunity.LivenessCheckedAt,
			&i.Opportunity.PipelineState,
			&i.Opportunity.Attempts,
			&i.Opportunity.LastError,
			&i.Opportunity.NextAttemptAt,
			&i.Opportunity.LeaseUntil,
			&i.Opportunity.Version,
			&i.Opportunity.QualityScore,
			&i.Opportunity.GhostRiskScore,
			&i.Opportunity.ContentHash,
			&i.Opportunity.Simhash,
			&i.Opportunity.CreatedAt,
			&i.Opportunity.UpdatedAt,
			&i.Opportunity.StateEnteredAt,
			&i.Opportunity.IsManagement,
			&i.Opportunity.NormalizationVersion,
			&i.Opportunity.BlockKey,
			&i.Opportunity.MergedInto,
			&i.Opportunity.SweptAt,
			&i.Opportunity.RepostCount,
			&i.Opportunity.SourcePostedAtAtLastChange,
			&i.Opportunity.ExtractionContentHash,
			&i.Opportunity.EnrichedAt,
			&i.Opportunity.ExtractionError,
			&i.Opportunity.UnmergedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpportunitySkills = `-- name: GetOpportunitySkills :many
SELECT os.opportunity_id, os.skill_id, os.requirement_level
  FROM opportunity_skill os
 WHERE os.opportunity_id = ANY ($1::uuid[])
   AND os.requirement_level IN ('required', 'preferred')
`

type GetOpportunitySkillsRow struct {
	OpportunityID    pgtype.UUID
	SkillID          pgtype.UUID
	RequirementLevel string
}

// Extracted skills for a set of postings, split by requirement level. Batched
// over the candidate set rather than queried per posting: 500 candidates would
// otherwise be 500 round trips inside one feed request.
func (q *Queries) GetOpportunitySkills(ctx context.Context, opportunityIds []pgtype.UUID) ([]GetOpportunitySkillsRow, error) {
	rows, err := q.db.Query(ctx, getOpportunitySkills, opportunityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpportunitySkillsRow
	for rows.Next() {
		var i GetOpportunitySkillsRow
		if err := rows.Scan(&i.OpportunityID, &i.SkillID, &i.RequirementLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileSkillIDs = `-- name: GetProfileSkillIDs :many
SELECT ps.skill_id FROM profile_skill ps WHERE ps.user_id = $1
`

func (q *Queries) GetProfileSkillIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getProfileSkillIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var skill_id pgtype.UUID
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putEligibilityResult = `-- name: PutEligibilityResult :exec
INSERT INTO eligibility_result (
    user_id, opportunity_id, profile_version, opportunity_version,
    eligible, failed_checks
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (user_id, opportunity_id, profile_version, opportunity_version)
DO UPDATE SET eligible = excluded.eligible,
              failed_checks = excluded.failed_checks,
              evaluated_at = now()
`

type PutEligibilityResultParams struct {
	UserID             pgtype.UUID
	OpportunityID      pgtype.UUID
	ProfileVersion     int32
	OpportunityVersion int32
	Eligible           bool
	FailedChecks       []string
}

func (q *Queries) PutEligibilityResult(ctx context.Context, arg PutEligibilityResultParams) error {
	_, err := q.db.Exec(ctx, putEligibilityResult,
		arg.UserID,
		arg.OpportunityID,
		arg.ProfileVersion,
		arg.OpportunityVersion,
		arg.Eligible,
		arg.FailedChecks,
	)
	return err
}

const putFitScore = `-- name: PutFitScore :exec
INSERT INTO fit_score (
    user_id, opportunity_id, weights_version, profile_version,
    opportunity_version, embedding_version, score, max_possible, factors
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9
)
ON CONFLICT (user_id, opportunity_id, weights_version, profile_version,
             opportunity_version, embedding_version)
DO UPDATE SET score = excluded.score,
              max_possible = excluded.max_possible,
              factors = excluded.factors,
              computed_at = now()
`

type PutFitScoreParams struct {
	UserID             pgtype.UUID
	OpportunityID      pgtype.UUID
	WeightsVersion     string
	ProfileVersion     int32
	OpportunityVersion int32
	EmbeddingVersion   string
	Score              int16
	MaxPossible        int16
	Factors            []byte
}

// Cache one score. Keyed on every version it depends on, so a version change
// writes a new row rather than overwriting a score computed under other rules.
func (q *Queries) PutFitScore(ctx context.Context, arg PutFitScoreParams) error {
	_, err := q.db.Exec(ctx, putFitScore,
		arg.UserID,
		arg.OpportunityID,
		arg.WeightsVersion,
		arg.ProfileVersion,
		arg.OpportunityVersion,
		arg.EmbeddingVersion,
		arg.Score,
		arg.MaxPossible,
		arg.Factors,
	)
	return err
}

const skillGapCoverage = `-- name: SkillGapCoverage :one
SELECT count(DISTINCT o.id)::bigint AS eligible,
       count(DISTINCT o.id) FILTER (
           WHERE EXISTS (SELECT 1 FROM opportunity_skill os
                          WHERE os.opportunity_id = o.id))::bigint AS with_skills
  FROM eligibility_result er
  JOIN profile p     ON p.user_id = er.user_id
                    AND p.profile_version = er.profile_version
  JOIN opportunity o ON o.id = er.opportunity_id
 WHERE er.user_id = $1
   AND er.eligible
   AND o.pipeline_state = 'ready'
   AND o.closed_at IS NULL
   AND o.merged_into IS NULL
`

type SkillGapCoverageRow struct {
	Eligible   int64
	WithSkills int64
}

// The denominator, without which every count above is unreadable.
//
// A posting whose skills were never extracted contributes nothing to the gap
// analysis, so reporting "23 roles want Kubernetes" out of an unstated total
// silently understates by however much of the corpus is unenriched. This is the
// honest denominator: eligible roles, and how many of them we could actually
// read.
func (q *Queries) SkillGapCoverage(ctx context.Context, userID pgtype.UUID) (SkillGapCoverageRow, error) {
	row := q.db.QueryRow(ctx, skillGapCoverage, userID)
	var i SkillGapCoverageRow
	err := row.Scan(&i.Eligible, &i.WithSkills)
	return i, err
}

const skillGapsForUser = `-- name: SkillGapsForUser :many
SELECT s.canonical_slug::text AS slug,
       s.display_name,
       count(DISTINCT o.id) FILTER (WHERE os.requirement_level = 'required')::bigint
           AS required_by,
       count(DISTINCT o.id) FILTER (WHERE os.requirement_level = 'preferred')::bigint
           AS preferred_by,
       -- Whether the vocabulary knows this skill. An extraction-invented phrase
       -- is not advice anyone can act on, so the caller can exclude it.
       (s.ontology_version LIKE 'seed-%')::boolean AS in_vocabulary
  FROM eligibility_result er
  JOIN profile p            ON p.user_id = er.user_id
                           AND p.profile_version = er.profile_version
  JOIN opportunity o        ON o.id = er.opportunity_id
  JOIN opportunity_skill os ON os.opportunity_id = o.id
  JOIN skill s              ON s.id = os.skill_id
 WHERE er.user_id = $1
   AND er.eligible
   AND o.pipeline_state = 'ready'
   AND o.closed_at IS NULL
   AND o.merged_into IS NULL
   AND os.requirement_level IN ('required', 'preferred')
   -- The gap is what they do NOT have. Origin is irrelevant: a skill claimed by
   -- hand and one read off a resume are both "has it".
   AND NOT EXISTS (
        SELECT 1 FROM profile_skill ps
         WHERE ps.user_id = er.user_id AND ps.skill_id = s.id)
 GROUP BY s.id, s.canonical_slug, s.display_name, s.ontology_version
 ORDER BY required_by DESC, preferred_by DESC, s.display_name
 LIMIT $2::int
`

type SkillGapsForUserParams struct {
	UserID  pgtype.UUID
	MaxRows int32
}

type SkillGapsForUserRow struct {
	Slug         string
	DisplayName  string
	RequiredBy   int64
	PreferredBy  int64
	InVocabulary bool
}

// Which skills the roles this user is eligible for ask for, that they do not have.
//
// Question four of the product's four: "what should I learn to be more
// competitive". Answered here as ARITHMETIC OVER OBSERVED DATA and nothing else
// — a count of postings, not an estimate of anyone's chances. We have no
// applicant counts, so there is no competitiveness figure to give and inventing
// one would discredit the honest numbers beside it (blueprint §3).
//
// Scoped to the user's ELIGIBLE set rather than the whole corpus. A skill that
// half the market wants is useless advice if every posting needing it fails this
// person's work-authorization or location gate; the only roles worth naming a
// gap for are the ones they could actually take.
//
// TWO things this query has to get right about eligibility_result, both of which
// it got wrong first:
//
//  1. Its primary key is (user_id, opportunity_id, profile_version,
//     opportunity_version), so it holds one row PER VERSION PAIR. Counting rows
//     counted 502 "roles" against a 265-posting corpus. Every count is over
//     DISTINCT opportunities.
//  2. A result computed against an older profile_version describes a gate the
//     user no longer has. Restricting to the CURRENT version is what keeps this
//     an analysis of who they are rather than who they were.
func (q *Queries) SkillGapsForUser(ctx context.Context, arg SkillGapsForUserParams) ([]SkillGapsForUserRow, error) {
	rows, err := q.db.Query(ctx, skillGapsForUser, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillGapsForUserRow
	for rows.Next() {
		var i SkillGapsForUserRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.RequiredBy,
			&i.PreferredBy,
			&i.InVocabulary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillsUserHasInDemand = `-- name: SkillsUserHasInDemand :many
SELECT s.display_name,
       count(DISTINCT o.id) FILTER (WHERE os.requirement_level = 'required')::bigint
           AS required_by
  FROM profile_skill ps
  JOIN skill s              ON s.id = ps.skill_id
  JOIN opportunity_skill os ON os.skill_id = s.id
  JOIN eligibility_result er ON er.opportunity_id = os.opportunity_id
  JOIN profile p            ON p.user_id = er.user_id
                           AND p.profile_version = er.profile_version
  JOIN opportunity o        ON o.id = er.opportunity_id
 WHERE ps.user_id = $1
   AND er.user_id = $1
   AND er.eligible
   AND o.pipeline_state = 'ready'
   AND o.closed_at IS NULL
   AND o.merged_into IS NULL
   AND os.requirement_level = 'required'
 GROUP BY s.id, s.display_name
 ORDER BY required_by DESC, s.display_name
 LIMIT $2::int
`

type SkillsUserHasInDemandParams struct {
	UserID  pgtype.UUID
	MaxRows int32
}

type SkillsUserHasInDemandRow struct {
	DisplayName string
	RequiredBy  int64
}

// The mirror: skills they DO have, and how many eligible roles ask for them.
//
// Included because a gap list on its own reads as a deficit report. The same
// arithmetic run the other way is what makes it a position rather than a verdict,
// and it costs one query.
func (q *Queries) SkillsUserHasInDemand(ctx context.Context, arg SkillsUserHasInDemandParams) ([]SkillsUserHasInDemandRow, error) {
	rows, err := q.db.Query(ctx, skillsUserHasInDemand, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillsUserHasInDemandRow
	for rows.Next() {
		var i SkillsUserHasInDemandRow
		if err := rows.Scan(&i.DisplayName, &i.RequiredBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
