// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type AppUser struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
	Status          string
	FailedLogins    int32
	LockedUntil     pgtype.Timestamptz
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AuditLog struct {
	ID         int64
	OccurredAt pgtype.Timestamptz
	ActorID    pgtype.UUID
	TenantID   pgtype.UUID
	Action     string
	Subject    *string
	Metadata   []byte
	PrevHash   []byte
	EntryHash  []byte
}

type Company struct {
	ID              pgtype.UUID
	CanonicalDomain string
	DisplayName     string
	IsAgency        bool
	Industry        *string
	SizeBand        *string
	Stage           *string
	HqCountry       *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DomainConfirmed bool
}

type CompanyAlias struct {
	CompanyID pgtype.UUID
	Alias     string
	SourceID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type CompanyMerge struct {
	ID            pgtype.UUID
	FromCompanyID pgtype.UUID
	IntoCompanyID pgtype.UUID
	Reason        string
	Confidence    *float32
	MergedBy      string
	MergedAt      pgtype.Timestamptz
	UndoneAt      pgtype.Timestamptz
}

type MergeCandidate struct {
	ID                 pgtype.UUID
	LeftOpportunityID  pgtype.UUID
	RightOpportunityID pgtype.UUID
	Reason             string
	Confidence         float32
	WithheldBecause    string
	Resolution         *string
	ResolvedBy         *string
	ResolvedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type Opportunity struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	CompanyID              pgtype.UUID
	TitleRaw               string
	TitleNormalized        string
	RoleFamily             *string
	SeniorityOrdinal       *int16
	DescriptionText        *string
	DescriptionHtmlKey     *string
	EmploymentType         *string
	WorkMode               *string
	RemoteGeoScope         *string
	RemoteTimezoneMin      *int16
	RemoteTimezoneMax      *int16
	LocationCountry        *string
	LocationRegion         *string
	LocationCity           *string
	LocationLat            *float64
	LocationLon            *float64
	LocationTimezone       *string
	Language               *string
	SalaryMinMinor         *int64
	SalaryMaxMinor         *int64
	SalaryCurrency         *string
	SalaryPeriod           *string
	SalaryIsEstimated      bool
	FxRateDate             pgtype.Date
	VisaSponsorship        string
	ApplyMethod            *string
	AtsType                *string
	FirstSeenAt            pgtype.Timestamptz
	LastSeenAt             pgtype.Timestamptz
	SourceReportedPostedAt pgtype.Timestamptz
	ClosedAt               pgtype.Timestamptz
	CloseReason            *string
	ConsecutiveMisses      int32
	LivenessCheckedAt      pgtype.Timestamptz
	PipelineState          string
	Attempts               int32
	LastError              *string
	NextAttemptAt          pgtype.Timestamptz
	LeaseUntil             pgtype.Timestamptz
	Version                int32
	QualityScore           *float32
	// Reserved for a periodic snapshot. Ghost risk is volatile and is computed at read time from repost_count, first_seen_at, last_seen_at and apply method. NULL means no snapshot has been taken, never "no risk".
	GhostRiskScore             *float32
	ContentHash                []byte
	Simhash                    *int64
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	StateEnteredAt             pgtype.Timestamptz
	IsManagement               bool
	NormalizationVersion       *string
	BlockKey                   *string
	MergedInto                 pgtype.UUID
	SweptAt                    pgtype.Timestamptz
	RepostCount                int32
	SourcePostedAtAtLastChange pgtype.Timestamptz
}

type OpportunityEmbedding struct {
	OpportunityID    pgtype.UUID
	EmbeddingModel   string
	EmbeddingVersion string
	EmbeddingDim     int32
	Embedding        pgvector.Vector
	CreatedAt        pgtype.Timestamptz
}

type OpportunityMerge struct {
	ID                pgtype.UUID
	FromOpportunityID pgtype.UUID
	IntoOpportunityID pgtype.UUID
	Reason            string
	Confidence        *float32
	SourceRowsMoved   int32
	MergedBy          string
	MergedAt          pgtype.Timestamptz
	UndoneAt          pgtype.Timestamptz
}

type OpportunitySkill struct {
	OpportunityID        pgtype.UUID
	SkillID              pgtype.UUID
	RequirementLevel     string
	ExtractionConfidence *float32
	OntologyVersion      string
	ModelID              *string
	PromptVersion        *string
	CreatedAt            pgtype.Timestamptz
}

type OpportunitySource struct {
	ID              pgtype.UUID
	OpportunityID   pgtype.UUID
	SourceID        pgtype.UUID
	SourceJobID     string
	AtsType         *string
	AtsJobID        *string
	ApplyUrl        *string
	RawObjectKey    *string
	ContentHash     []byte
	Simhash         *int64
	FirstSeenAt     pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
	Etag            *string
	MergeReason     *string
	MergeConfidence *float32
	MergedBy        *string
	CreatedAt       pgtype.Timestamptz
}

type RefreshToken struct {
	ID         pgtype.UUID
	FamilyID   pgtype.UUID
	UserID     pgtype.UUID
	SessionID  pgtype.UUID
	TokenHash  []byte
	UsedAt     pgtype.Timestamptz
	ReplacedBy pgtype.UUID
	RevokedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Skill struct {
	ID              pgtype.UUID
	CanonicalSlug   string
	DisplayName     string
	ExternalRef     *string
	OntologyVersion string
	CreatedAt       pgtype.Timestamptz
}

type SkillAlias struct {
	SkillID pgtype.UUID
	Alias   string
}

type SkillDemandDaily struct {
	SkillID      pgtype.UUID
	Day          pgtype.Date
	Country      string
	WorkMode     string
	PostingCount int32
}

type SkillEdge struct {
	FromSkillID pgtype.UUID
	ToSkillID   pgtype.UUID
	Relation    string
}

type Source struct {
	ID              pgtype.UUID
	Name            string
	Tier            string
	Type            string
	LegalBasis      string
	RobotsCheckedAt pgtype.Timestamptz
	TermsReviewedAt pgtype.Timestamptz
	ReviewedBy      *string
	RateLimitRps    pgtype.Numeric
	PollInterval    pgtype.Interval
	EtagSupported   bool
	Status          string
	LastSuccessAt   pgtype.Timestamptz
	LastFailureAt   pgtype.Timestamptz
	LastError       *string
	ItemsDiscovered int64
	ItemsProcessed  int64
	ParseYield7d    pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type SourceSchedule struct {
	SourceID   pgtype.UUID
	NextRunAt  pgtype.Timestamptz
	LeaseUntil pgtype.Timestamptz
	LastRunAt  pgtype.Timestamptz
	Cursor     []byte
	UpdatedAt  pgtype.Timestamptz
}

type Tenant struct {
	ID          pgtype.UUID
	Kind        string
	DisplayName *string
	CreatedAt   pgtype.Timestamptz
}

type UserSession struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	UserAgent  *string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type UserToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Purpose    string
	TokenHash  []byte
	ConsumedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}
