// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceState = `-- name: AdvanceState :execrows
UPDATE opportunity
   SET pipeline_state = $1,
       version        = version + 1,
       lease_until    = NULL,
       attempts       = 0,
       last_error     = NULL,
       next_attempt_at = now()
 WHERE id = $2
   AND version = $3
   AND pipeline_state = $4
`

type AdvanceStateParams struct {
	NextState    string
	ID           pgtype.UUID
	Version      int32
	CurrentState string
}

// Optimistic concurrency: the version must match what the worker read. Zero rows
// affected means another stage wrote first, so the caller reloads and retries
// rather than clobbering.
func (q *Queries) AdvanceState(ctx context.Context, arg AdvanceStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceState,
		arg.NextState,
		arg.ID,
		arg.Version,
		arg.CurrentState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimBatch = `-- name: ClaimBatch :many
UPDATE opportunity
   SET lease_until = now() + $1::interval,
       attempts    = attempts + 1
 WHERE id IN (
   SELECT o.id FROM opportunity o
    WHERE o.pipeline_state = $2
      -- A merged row has left the pipeline: it is represented by its canonical
      -- row and must never be claimed or swept again.
      AND o.merged_into IS NULL
      AND o.next_attempt_at <= now()
      AND (o.lease_until IS NULL OR o.lease_until < now())
    ORDER BY o.next_attempt_at
    FOR UPDATE SKIP LOCKED
    LIMIT $3::int
 )
 RETURNING id, version, attempts, pipeline_state
`

type ClaimBatchParams struct {
	Lease pgtype.Interval
	State string
	Batch int32
}

type ClaimBatchRow struct {
	ID            pgtype.UUID
	Version       int32
	Attempts      int32
	PipelineState string
}

// FOR UPDATE SKIP LOCKED is what makes this safe with N workers and no
// coordinator: each worker skips rows another has locked instead of blocking.
//
// The lease means a hard-killed worker self-heals: once lease_until passes, the
// row becomes claimable again without any cleanup step.
func (q *Queries) ClaimBatch(ctx context.Context, arg ClaimBatchParams) ([]ClaimBatchRow, error) {
	rows, err := q.db.Query(ctx, claimBatch, arg.Lease, arg.State, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimBatchRow
	for rows.Next() {
		var i ClaimBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Attempts,
			&i.PipelineState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOpportunity = `-- name: CreateOpportunity :one
INSERT INTO opportunity (company_id, title_raw, title_normalized, pipeline_state, content_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, company_id, title_raw, title_normalized, role_family, seniority_ordinal, description_text, description_html_key, employment_type, work_mode, remote_geo_scope, remote_timezone_min, remote_timezone_max, location_country, location_region, location_city, location_lat, location_lon, location_timezone, language, salary_min_minor, salary_max_minor, salary_currency, salary_period, salary_is_estimated, fx_rate_date, visa_sponsorship, apply_method, ats_type, first_seen_at, last_seen_at, source_reported_posted_at, closed_at, close_reason, consecutive_misses, liveness_checked_at, pipeline_state, attempts, last_error, next_attempt_at, lease_until, version, quality_score, ghost_risk_score, content_hash, simhash, created_at, updated_at, state_entered_at, is_management, normalization_version, block_key, merged_into, swept_at, repost_count, source_posted_at_at_last_change, extraction_content_hash, enriched_at, extraction_error, unmerged_at
`

type CreateOpportunityParams struct {
	CompanyID       pgtype.UUID
	TitleRaw        string
	TitleNormalized string
	PipelineState   string
	ContentHash     []byte
}

func (q *Queries) CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, createOpportunity,
		arg.CompanyID,
		arg.TitleRaw,
		arg.TitleNormalized,
		arg.PipelineState,
		arg.ContentHash,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.TitleRaw,
		&i.TitleNormalized,
		&i.RoleFamily,
		&i.SeniorityOrdinal,
		&i.DescriptionText,
		&i.DescriptionHtmlKey,
		&i.EmploymentType,
		&i.WorkMode,
		&i.RemoteGeoScope,
		&i.RemoteTimezoneMin,
		&i.RemoteTimezoneMax,
		&i.LocationCountry,
		&i.LocationRegion,
		&i.LocationCity,
		&i.LocationLat,
		&i.LocationLon,
		&i.LocationTimezone,
		&i.Language,
		&i.SalaryMinMinor,
		&i.SalaryMaxMinor,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryIsEstimated,
		&i.FxRateDate,
		&i.VisaSponsorship,
		&i.ApplyMethod,
		&i.AtsType,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.SourceReportedPostedAt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.ConsecutiveMisses,
		&i.LivenessCheckedAt,
		&i.PipelineState,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.Version,
		&i.QualityScore,
		&i.GhostRiskScore,
		&i.ContentHash,
		&i.Simhash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateEnteredAt,
		&i.IsManagement,
		&i.NormalizationVersion,
		&i.BlockKey,
		&i.MergedInto,
		&i.SweptAt,
		&i.RepostCount,
		&i.SourcePostedAtAtLastChange,
		&i.ExtractionContentHash,
		&i.EnrichedAt,
		&i.ExtractionError,
		&i.UnmergedAt,
	)
	return i, err
}

const deferItem = `-- name: DeferItem :exec
UPDATE opportunity
   SET next_attempt_at = now() + $1::interval,
       lease_until = NULL,
       attempts = GREATEST(attempts - 1, 0)
 WHERE id = $2
`

type DeferItemParams struct {
	Delay pgtype.Interval
	ID    pgtype.UUID
}

// Put an item back WITHOUT spending an attempt. ClaimBatch already incremented
// attempts on the way in, so it is decremented here: a systemic failure must not
// consume a budget that exists for individually-bad records.
func (q *Queries) DeferItem(ctx context.Context, arg DeferItemParams) error {
	_, err := q.db.Exec(ctx, deferItem, arg.Delay, arg.ID)
	return err
}

const deleteOpportunitiesForCompany = `-- name: DeleteOpportunitiesForCompany :execrows
DELETE FROM opportunity WHERE company_id = $1
`

func (q *Queries) DeleteOpportunitiesForCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOpportunitiesForCompany, companyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAttempt = `-- name: FailAttempt :execrows
UPDATE opportunity
   SET last_error      = $1,
       lease_until     = NULL,
       next_attempt_at = now() + $2::interval,
       pipeline_state  = CASE WHEN attempts >= $3::int
                              THEN 'failed_permanent'
                              ELSE pipeline_state END
 WHERE id = $4
`

type FailAttemptParams struct {
	Err         *string
	Backoff     pgtype.Interval
	MaxAttempts int32
	ID          pgtype.UUID
}

// Backoff, then park. A parked record is visible in a queue; a lost one is not.
func (q *Queries) FailAttempt(ctx context.Context, arg FailAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAttempt,
		arg.Err,
		arg.Backoff,
		arg.MaxAttempts,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOpportunityState = `-- name: GetOpportunityState :one
SELECT id, pipeline_state, version, attempts, last_error, lease_until, next_attempt_at
  FROM opportunity WHERE id = $1
`

type GetOpportunityStateRow struct {
	ID            pgtype.UUID
	PipelineState string
	Version       int32
	Attempts      int32
	LastError     *string
	LeaseUntil    pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) GetOpportunityState(ctx context.Context, id pgtype.UUID) (GetOpportunityStateRow, error) {
	row := q.db.QueryRow(ctx, getOpportunityState, id)
	var i GetOpportunityStateRow
	err := row.Scan(
		&i.ID,
		&i.PipelineState,
		&i.Version,
		&i.Attempts,
		&i.LastError,
		&i.LeaseUntil,
		&i.NextAttemptAt,
	)
	return i, err
}

const pipelineStats = `-- name: PipelineStats :many
SELECT pipeline_state, count(*) AS total, min(state_entered_at) AS oldest
  FROM opportunity
 WHERE merged_into IS NULL
 GROUP BY pipeline_state
 ORDER BY pipeline_state
`

type PipelineStatsRow struct {
	PipelineState string
	Total         int64
	Oldest        interface{}
}

// The pipeline dashboard. An old min(updated_at) in any row means something is
// stranded — alert on it.
func (q *Queries) PipelineStats(ctx context.Context) ([]PipelineStatsRow, error) {
	rows, err := q.db.Query(ctx, pipelineStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineStatsRow
	for rows.Next() {
		var i PipelineStatsRow
		if err := rows.Scan(&i.PipelineState, &i.Total, &i.Oldest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseClaim = `-- name: ReleaseClaim :exec
UPDATE opportunity
   SET lease_until = NULL, attempts = GREATEST(attempts - 1, 0)
 WHERE id = $1 AND lease_until IS NOT NULL
`

// Called on graceful shutdown so a clean deploy is fast instead of waiting out
// the lease. The lease is the safety net; this is the courtesy.
func (q *Queries) ReleaseClaim(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseClaim, id)
	return err
}

const requeueStranded = `-- name: RequeueStranded :execrows
UPDATE opportunity
   SET next_attempt_at = now(), lease_until = NULL, swept_at = now()
 WHERE id = ANY($1::uuid[])
`

func (q *Queries) RequeueStranded(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStranded, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepStranded = `-- name: SweepStranded :many
SELECT id, pipeline_state, attempts, state_entered_at
  FROM opportunity
 WHERE pipeline_state NOT IN ('ready','failed_permanent')
   AND merged_into IS NULL
   AND (lease_until IS NULL OR lease_until < now())
   AND state_entered_at < now() - $1::interval
 -- swept_at is the progress cursor: never-swept rows first, so a backlog larger
 -- than one batch is worked through instead of the same head being requeued.
 ORDER BY swept_at NULLS FIRST, state_entered_at
 LIMIT $2::int
`

type SweepStrandedParams struct {
	Threshold pgtype.Interval
	Batch     int32
}

type SweepStrandedRow struct {
	ID             pgtype.UUID
	PipelineState  string
	Attempts       int32
	StateEnteredAt pgtype.Timestamptz
}

// Anything sitting in a non-terminal state past its threshold with no live
// lease. This is the query that turns a lost event into latency instead of
// silent data loss.
func (q *Queries) SweepStranded(ctx context.Context, arg SweepStrandedParams) ([]SweepStrandedRow, error) {
	rows, err := q.db.Query(ctx, sweepStranded, arg.Threshold, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweepStrandedRow
	for rows.Next() {
		var i SweepStrandedRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineState,
			&i.Attempts,
			&i.StateEnteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
