// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe.sql

package store

import (
	"context"
)

const probeCountCompanies = `-- name: ProbeCountCompanies :one
SELECT count(*) FROM company
`

func (q *Queries) ProbeCountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, probeCountCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}
