// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const anonymizeUserFlags = `-- name: AnonymizeUserFlags :execrows
UPDATE opportunity_flag SET reported_by = NULL
 WHERE reported_by = $1
`

// Erasure. A flag is about the POSTING, not the reporter, so the report survives
// with its author removed rather than being deleted.
//
// Done explicitly rather than left to the ON DELETE SET NULL cascade, so the
// erasure report can state a count for it. A scam report vanishing because
// someone closed their account would be the wrong trade — the listing is still
// a problem for everyone else.
func (q *Queries) AnonymizeUserFlags(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, anonymizeUserFlags, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeErasureRequest = `-- name: CompleteErasureRequest :exec
UPDATE erasure_request SET completed_at = now()
 WHERE id = $1
   AND NOT EXISTS (
     SELECT 1 FROM erasure_step
      WHERE request_id = $1
        AND status NOT IN ('done','not_applicable'))
`

// Only when every step succeeded. A partial erasure must stay visibly
// incomplete rather than being marked done.
func (q *Queries) CompleteErasureRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeErasureRequest, id)
	return err
}

const countUserTraces = `-- name: CountUserTraces :one
SELECT (SELECT count(*) FROM profile p        WHERE p.user_id  = $1)
     + (SELECT count(*) FROM profile_skill ps WHERE ps.user_id = $1)
     + (SELECT count(*) FROM profile_embedding pe WHERE pe.user_id = $1)
     + (SELECT count(*) FROM fit_score fsc WHERE fsc.user_id = $1)
     + (SELECT count(*) FROM eligibility_result er WHERE er.user_id = $1)
     + (SELECT count(*) FROM engagement_event ee WHERE ee.user_id = $1)
     + (SELECT count(*) FROM resume r         WHERE r.user_id  = $1)
     -- Step 18. A notification setting holds a timezone and quiet hours; a
     -- digest_send row records which postings were mailed to this person and
     -- when. Both cascade from app_user, but a cascade is not a verification:
     -- this count is what makes the erasure guarantee checkable rather than
     -- assumed, and a table missing from HERE is the specific way a derived
     -- artifact gets quietly left behind.
     + (SELECT count(*) FROM notification_setting ns WHERE ns.user_id = $1)
     + (SELECT count(*) FROM digest_send ds  WHERE ds.user_id = $1)
     + (SELECT count(*) FROM user_session us  WHERE us.user_id = $1)
     + (SELECT count(*) FROM refresh_token rt WHERE rt.user_id = $1)
     + (SELECT count(*) FROM user_token ut    WHERE ut.user_id = $1)
     + (SELECT count(*) FROM app_user au      WHERE au.id      = $1)
       AS traces
`

// Verification: after erasure this must be zero everywhere. Counting rather than
// trusting the deletes is what makes the guarantee checkable.
// Every column is table-qualified: unqualified user_id across seven subqueries
// is ambiguous to the planner.
func (q *Queries) CountUserTraces(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUserTraces, userID)
	var traces int32
	err := row.Scan(&traces)
	return traces, err
}

const createErasureRequest = `-- name: CreateErasureRequest :one

INSERT INTO erasure_request (user_id) VALUES ($1) RETURNING id, user_id, requested_at, completed_at
`

// ---------------------------------------------------------------- erasure
func (q *Queries) CreateErasureRequest(ctx context.Context, userID pgtype.UUID) (ErasureRequest, error) {
	row := q.db.QueryRow(ctx, createErasureRequest, userID)
	var i ErasureRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createResume = `-- name: CreateResume :one
INSERT INTO resume (user_id, object_key, filename, content_type, size_bytes, sha256)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, user_id, object_key, text_object_key, filename, content_type, size_bytes, sha256, text_chars, parse_state, parse_error, uploaded_at, deleted_at, skills_extracted_at, skills_model_id, skills_prompt_version, skills_schema_version, skills_redaction_version, skills_field_set, skills_redacted_chars, skills_sent_chars, skills_found, skills_resolved, skills_years_claimed, skills_seniority_claimed
`

type CreateResumeParams struct {
	UserID      pgtype.UUID
	ObjectKey   string
	Filename    *string
	ContentType *string
	SizeBytes   int64
	Sha256      []byte
}

func (q *Queries) CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error) {
	row := q.db.QueryRow(ctx, createResume,
		arg.UserID,
		arg.ObjectKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.TextObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.TextChars,
		&i.ParseState,
		&i.ParseError,
		&i.UploadedAt,
		&i.DeletedAt,
		&i.SkillsExtractedAt,
		&i.SkillsModelID,
		&i.SkillsPromptVersion,
		&i.SkillsSchemaVersion,
		&i.SkillsRedactionVersion,
		&i.SkillsFieldSet,
		&i.SkillsRedactedChars,
		&i.SkillsSentChars,
		&i.SkillsFound,
		&i.SkillsResolved,
		&i.SkillsYearsClaimed,
		&i.SkillsSeniorityClaimed,
	)
	return i, err
}

const deleteManualProfileSkills = `-- name: DeleteManualProfileSkills :execrows
DELETE FROM profile_skill WHERE user_id = $1 AND origin = 'manual'
`

// Clears only the skills the USER typed, leaving resume- and github-derived ones
// intact. A manual edit means "this is my list of what I claim by hand", not
// "discard everything we inferred from my documents" — and the origin column
// exists precisely so the two can be told apart.
func (q *Queries) DeleteManualProfileSkills(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManualProfileSkills, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileData = `-- name: DeleteProfileData :execrows
DELETE FROM profile WHERE user_id = $1
`

func (q *Queries) DeleteProfileData(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileData, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileEmbedding = `-- name: DeleteProfileEmbedding :execrows
DELETE FROM profile_embedding WHERE user_id = $1
`

// Erasure. The app_user cascade would remove these anyway, but an enumerated
// delete is what lets the report state a count for this store instead of
// attributing it to the user row.
func (q *Queries) DeleteProfileEmbedding(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileEmbedding, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileSkill = `-- name: DeleteProfileSkill :exec
DELETE FROM profile_skill WHERE user_id = $1 AND skill_id = $2
`

type DeleteProfileSkillParams struct {
	UserID  pgtype.UUID
	SkillID pgtype.UUID
}

func (q *Queries) DeleteProfileSkill(ctx context.Context, arg DeleteProfileSkillParams) error {
	_, err := q.db.Exec(ctx, deleteProfileSkill, arg.UserID, arg.SkillID)
	return err
}

const deleteProfileSkills = `-- name: DeleteProfileSkills :execrows
DELETE FROM profile_skill WHERE user_id = $1
`

func (q *Queries) DeleteProfileSkills(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileSkills, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteResumeOriginSkills = `-- name: DeleteResumeOriginSkills :execrows
DELETE FROM profile_skill WHERE user_id = $1 AND origin = 'resume'
`

// Clears skills this user's RESUMES contributed, leaving manual ones intact.
//
// The mirror of DeleteManualProfileSkills. Re-extracting a resume must replace
// what that resume claimed without discarding what the person typed by hand — a
// manual entry is a stated claim and a resume reading is evidence, and evidence
// being refreshed is not a reason to drop the claim.
func (q *Queries) DeleteResumeOriginSkills(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResumeOriginSkills, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteResumeRows = `-- name: DeleteResumeRows :execrows
DELETE FROM resume WHERE user_id = $1
`

func (q *Queries) DeleteResumeRows(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResumeRows, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :execrows
DELETE FROM refresh_token WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserRow = `-- name: DeleteUserRow :execrows
DELETE FROM app_user WHERE id = $1
`

func (q *Queries) DeleteUserRow(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserRow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM user_session WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserTokens = `-- name: DeleteUserTokens :execrows
DELETE FROM user_token WHERE user_id = $1
`

func (q *Queries) DeleteUserTokens(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failResume = `-- name: FailResume :exec
UPDATE resume SET parse_state = 'failed', parse_error = $2 WHERE id = $1
`

type FailResumeParams struct {
	ID         pgtype.UUID
	ParseError *string
}

func (q *Queries) FailResume(ctx context.Context, arg FailResumeParams) error {
	_, err := q.db.Exec(ctx, failResume, arg.ID, arg.ParseError)
	return err
}

const getErasureRequest = `-- name: GetErasureRequest :one
SELECT id, user_id, requested_at, completed_at FROM erasure_request WHERE id = $1
`

func (q *Queries) GetErasureRequest(ctx context.Context, id pgtype.UUID) (ErasureRequest, error) {
	row := q.db.QueryRow(ctx, getErasureRequest, id)
	var i ErasureRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, tenant_id, headline, years_experience, seniority_ordinal, is_management, target_role_families, target_countries, work_mode_preference, languages, min_salary_minor, salary_currency, salary_period, work_authorization, profile_version, created_at, updated_at, target_employment_types FROM profile WHERE user_id = $1
`

func (q *Queries) GetProfile(ctx context.Context, userID pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Headline,
		&i.YearsExperience,
		&i.SeniorityOrdinal,
		&i.IsManagement,
		&i.TargetRoleFamilies,
		&i.TargetCountries,
		&i.WorkModePreference,
		&i.Languages,
		&i.MinSalaryMinor,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.WorkAuthorization,
		&i.ProfileVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetEmploymentTypes,
	)
	return i, err
}

const getProfileEmbedding = `-- name: GetProfileEmbedding :one
SELECT pe.embedding, pe.embedding_model, pe.profile_version AS embedded_profile_version,
       p.profile_version AS current_profile_version
  FROM profile_embedding pe
  JOIN profile p ON p.user_id = pe.user_id
 WHERE pe.user_id = $1
   AND pe.embedding_version = $2
`

type GetProfileEmbeddingParams struct {
	UserID           pgtype.UUID
	EmbeddingVersion string
}

type GetProfileEmbeddingRow struct {
	Embedding              pgvector.Vector
	EmbeddingModel         string
	EmbeddedProfileVersion int32
	CurrentProfileVersion  int32
}

// Returns the vector with the profile version it was built from, so the caller
// can tell a current vector from one that predates the latest profile edit.
func (q *Queries) GetProfileEmbedding(ctx context.Context, arg GetProfileEmbeddingParams) (GetProfileEmbeddingRow, error) {
	row := q.db.QueryRow(ctx, getProfileEmbedding, arg.UserID, arg.EmbeddingVersion)
	var i GetProfileEmbeddingRow
	err := row.Scan(
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddedProfileVersion,
		&i.CurrentProfileVersion,
	)
	return i, err
}

const getResume = `-- name: GetResume :one
SELECT id, user_id, object_key, text_object_key, filename, content_type, size_bytes, sha256, text_chars, parse_state, parse_error, uploaded_at, deleted_at, skills_extracted_at, skills_model_id, skills_prompt_version, skills_schema_version, skills_redaction_version, skills_field_set, skills_redacted_chars, skills_sent_chars, skills_found, skills_resolved, skills_years_claimed, skills_seniority_claimed FROM resume WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetResume(ctx context.Context, id pgtype.UUID) (Resume, error) {
	row := q.db.QueryRow(ctx, getResume, id)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.TextObjectKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.TextChars,
		&i.ParseState,
		&i.ParseError,
		&i.UploadedAt,
		&i.DeletedAt,
		&i.SkillsExtractedAt,
		&i.SkillsModelID,
		&i.SkillsPromptVersion,
		&i.SkillsSchemaVersion,
		&i.SkillsRedactionVersion,
		&i.SkillsFieldSet,
		&i.SkillsRedactedChars,
		&i.SkillsSentChars,
		&i.SkillsFound,
		&i.SkillsResolved,
		&i.SkillsYearsClaimed,
		&i.SkillsSeniorityClaimed,
	)
	return i, err
}

const getResumeSkillProvenance = `-- name: GetResumeSkillProvenance :one
SELECT r.id, r.filename, r.skills_extracted_at, r.skills_model_id,
       r.skills_redaction_version, r.skills_field_set,
       r.skills_found, r.skills_resolved,
       r.skills_years_claimed, r.skills_seniority_claimed
  FROM resume r
 WHERE r.user_id = $1 AND r.deleted_at IS NULL
   AND r.skills_extracted_at IS NOT NULL
 ORDER BY r.skills_extracted_at DESC
 LIMIT 1
`

type GetResumeSkillProvenanceRow struct {
	ID                     pgtype.UUID
	Filename               *string
	SkillsExtractedAt      pgtype.Timestamptz
	SkillsModelID          *string
	SkillsRedactionVersion *string
	SkillsFieldSet         *string
	SkillsFound            *int32
	SkillsResolved         *int32
	SkillsYearsClaimed     *int16
	SkillsSeniorityClaimed *string
}

// What a user can be told about their own resume extraction.
func (q *Queries) GetResumeSkillProvenance(ctx context.Context, userID pgtype.UUID) (GetResumeSkillProvenanceRow, error) {
	row := q.db.QueryRow(ctx, getResumeSkillProvenance, userID)
	var i GetResumeSkillProvenanceRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.SkillsExtractedAt,
		&i.SkillsModelID,
		&i.SkillsRedactionVersion,
		&i.SkillsFieldSet,
		&i.SkillsFound,
		&i.SkillsResolved,
		&i.SkillsYearsClaimed,
		&i.SkillsSeniorityClaimed,
	)
	return i, err
}

const listAllUserResumeKeys = `-- name: ListAllUserResumeKeys :many
SELECT object_key, text_object_key FROM resume WHERE user_id = $1
`

type ListAllUserResumeKeysRow struct {
	ObjectKey     string
	TextObjectKey *string
}

// Includes soft-deleted rows: erasure must remove objects for resumes the user
// already asked to delete, not just the live ones.
func (q *Queries) ListAllUserResumeKeys(ctx context.Context, userID pgtype.UUID) ([]ListAllUserResumeKeysRow, error) {
	rows, err := q.db.Query(ctx, listAllUserResumeKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUserResumeKeysRow
	for rows.Next() {
		var i ListAllUserResumeKeysRow
		if err := rows.Scan(&i.ObjectKey, &i.TextObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErasureSteps = `-- name: ListErasureSteps :many
SELECT location, status, items, detail FROM erasure_step
 WHERE request_id = $1 ORDER BY location
`

type ListErasureStepsRow struct {
	Location string
	Status   string
	Items    int32
	Detail   *string
}

func (q *Queries) ListErasureSteps(ctx context.Context, requestID pgtype.UUID) ([]ListErasureStepsRow, error) {
	rows, err := q.db.Query(ctx, listErasureSteps, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListErasureStepsRow
	for rows.Next() {
		var i ListErasureStepsRow
		if err := rows.Scan(
			&i.Location,
			&i.Status,
			&i.Items,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileSkills = `-- name: ListProfileSkills :many
SELECT ps.skill_id, ps.origin, ps.proficiency, ps.years,
       s.canonical_slug, s.display_name
  FROM profile_skill ps
  JOIN skill s ON s.id = ps.skill_id
 WHERE ps.user_id = $1
 ORDER BY s.display_name
`

type ListProfileSkillsRow struct {
	SkillID       pgtype.UUID
	Origin        string
	Proficiency   *int16
	Years         *int16
	CanonicalSlug string
	DisplayName   string
}

func (q *Queries) ListProfileSkills(ctx context.Context, userID pgtype.UUID) ([]ListProfileSkillsRow, error) {
	rows, err := q.db.Query(ctx, listProfileSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileSkillsRow
	for rows.Next() {
		var i ListProfileSkillsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.Origin,
			&i.Proficiency,
			&i.Years,
			&i.CanonicalSlug,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserResumes = `-- name: ListUserResumes :many
SELECT id, user_id, object_key, text_object_key, filename, content_type, size_bytes, sha256, text_chars, parse_state, parse_error, uploaded_at, deleted_at, skills_extracted_at, skills_model_id, skills_prompt_version, skills_schema_version, skills_redaction_version, skills_field_set, skills_redacted_chars, skills_sent_chars, skills_found, skills_resolved, skills_years_claimed, skills_seniority_claimed FROM resume WHERE user_id = $1 AND deleted_at IS NULL ORDER BY uploaded_at DESC
`

func (q *Queries) ListUserResumes(ctx context.Context, userID pgtype.UUID) ([]Resume, error) {
	rows, err := q.db.Query(ctx, listUserResumes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resume
	for rows.Next() {
		var i Resume
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.TextObjectKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.TextChars,
			&i.ParseState,
			&i.ParseError,
			&i.UploadedAt,
			&i.DeletedAt,
			&i.SkillsExtractedAt,
			&i.SkillsModelID,
			&i.SkillsPromptVersion,
			&i.SkillsSchemaVersion,
			&i.SkillsRedactionVersion,
			&i.SkillsFieldSet,
			&i.SkillsRedactedChars,
			&i.SkillsSentChars,
			&i.SkillsFound,
			&i.SkillsResolved,
			&i.SkillsYearsClaimed,
			&i.SkillsSeniorityClaimed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileSkillByAlias = `-- name: ProfileSkillByAlias :one
SELECT s.id, s.canonical_slug::text AS slug, s.display_name
  FROM skill_alias a JOIN skill s ON s.id = a.skill_id
 WHERE a.alias = $1::citext
 LIMIT 1
`

type ProfileSkillByAliasRow struct {
	ID          pgtype.UUID
	Slug        string
	DisplayName string
}

// Resolves a user-typed skill name against the ontology.
//
// Alias-only, with NO create path, and that asymmetry with extraction is
// deliberate. An extracted phrase is evidence from a posting and is worth
// keeping even unrecognised; a user's typo is not evidence of anything, and
// letting the profile mint skills would fill the vocabulary with one-off spellings
// that then never match a posting. Unrecognised input is reported back to the
// user instead.
func (q *Queries) ProfileSkillByAlias(ctx context.Context, alias string) (ProfileSkillByAliasRow, error) {
	row := q.db.QueryRow(ctx, profileSkillByAlias, alias)
	var i ProfileSkillByAliasRow
	err := row.Scan(&i.ID, &i.Slug, &i.DisplayName)
	return i, err
}

const putProfileEmbedding = `-- name: PutProfileEmbedding :exec
INSERT INTO profile_embedding (
    user_id, embedding_model, embedding_version, embedding_dim, embedding, profile_version
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (user_id, embedding_version) DO UPDATE
   SET embedding       = excluded.embedding,
       embedding_model = excluded.embedding_model,
       embedding_dim   = excluded.embedding_dim,
       profile_version = excluded.profile_version,
       updated_at      = now()
`

type PutProfileEmbeddingParams struct {
	UserID           pgtype.UUID
	EmbeddingModel   string
	EmbeddingVersion string
	EmbeddingDim     int32
	Embedding        pgvector.Vector
	ProfileVersion   int32
}

// Upsert per (user, version) so a profile edit refreshes the vector in place and
// a version migration can dual-write.
func (q *Queries) PutProfileEmbedding(ctx context.Context, arg PutProfileEmbeddingParams) error {
	_, err := q.db.Exec(ctx, putProfileEmbedding,
		arg.UserID,
		arg.EmbeddingModel,
		arg.EmbeddingVersion,
		arg.EmbeddingDim,
		arg.Embedding,
		arg.ProfileVersion,
	)
	return err
}

const recordErasureStep = `-- name: RecordErasureStep :exec
INSERT INTO erasure_step (request_id, location, status, items, detail, completed_at)
VALUES ($1,$2,$3,$4,$5, now())
ON CONFLICT (request_id, location) DO UPDATE SET
    status = EXCLUDED.status, items = EXCLUDED.items,
    detail = EXCLUDED.detail, completed_at = now()
`

type RecordErasureStepParams struct {
	RequestID pgtype.UUID
	Location  string
	Status    string
	Items     int32
	Detail    *string
}

func (q *Queries) RecordErasureStep(ctx context.Context, arg RecordErasureStepParams) error {
	_, err := q.db.Exec(ctx, recordErasureStep,
		arg.RequestID,
		arg.Location,
		arg.Status,
		arg.Items,
		arg.Detail,
	)
	return err
}

const recordResumeSkillExtraction = `-- name: RecordResumeSkillExtraction :exec
UPDATE resume
   SET skills_extracted_at      = now(),
       skills_model_id          = $1,
       skills_prompt_version    = $2,
       skills_schema_version    = $3,
       skills_redaction_version = $4,
       skills_field_set         = $5,
       skills_redacted_chars    = $6,
       skills_sent_chars        = $7,
       skills_found             = $8,
       skills_resolved          = $9,
       skills_years_claimed     = $10,
       skills_seniority_claimed = $11
 WHERE id = $12
`

type RecordResumeSkillExtractionParams struct {
	ModelID          *string
	PromptVersion    *string
	SchemaVersion    *string
	RedactionVersion *string
	FieldSet         *string
	RedactedChars    *int32
	SentChars        *int32
	SkillsFound      *int32
	SkillsResolved   *int32
	YearsClaimed     *int16
	SeniorityClaimed *string
	ID               pgtype.UUID
}

// Stamps what was sent, to whom, and what came back.
//
// The counts are counts, never values. "3 email addresses removed" is auditable;
// the addresses themselves would put the PII back into the record we keep to
// prove we did not retain it.
func (q *Queries) RecordResumeSkillExtraction(ctx context.Context, arg RecordResumeSkillExtractionParams) error {
	_, err := q.db.Exec(ctx, recordResumeSkillExtraction,
		arg.ModelID,
		arg.PromptVersion,
		arg.SchemaVersion,
		arg.RedactionVersion,
		arg.FieldSet,
		arg.RedactedChars,
		arg.SentChars,
		arg.SkillsFound,
		arg.SkillsResolved,
		arg.YearsClaimed,
		arg.SeniorityClaimed,
		arg.ID,
	)
	return err
}

const resumesNeedingSkills = `-- name: ResumesNeedingSkills :many
SELECT r.id, r.user_id, r.text_object_key, r.skills_extracted_at
  FROM resume r
 -- 'text_extracted' is the state a successful upload reaches, not 'parsed'.
 -- The latter is reserved for a structured parse that does not exist yet, and
 -- filtering on it meant this query matched nothing at all — a batch that
 -- reports "nothing to do" for every resume is indistinguishable from one that
 -- is working.
 WHERE r.parse_state IN ('text_extracted', 'parsed')
   AND r.deleted_at IS NULL
   AND r.text_object_key IS NOT NULL
   AND (r.skills_extracted_at IS NULL
        OR r.skills_prompt_version IS DISTINCT FROM $1::text
        OR r.skills_model_id IS DISTINCT FROM $2::text
        OR r.skills_redaction_version IS DISTINCT FROM $3::text)
 ORDER BY r.uploaded_at DESC
 LIMIT $4::int
`

type ResumesNeedingSkillsParams struct {
	PromptVersion    string
	ModelID          string
	RedactionVersion string
	MaxRows          int32
}

type ResumesNeedingSkillsRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TextObjectKey     *string
	SkillsExtractedAt pgtype.Timestamptz
}

// Resumes whose text is parsed but whose skills have not been extracted, or were
// extracted under a superseded prompt, model or redaction version.
//
// The version comparison is the cache: a prompt change re-extracts, an unchanged
// prompt does not. Hard rule 8 applied to resumes — re-extracting under the same
// inputs would make a profile's skills flap for a document that did not change.
func (q *Queries) ResumesNeedingSkills(ctx context.Context, arg ResumesNeedingSkillsParams) ([]ResumesNeedingSkillsRow, error) {
	rows, err := q.db.Query(ctx, resumesNeedingSkills,
		arg.PromptVersion,
		arg.ModelID,
		arg.RedactionVersion,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResumesNeedingSkillsRow
	for rows.Next() {
		var i ResumesNeedingSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TextObjectKey,
			&i.SkillsExtractedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResumeText = `-- name: SetResumeText :exec
UPDATE resume
   SET text_object_key = $2, text_chars = $3, parse_state = 'text_extracted', parse_error = NULL
 WHERE id = $1
`

type SetResumeTextParams struct {
	ID            pgtype.UUID
	TextObjectKey *string
	TextChars     *int32
}

func (q *Queries) SetResumeText(ctx context.Context, arg SetResumeTextParams) error {
	_, err := q.db.Exec(ctx, setResumeText, arg.ID, arg.TextObjectKey, arg.TextChars)
	return err
}

const softDeleteResume = `-- name: SoftDeleteResume :exec
UPDATE resume SET deleted_at = now() WHERE id = $1 AND user_id = $2
`

type SoftDeleteResumeParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SoftDeleteResume(ctx context.Context, arg SoftDeleteResumeParams) error {
	_, err := q.db.Exec(ctx, softDeleteResume, arg.ID, arg.UserID)
	return err
}

const touchProfileVersion = `-- name: TouchProfileVersion :exec
UPDATE profile SET updated_at = now() WHERE user_id = $1
`

// Skills live in their own table, so editing them does not fire the profile
// trigger. Called explicitly, because a skill change absolutely can move a fit
// score and a stale cached score is worse than a slow one.
func (q *Queries) TouchProfileVersion(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchProfileVersion, userID)
	return err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profile (
    user_id, tenant_id, headline, years_experience, seniority_ordinal, is_management,
    target_role_families, target_countries, work_mode_preference, languages,
    min_salary_minor, salary_currency, salary_period, work_authorization,
    target_employment_types
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
ON CONFLICT (user_id) DO UPDATE SET
    headline             = EXCLUDED.headline,
    years_experience     = EXCLUDED.years_experience,
    seniority_ordinal    = EXCLUDED.seniority_ordinal,
    is_management        = EXCLUDED.is_management,
    target_role_families = EXCLUDED.target_role_families,
    target_countries     = EXCLUDED.target_countries,
    work_mode_preference = EXCLUDED.work_mode_preference,
    languages            = EXCLUDED.languages,
    min_salary_minor     = EXCLUDED.min_salary_minor,
    salary_currency      = EXCLUDED.salary_currency,
    salary_period        = EXCLUDED.salary_period,
    work_authorization   = EXCLUDED.work_authorization,
    target_employment_types = EXCLUDED.target_employment_types
RETURNING user_id, tenant_id, headline, years_experience, seniority_ordinal, is_management, target_role_families, target_countries, work_mode_preference, languages, min_salary_minor, salary_currency, salary_period, work_authorization, profile_version, created_at, updated_at, target_employment_types
`

type UpsertProfileParams struct {
	UserID                pgtype.UUID
	TenantID              pgtype.UUID
	Headline              *string
	YearsExperience       *int16
	SeniorityOrdinal      *int16
	IsManagement          bool
	TargetRoleFamilies    []string
	TargetCountries       []string
	WorkModePreference    *string
	Languages             []string
	MinSalaryMinor        *int64
	SalaryCurrency        *string
	SalaryPeriod          *string
	WorkAuthorization     []byte
	TargetEmploymentTypes []string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.TenantID,
		arg.Headline,
		arg.YearsExperience,
		arg.SeniorityOrdinal,
		arg.IsManagement,
		arg.TargetRoleFamilies,
		arg.TargetCountries,
		arg.WorkModePreference,
		arg.Languages,
		arg.MinSalaryMinor,
		arg.SalaryCurrency,
		arg.SalaryPeriod,
		arg.WorkAuthorization,
		arg.TargetEmploymentTypes,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Headline,
		&i.YearsExperience,
		&i.SeniorityOrdinal,
		&i.IsManagement,
		&i.TargetRoleFamilies,
		&i.TargetCountries,
		&i.WorkModePreference,
		&i.Languages,
		&i.MinSalaryMinor,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.WorkAuthorization,
		&i.ProfileVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetEmploymentTypes,
	)
	return i, err
}

const upsertProfileSkill = `-- name: UpsertProfileSkill :exec
INSERT INTO profile_skill (user_id, skill_id, origin, proficiency, years)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (user_id, skill_id) DO UPDATE SET
    -- A manual claim outranks a parsed one: the user typing it is stronger
    -- evidence than a parser guessing it from a document.
    origin      = CASE WHEN EXCLUDED.origin = 'manual' THEN 'manual' ELSE profile_skill.origin END,
    proficiency = COALESCE(EXCLUDED.proficiency, profile_skill.proficiency),
    years       = COALESCE(EXCLUDED.years, profile_skill.years)
`

type UpsertProfileSkillParams struct {
	UserID      pgtype.UUID
	SkillID     pgtype.UUID
	Origin      string
	Proficiency *int16
	Years       *int16
}

func (q *Queries) UpsertProfileSkill(ctx context.Context, arg UpsertProfileSkillParams) error {
	_, err := q.db.Exec(ctx, upsertProfileSkill,
		arg.UserID,
		arg.SkillID,
		arg.Origin,
		arg.Proficiency,
		arg.Years,
	)
	return err
}
