// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrieve.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const countEligibleOpportunities = `-- name: CountEligibleOpportunities :one
SELECT count(*)
  FROM opportunity o
 WHERE o.pipeline_state = 'ready'
   AND o.merged_into IS NULL
   AND o.closed_at IS NULL
   AND (cardinality($1::char(2)[]) = 0
        OR o.location_country = ANY ($1::char(2)[])
        OR o.work_mode = 'remote')
   AND ($2::text IS NULL
        OR o.work_mode = $2::text
        OR ($2::text = 'hybrid' AND o.work_mode = 'remote'))
   AND (cardinality($3::text[]) = 0
        OR o.employment_type IS NULL
        OR o.employment_type = ANY ($3::text[]))
   AND (cardinality($4::char(2)[]) = 0
        OR o.language IS NULL
        OR o.language = ANY ($4::char(2)[]))
   AND o.last_seen_at > now() - $5::interval
`

type CountEligibleOpportunitiesParams struct {
	Countries       []string
	WorkMode        *string
	EmploymentTypes []string
	Languages       []string
	MaxStaleness    pgtype.Interval
}

// The denominator for retrieval coverage (§21). Without it a channel returning
// 12 candidates is indistinguishable from a corpus that only holds 12 eligible
// postings, and silent under-return looks like a small market.
func (q *Queries) CountEligibleOpportunities(ctx context.Context, arg CountEligibleOpportunitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleOpportunities,
		arg.Countries,
		arg.WorkMode,
		arg.EmploymentTypes,
		arg.Languages,
		arg.MaxStaleness,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const retrieveByKeyword = `-- name: RetrieveByKeyword :many
SELECT o.id,
       o.title_raw,
       o.company_id,
       o.first_seen_at,
       ts_rank(to_tsvector('english', coalesce(o.title_normalized, '')),
               websearch_to_tsquery('english', $1::text))::double precision AS rank
  FROM opportunity o
 WHERE o.pipeline_state = 'ready'
   AND o.merged_into IS NULL
   AND o.closed_at IS NULL
   AND to_tsvector('english', coalesce(o.title_normalized, ''))
       @@ websearch_to_tsquery('english', $1::text)
   AND (cardinality($2::char(2)[]) = 0
        OR o.location_country = ANY ($2::char(2)[])
        OR o.work_mode = 'remote')
   AND ($3::text IS NULL
        OR o.work_mode = $3::text
        OR ($3::text = 'hybrid' AND o.work_mode = 'remote'))
   AND (cardinality($4::text[]) = 0
        OR o.employment_type IS NULL
        OR o.employment_type = ANY ($4::text[]))
   AND (cardinality($5::char(2)[]) = 0
        OR o.language IS NULL
        OR o.language = ANY ($5::char(2)[]))
   AND o.last_seen_at > now() - $6::interval
 ORDER BY rank DESC, o.first_seen_at DESC
 LIMIT $7
`

type RetrieveByKeywordParams struct {
	Terms           string
	Countries       []string
	WorkMode        *string
	EmploymentTypes []string
	Languages       []string
	MaxStaleness    pgtype.Interval
	MaxCandidates   int32
}

type RetrieveByKeywordRow struct {
	ID          pgtype.UUID
	TitleRaw    string
	CompanyID   pgtype.UUID
	FirstSeenAt pgtype.Timestamptz
	Rank        float64
}

// Channel 2: full-text recall on the user's target-role terms, over the TITLE.
//
// It exists because the vector channel and this one fail differently. A lexical
// embedding scores shared boilerplate as similarity, so a posting whose title
// carries the user's exact role words can still rank below unrelated postings
// from the same company; an exact term match on the title cannot miss it.
//
// Title only, deliberately. Measured on 199 real GitLab postings with the terms
// "backend OR platform": matching title plus description returned all 199,
// because the company names its own platform in every description. Matching the
// title returned 34, all genuine backend or platform roles. A channel that
// returns the whole corpus bounds nothing, and bounding is what stage 1 is for.
//
// Description text is not ignored by retrieval — the vector channel embeds it.
// The division of labour is deliberate: exact matching for the broad, boilerplate
// prone role words, and the vector for everything the description implies.
func (q *Queries) RetrieveByKeyword(ctx context.Context, arg RetrieveByKeywordParams) ([]RetrieveByKeywordRow, error) {
	rows, err := q.db.Query(ctx, retrieveByKeyword,
		arg.Terms,
		arg.Countries,
		arg.WorkMode,
		arg.EmploymentTypes,
		arg.Languages,
		arg.MaxStaleness,
		arg.MaxCandidates,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrieveByKeywordRow
	for rows.Next() {
		var i RetrieveByKeywordRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRaw,
			&i.CompanyID,
			&i.FirstSeenAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveByVector = `-- name: RetrieveByVector :many

SELECT o.id,
       o.title_raw,
       o.company_id,
       o.first_seen_at,
       -- Cast is load-bearing: without it sqlc cannot infer the operator's
       -- return type and emits interface{}.
       (e.embedding <=> $1::vector)::double precision AS distance
  FROM opportunity o
  JOIN opportunity_embedding e
    ON e.opportunity_id = o.id
   AND e.embedding_version = $2
 WHERE o.pipeline_state = 'ready'
   AND o.merged_into IS NULL
   AND o.closed_at IS NULL
   -- Empty array means the user set no constraint, which must not exclude
   -- everything. Postgres has no "match anything" array, so each predicate is
   -- written as "unconstrained OR matches".
   AND (cardinality($3::char(2)[]) = 0
        OR o.location_country = ANY ($3::char(2)[])
        -- A remote posting is not excluded by a country filter: its location is
        -- a formality, and dropping it would hide the roles remote-seeking users
        -- most want.
        OR o.work_mode = 'remote')
   AND ($4::text IS NULL
        OR o.work_mode = $4::text
        -- Asking for remote accepts hybrid; asking for hybrid does not accept
        -- onsite. The asymmetry is the point: hybrid is a superset of remote days.
        OR ($4::text = 'hybrid' AND o.work_mode = 'remote'))
   AND (cardinality($5::text[]) = 0
        OR o.employment_type IS NULL
        OR o.employment_type = ANY ($5::text[]))
   AND (cardinality($6::char(2)[]) = 0
        OR o.language IS NULL
        OR o.language = ANY ($6::char(2)[]))
   AND o.last_seen_at > now() - $7::interval
 ORDER BY e.embedding <=> $1::vector
 LIMIT $8
`

type RetrieveByVectorParams struct {
	QueryVector      pgvector.Vector
	EmbeddingVersion string
	Countries        []string
	WorkMode         *string
	EmploymentTypes  []string
	Languages        []string
	MaxStaleness     pgtype.Interval
	MaxCandidates    int32
}

type RetrieveByVectorRow struct {
	ID          pgtype.UUID
	TitleRaw    string
	CompanyID   pgtype.UUID
	FirstSeenAt pgtype.Timestamptz
	Distance    float64
}

// Stage 1 of the two-stage matcher (blueprint §18). Bounds the work for
// everything downstream: without it, scoring is the full user x opportunity
// cross product.
//
// Two recall channels, both carrying the same hard predicates. The predicates
// are inside each channel rather than applied to its output, because filtering
// after a kNN walk discards candidates the walk already spent its budget on:
// measured on 50k vectors with a 1%-selective predicate, asking for 100 returned
// 4. The caller sets hnsw.iterative_scan for the same reason.
//
// Nothing here ranks. Ordering inside a channel only decides what survives the
// cap; the fit score in step 15 is the only thing that ranks.
// Channel 1: nearest neighbours to the profile vector among eligible postings.
//
// The planner is deliberately left to choose its own scan. Forcing the index
// makes selective predicates under-return; left alone it uses an exact scan when
// the eligible set is small (correct, and cheap precisely because it is small)
// and the HNSW index when it is large.
func (q *Queries) RetrieveByVector(ctx context.Context, arg RetrieveByVectorParams) ([]RetrieveByVectorRow, error) {
	rows, err := q.db.Query(ctx, retrieveByVector,
		arg.QueryVector,
		arg.EmbeddingVersion,
		arg.Countries,
		arg.WorkMode,
		arg.EmploymentTypes,
		arg.Languages,
		arg.MaxStaleness,
		arg.MaxCandidates,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrieveByVectorRow
	for rows.Next() {
		var i RetrieveByVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRaw,
			&i.CompanyID,
			&i.FirstSeenAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
