// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyNormalization = `-- name: ApplyNormalization :execrows
UPDATE opportunity
   SET title_normalized      = $1,
       role_family           = $2,
       seniority_ordinal     = $3,
       is_management         = $4,
       work_mode             = $5,
       location_country      = $6,
       location_city         = $7,
       remote_geo_scope      = $8,
       simhash               = $9,
       block_key             = $10,
       normalization_version = $11,
       pipeline_state        = $12,
       next_attempt_at       = now(),
       attempts              = 0,
       last_error            = NULL,
       lease_until           = NULL,
       version               = version + 1
 WHERE id = $13
   AND version = $14
   AND pipeline_state = $15
`

type ApplyNormalizationParams struct {
	TitleNormalized      string
	RoleFamily           *string
	SeniorityOrdinal     *int16
	IsManagement         bool
	WorkMode             *string
	LocationCountry      *string
	LocationCity         *string
	RemoteGeoScope       *string
	Simhash              *int64
	BlockKey             *string
	NormalizationVersion *string
	NextState            string
	ID                   pgtype.UUID
	Version              int32
	CurrentState         string
}

// Sets the derived fields AND advances the state in ONE statement.
//
// These cannot be separate: any write bumps version, which would invalidate a
// follow-up version-guarded advance and livelock the stage. This is the
// blueprint's rule that state advances in the same transaction as the work.
func (q *Queries) ApplyNormalization(ctx context.Context, arg ApplyNormalizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyNormalization,
		arg.TitleNormalized,
		arg.RoleFamily,
		arg.SeniorityOrdinal,
		arg.IsManagement,
		arg.WorkMode,
		arg.LocationCountry,
		arg.LocationCity,
		arg.RemoteGeoScope,
		arg.Simhash,
		arg.BlockKey,
		arg.NormalizationVersion,
		arg.NextState,
		arg.ID,
		arg.Version,
		arg.CurrentState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOpenMergeCandidates = `-- name: CountOpenMergeCandidates :one
SELECT count(*) FROM merge_candidate WHERE resolution IS NULL
`

func (q *Queries) CountOpenMergeCandidates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenMergeCandidates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findBlockCandidates = `-- name: FindBlockCandidates :many
SELECT o.id, o.company_id, o.ats_type, o.title_normalized, o.content_hash,
       o.simhash, o.location_country, o.remote_geo_scope,
       coalesce(length(o.description_text), 0)::int AS text_len,
       s.apply_url, s.ats_job_id
  FROM opportunity o
  LEFT JOIN opportunity_source s ON s.opportunity_id = o.id
 WHERE o.block_key = $1
   AND o.id <> $2
   AND o.merged_into IS NULL
   -- A human already said these are different roles. A simhash is not entitled
   -- to overrule that, so an un-merged posting is never a merge candidate again.
   AND o.unmerged_at IS NULL
   AND o.closed_at IS NULL
 LIMIT $3::int
`

type FindBlockCandidatesParams struct {
	BlockKey      *string
	ExcludeID     pgtype.UUID
	MaxCandidates int32
}

type FindBlockCandidatesRow struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	AtsType         *string
	TitleNormalized string
	ContentHash     []byte
	Simhash         *int64
	LocationCountry *string
	RemoteGeoScope  *string
	TextLen         int32
	ApplyUrl        *string
	AtsJobID        *string
}

// Only ever compares within a block, and never against a row already merged
// away or closed.
func (q *Queries) FindBlockCandidates(ctx context.Context, arg FindBlockCandidatesParams) ([]FindBlockCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findBlockCandidates, arg.BlockKey, arg.ExcludeID, arg.MaxCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindBlockCandidatesRow
	for rows.Next() {
		var i FindBlockCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.AtsType,
			&i.TitleNormalized,
			&i.ContentHash,
			&i.Simhash,
			&i.LocationCountry,
			&i.RemoteGeoScope,
			&i.TextLen,
			&i.ApplyUrl,
			&i.AtsJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLatestMergeFor = `-- name: FindLatestMergeFor :one
SELECT id, from_opportunity_id, into_opportunity_id, reason, confidence, source_rows_moved, merged_by, merged_at, undone_at, moved_source_ids FROM opportunity_merge
 WHERE from_opportunity_id = $1 AND undone_at IS NULL
 ORDER BY merged_at DESC
 LIMIT 1
`

// The merge that hid this posting, so it can be reversed.
func (q *Queries) FindLatestMergeFor(ctx context.Context, fromOpportunityID pgtype.UUID) (OpportunityMerge, error) {
	row := q.db.QueryRow(ctx, findLatestMergeFor, fromOpportunityID)
	var i OpportunityMerge
	err := row.Scan(
		&i.ID,
		&i.FromOpportunityID,
		&i.IntoOpportunityID,
		&i.Reason,
		&i.Confidence,
		&i.SourceRowsMoved,
		&i.MergedBy,
		&i.MergedAt,
		&i.UndoneAt,
		&i.MovedSourceIds,
	)
	return i, err
}

const findMultiMemberBlocks = `-- name: FindMultiMemberBlocks :many
SELECT block_key, count(*) AS members
  FROM opportunity
 WHERE block_key IS NOT NULL
   AND merged_into IS NULL
   AND closed_at IS NULL
 GROUP BY block_key
HAVING count(*) > 1
 ORDER BY count(*) DESC
 LIMIT $1::int
`

type FindMultiMemberBlocksRow struct {
	BlockKey *string
	Members  int64
}

// Dedup is order-dependent: on a bulk first ingest two identical postings can
// each complete before the other's block_key is visible, so neither ever sees
// the other. This makes dedup eventually consistent instead.
func (q *Queries) FindMultiMemberBlocks(ctx context.Context, batch int32) ([]FindMultiMemberBlocksRow, error) {
	rows, err := q.db.Query(ctx, findMultiMemberBlocks, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindMultiMemberBlocksRow
	for rows.Next() {
		var i FindMultiMemberBlocksRow
		if err := rows.Scan(&i.BlockKey, &i.Members); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpportunityForDedupe = `-- name: GetOpportunityForDedupe :one
SELECT o.id, o.version, o.company_id, o.title_normalized, o.content_hash,
       o.simhash, o.block_key, o.location_country, o.remote_geo_scope, o.ats_type,
       coalesce(length(o.description_text), 0)::int AS text_len,
       s.apply_url, s.ats_job_id
  FROM opportunity o
  LEFT JOIN opportunity_source s ON s.opportunity_id = o.id
 WHERE o.id = $1
 LIMIT 1
`

type GetOpportunityForDedupeRow struct {
	ID              pgtype.UUID
	Version         int32
	CompanyID       pgtype.UUID
	TitleNormalized string
	ContentHash     []byte
	Simhash         *int64
	BlockKey        *string
	LocationCountry *string
	RemoteGeoScope  *string
	AtsType         *string
	TextLen         int32
	ApplyUrl        *string
	AtsJobID        *string
}

func (q *Queries) GetOpportunityForDedupe(ctx context.Context, id pgtype.UUID) (GetOpportunityForDedupeRow, error) {
	row := q.db.QueryRow(ctx, getOpportunityForDedupe, id)
	var i GetOpportunityForDedupeRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CompanyID,
		&i.TitleNormalized,
		&i.ContentHash,
		&i.Simhash,
		&i.BlockKey,
		&i.LocationCountry,
		&i.RemoteGeoScope,
		&i.AtsType,
		&i.TextLen,
		&i.ApplyUrl,
		&i.AtsJobID,
	)
	return i, err
}

const getOpportunityForNormalize = `-- name: GetOpportunityForNormalize :one
SELECT id, version, title_raw, location_region, description_text, company_id
  FROM opportunity WHERE id = $1
`

type GetOpportunityForNormalizeRow struct {
	ID              pgtype.UUID
	Version         int32
	TitleRaw        string
	LocationRegion  *string
	DescriptionText *string
	CompanyID       pgtype.UUID
}

func (q *Queries) GetOpportunityForNormalize(ctx context.Context, id pgtype.UUID) (GetOpportunityForNormalizeRow, error) {
	row := q.db.QueryRow(ctx, getOpportunityForNormalize, id)
	var i GetOpportunityForNormalizeRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.TitleRaw,
		&i.LocationRegion,
		&i.DescriptionText,
		&i.CompanyID,
	)
	return i, err
}

const isUnmerged = `-- name: IsUnmerged :one
SELECT (merged_into IS NULL)::boolean AS unmerged FROM opportunity WHERE id = $1
`

func (q *Queries) IsUnmerged(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUnmerged, id)
	var unmerged bool
	err := row.Scan(&unmerged)
	return unmerged, err
}

const listBlockMembers = `-- name: ListBlockMembers :many
SELECT o.id, o.version, o.company_id, o.title_normalized, o.content_hash,
       o.simhash, o.location_country, o.remote_geo_scope, o.ats_type, o.first_seen_at,
       coalesce(length(o.description_text), 0)::int AS text_len,
       s.apply_url, s.ats_job_id
  FROM opportunity o
  LEFT JOIN opportunity_source s ON s.opportunity_id = o.id
 WHERE o.block_key = $1
   AND o.merged_into IS NULL
   AND o.unmerged_at IS NULL
   AND o.closed_at IS NULL
 ORDER BY o.first_seen_at, o.id
`

type ListBlockMembersRow struct {
	ID              pgtype.UUID
	Version         int32
	CompanyID       pgtype.UUID
	TitleNormalized string
	ContentHash     []byte
	Simhash         *int64
	LocationCountry *string
	RemoteGeoScope  *string
	AtsType         *string
	FirstSeenAt     pgtype.Timestamptz
	TextLen         int32
	ApplyUrl        *string
	AtsJobID        *string
}

func (q *Queries) ListBlockMembers(ctx context.Context, blockKey *string) ([]ListBlockMembersRow, error) {
	rows, err := q.db.Query(ctx, listBlockMembers, blockKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockMembersRow
	for rows.Next() {
		var i ListBlockMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CompanyID,
			&i.TitleNormalized,
			&i.ContentHash,
			&i.Simhash,
			&i.LocationCountry,
			&i.RemoteGeoScope,
			&i.AtsType,
			&i.FirstSeenAt,
			&i.TextLen,
			&i.ApplyUrl,
			&i.AtsJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBlock = `-- name: LockBlock :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

// Serializes merge decisions within one block for the duration of the
// transaction. Without it two workers in the same block can each merge into the
// other, producing an A->B->A cycle that no later read can untangle.
func (q *Queries) LockBlock(ctx context.Context, blockKey string) error {
	_, err := q.db.Exec(ctx, lockBlock, blockKey)
	return err
}

const markMerged = `-- name: MarkMerged :execrows
UPDATE opportunity SET merged_into = $1, version = version + 1
 WHERE id = $2 AND merged_into IS NULL
`

type MarkMergedParams struct {
	IntoID pgtype.UUID
	FromID pgtype.UUID
}

func (q *Queries) MarkMerged(ctx context.Context, arg MarkMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMerged, arg.IntoID, arg.FromID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveSourceRows = `-- name: MoveSourceRows :many
UPDATE opportunity_source
   SET opportunity_id = $1,
       merge_reason = $2,
       merge_confidence = $3,
       merged_by = 'dedupe'
 WHERE opportunity_id = $4
RETURNING id
`

type MoveSourceRowsParams struct {
	IntoID     pgtype.UUID
	Reason     *string
	Confidence *float32
	FromID     pgtype.UUID
}

// Returns the ids it moved, not just how many.
//
// The count alone made un-merge impossible: with two merges into one canonical
// there is no way to infer which rows came from where. Hard rule 11 says merges
// are reversible, and this is what makes that true rather than aspirational.
func (q *Queries) MoveSourceRows(ctx context.Context, arg MoveSourceRowsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, moveSourceRows,
		arg.IntoID,
		arg.Reason,
		arg.Confidence,
		arg.FromID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const normalizationStats = `-- name: NormalizationStats :many
SELECT normalization_version,
       count(*) AS total,
       count(role_family) AS with_family,
       count(seniority_ordinal) AS with_seniority,
       count(location_country) AS with_country,
       count(*) FILTER (WHERE is_management) AS management
  FROM opportunity
 WHERE merged_into IS NULL
 GROUP BY normalization_version
`

type NormalizationStatsRow struct {
	NormalizationVersion *string
	Total                int64
	WithFamily           int64
	WithSeniority        int64
	WithCountry          int64
	Management           int64
}

func (q *Queries) NormalizationStats(ctx context.Context) ([]NormalizationStatsRow, error) {
	rows, err := q.db.Query(ctx, normalizationStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NormalizationStatsRow
	for rows.Next() {
		var i NormalizationStatsRow
		if err := rows.Scan(
			&i.NormalizationVersion,
			&i.Total,
			&i.WithFamily,
			&i.WithSeniority,
			&i.WithCountry,
			&i.Management,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueMergeCandidate = `-- name: QueueMergeCandidate :exec
INSERT INTO merge_candidate (left_opportunity_id, right_opportunity_id, reason,
                             confidence, withheld_because)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (left_opportunity_id, right_opportunity_id) DO NOTHING
`

type QueueMergeCandidateParams struct {
	LeftOpportunityID  pgtype.UUID
	RightOpportunityID pgtype.UUID
	Reason             string
	Confidence         float32
	WithheldBecause    string
}

// Idempotent: re-running the sweep must not queue the same pair twice.
func (q *Queries) QueueMergeCandidate(ctx context.Context, arg QueueMergeCandidateParams) error {
	_, err := q.db.Exec(ctx, queueMergeCandidate,
		arg.LeftOpportunityID,
		arg.RightOpportunityID,
		arg.Reason,
		arg.Confidence,
		arg.WithheldBecause,
	)
	return err
}

const recordMerge = `-- name: RecordMerge :one
INSERT INTO opportunity_merge (from_opportunity_id, into_opportunity_id, reason,
                               confidence, source_rows_moved, merged_by,
                               moved_source_ids)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, from_opportunity_id, into_opportunity_id, reason, confidence, source_rows_moved, merged_by, merged_at, undone_at, moved_source_ids
`

type RecordMergeParams struct {
	FromOpportunityID pgtype.UUID
	IntoOpportunityID pgtype.UUID
	Reason            string
	Confidence        *float32
	SourceRowsMoved   int32
	MergedBy          string
	MovedSourceIds    []pgtype.UUID
}

func (q *Queries) RecordMerge(ctx context.Context, arg RecordMergeParams) (OpportunityMerge, error) {
	row := q.db.QueryRow(ctx, recordMerge,
		arg.FromOpportunityID,
		arg.IntoOpportunityID,
		arg.Reason,
		arg.Confidence,
		arg.SourceRowsMoved,
		arg.MergedBy,
		arg.MovedSourceIds,
	)
	var i OpportunityMerge
	err := row.Scan(
		&i.ID,
		&i.FromOpportunityID,
		&i.IntoOpportunityID,
		&i.Reason,
		&i.Confidence,
		&i.SourceRowsMoved,
		&i.MergedBy,
		&i.MergedAt,
		&i.UndoneAt,
		&i.MovedSourceIds,
	)
	return i, err
}

const restoreMergedOpportunity = `-- name: RestoreMergedOpportunity :execrows
UPDATE opportunity
   SET merged_into = NULL, unmerged_at = now(), pipeline_state = 'deduped',
       version = version + 1, attempts = 0, last_error = NULL,
       next_attempt_at = now(), lease_until = NULL
 WHERE id = $1 AND merged_into IS NOT NULL
`

// Makes the posting visible again and marks it as human-unmerged.
//
// unmerged_at is what stops dedup re-merging it on the next pass. Without it the
// operator watches their un-merge undo itself: the posting becomes claimable, the
// same block yields the same near-identical pair, and the heuristic wins.
//
// pipeline_state moves to 'deduped' rather than staying where it was, so the
// posting resumes AFTER the dedupe stage and continues to enrichment on its own.
func (q *Queries) RestoreMergedOpportunity(ctx context.Context, opportunityID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreMergedOpportunity, opportunityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreSourceRows = `-- name: RestoreSourceRows :execrows
UPDATE opportunity_source
   SET opportunity_id = $1,
       merge_reason = NULL, merge_confidence = NULL, merged_by = NULL
 WHERE id = ANY ($2::uuid[])
`

type RestoreSourceRowsParams struct {
	BackToID     pgtype.UUID
	SourceRowIds []pgtype.UUID
}

// Moves exactly the rows a merge moved back to the posting they came from, and
// clears the merge provenance from them.
func (q *Queries) RestoreSourceRows(ctx context.Context, arg RestoreSourceRowsParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreSourceRows, arg.BackToID, arg.SourceRowIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const undoMerge = `-- name: UndoMerge :one
UPDATE opportunity_merge SET undone_at = now()
 WHERE id = $1 AND undone_at IS NULL
RETURNING id, from_opportunity_id, into_opportunity_id, reason, confidence, source_rows_moved, merged_by, merged_at, undone_at, moved_source_ids
`

// Marks the merge record reversed. One of three statements that make up an
// un-merge; see internal/admin.Unmerge for the whole operation, which must run in
// one transaction or a crash leaves a posting neither merged nor visible.
func (q *Queries) UndoMerge(ctx context.Context, id pgtype.UUID) (OpportunityMerge, error) {
	row := q.db.QueryRow(ctx, undoMerge, id)
	var i OpportunityMerge
	err := row.Scan(
		&i.ID,
		&i.FromOpportunityID,
		&i.IntoOpportunityID,
		&i.Reason,
		&i.Confidence,
		&i.SourceRowsMoved,
		&i.MergedBy,
		&i.MergedAt,
		&i.UndoneAt,
		&i.MovedSourceIds,
	)
	return i, err
}
